### ISSUE TITLE
Uncaught Java exception when launching browser from ZAP desktop

### ISSUE THREAD

**Issue by CollegiateComputer** [zaproxy/zaproxy#5285] opened 2019-03-23 14:06 UTC
**Describe the bug**
Uncaught Java exception thrown when launching browser from ZAP desktop. 

**To Reproduce**
1. Launch ZAP desktop.
2. Select launch browser from "Quick Start" menu
3. See error

**Expected behavior**
Handler for exception

**Screenshots**
N/A

**Software versions**
 - ZAP: Version D-2019-03-18
 - Add-on: N/A
 - OS: Ubuntu 18.0.4.2 LTS
 - Java: openjdk 10.0.2 2018-07-17
 - Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Errors from the zap.log file**
```
Mar 23, 2019 9:47:37 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
61936 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: valid modelIndex: 0 <= index < 2 but was: 2
	at org.jdesktop.swingx.sort.DefaultSortController.convertRowIndexToView(DefaultSortController.java:335)
	at java.desktop/javax.swing.JTable.convertRowIndexToView(JTable.java:2632)
	at java.desktop/javax.swing.JTable.repaintSortedRows(JTable.java:4205)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4146)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4425)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsUpdated(AbstractTableModel.java:247)
	at org.zaproxy.zap.utils.PagingTableModel.setData(PagingTableModel.java:339)
	at org.zaproxy.zap.utils.PagingTableModel.access$100(PagingTableModel.java:59)
	at org.zaproxy.zap.utils.PagingTableModel$SegmentLoaderThread$1.run(PagingTableModel.java:432)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Additional context**
Also experiencing an issue with ZAP HUD. Separate issue opened in ZAP HUD issues, but I'm not sure if this is, or could potentially be, related to the HUD as well.

**Comment by thc202** [comment] 2019-06-19 20:27
This is not related to the HUD (it's just triggered by it).

Duplicate of #4044.

**Closed by thc202** 2019-06-19 20:27 UTC
Labels: bug
