### ISSUE TITLE
Proxy connection refused when attempting connection through Postman

### ISSUE THREAD

**Issue by adispennette** [zaproxy/zaproxy#5140] opened 2018-12-07 23:43 UTC
**Describe the bug**
I have opened a [this](https://github.com/postmanlabs/postman-app-support/issues/5626) ticket with Postman for more information on why the proxy connection is being refused.  
As I mentioned in the other post when executing in Firefox I see the request being intercepted by Zap.

This is a request/inquiry to know if there is or can be a better way to integrate Postman requests into ZAP

**Comment by adispennette** [comment] 2018-12-10 15:54
@kingthorin Thanks for the update.  Is there a plan for supporting IPv6?

**Comment by kingthorin** [comment] 2018-12-10 16:23
I believe that's going to be part of: https://github.com/zaproxy/zaproxy/issues/1765 but we do not have an ETA at this time.

**Comment by kingthorin** [comment] 2019-02-16 02:53
Can this be closed as a dupe of 3705?

**Comment by thc202** [comment] 2019-02-16 08:13
Yes.

**Closed by thc202** 2019-02-16 08:13 UTC
