### ISSUE TITLE
GUI overlays duplicate portions of itself 

### ISSUE THREAD

**Issue by TMProgramming** [zaproxy/zaproxy#6332] opened 2020-11-30 17:09 UTC
**Describe the bug**
When running OWASP ZAP the GUI will begin to overlay duplicates of the screen over the UI when mousing around the screen.

**To Reproduce**
1. Startup ZAP
2. Open Firefox and start FoxyProxy
3. Navigate to target site
4. Begin filling the site tree by navigating the target site.
5. After a few minutes, 3-5 in my experience, select and endpoint.
6. View Request & Response 
7. Error will occur where portions of the screen are obscured by portions of duplicated GUI. 

**Expected behavior**
Expected to be able to clearly move from endpoint to endpoint without any portion of ZAP being obscured.

**Screenshots**
![image](https://user-images.githubusercontent.com/53239298/100640721-c13fc600-3304-11eb-8dbf-2ef1aa30a28e.png)

**Software versions**
 - ZAP: Version: 2.9.0
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: Windows 10 Version: 20H2 Build: 19042.630
 - Java: Oracle Corporation 1.8.0_271
 - Browser: FireFox 83.0

**Errors from the zap.log file**
None generated

**Would you like to help fix this issue?**
I'd be happy to try.

**Comment by kingthorin** [comment] 2020-11-30 17:25
Im unable to duplicate this on any of the Win10 boxes I have access to. I suspect this might be a java or video driver issue.

**Comment by psiinon** [comment] 2020-11-30 17:31
I've never seen this either, and used ZAP on Win10 for years...

**Comment by TMProgramming** [comment] 2020-11-30 17:39
I've uninstalled and reinstalled the video driver as well as Java on multiple occasions but the issue persists.

**Comment by kingthorin** [comment] 2020-11-30 18:17
Unfortunately without a way to reproduce it we don't really have a way to debug it.

**Comment by kingthorin** [comment] 2020-11-30 18:42
Do you have display scaling turned on? (Ex: something other than 100%)
![image](https://user-images.githubusercontent.com/7570458/100650119-737d8a80-3311-11eb-90d1-686e26f571e9.png)

Or are you using a High DPI display?
Does your system have/use multiple video cards? 
  - Per: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8067328 
  > On a dual graphics card system, like the Lenovo T430, the workaround is to change the configuration of the graphics driver, so that he favors the use of the second graphics card, for example. NVIDIA, on both screens. Thus the use of the Intel HD offending card is reduced or even not used anymore.


Would you be able to try a recent [weekly](https://www.zaproxy.org/download/#weekly)?

**Comment by TMProgramming** [comment] 2020-11-30 18:47
My system does indeed have dual graphics, one being the integrated on the CPU and the other is a RTX 2070. It's connected to a 1440p 144hz monitor but I also have the issue when using the laptop screen without being connected to the external monitor. I'll have to check the other settings when I get back home.

**Comment by kingthorin** [comment] 2020-11-30 19:04
Okay, thanks.

**Comment by TMProgramming** [comment] 2020-12-01 02:30
Apologies for the long delay, I have confirmed my display scale settings are set to 100%. Also, from what I can tell both displays are set to prioritize the RTX 2070 vice the integrated Intel UHD 630 graphics.

**Comment by wadim-al** [comment] 2020-12-19 19:03
I've already reported this: #6072 . This reproduces in Burp too, because it is some problem in JRE.

Solution: add the following to your startup script:
`set jvmopts=-Dsun.java2d.noddraw=true`

**Comment by thc202** [comment] 2020-12-21 10:52
@TMProgramming could you verify that the above helps?

**Comment by thc202** [comment] 2021-02-08 14:12
Closing, this is not something that we could fix from ZAP, either a JRE or driver bug. In any case it would be great if you could try the above.

**Closed by thc202** 2021-02-08 14:12 UTC
Labels: Component-UI, OpSys-Windows, Usability, bug
