### ISSUE TITLE
owasp/zap2docker-stable:latest  Getting error while building docker image on Jenkins exec /zap/zap.sh: exec format error

### ISSUE THREAD

**Issue by deepamalik18** [zaproxy/zaproxy#8444] opened 2024-04-12 13:55 UTC
### Describe the bug

 Getting error while building docker image on Jenkins exec /zap/zap.sh: exec format error

Zap Version 2.14.0
Local docker version is Docker version 20.10.21,

### Steps to reproduce the behavior

 Getting error while building docker image on Jenkins exec /zap/zap.sh: exec format error

Zap Version 2.14.0
Local docker version is Docker version 20.10.21,

### Expected behavior

Builds should not report any zap errors

### Software versions

   | exec /zap/zap.sh: exec format error

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2024-04-12 13:58
Duplicate of https://github.com/zaproxy/zaproxy/issues/8440

---

OWASP ZAP Docker images are no more, this should not be news:
https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/#docker-hub
https://www.zaproxy.org/blog/2023-10-12-zap-2-14-0/#rebranding-and-docker-hub-move

(And many more posts in the user group and other places.)

For images that should be used: https://www.zaproxy.org/docs/docker/about/#install-instructions

---

Please refer to: https://www.zaproxy.org/download/#docker

As ZAP is no longer an OWASP project the images are moving away from the OWASP Docker org and will soon no longer be available there.

The images published today/this week are still a work in progress.

**Closed by kingthorin** 2024-04-12 13:58 UTC
Labels: duplicate, Docker
