### ISSUE TITLE
Generate report for defined Context

### ISSUE THREAD

**Issue by mikilino** [zaproxy/zaproxy#4960] opened 2018-08-29 07:27 UTC
Hi there,

I found a similar issue #1924 from 2015 with no answer.
Is this feature already implemented and how to do it?

Thank you

**Comment by thc202** [comment] 2018-08-29 08:34
It's not yet implemented, the issue is still open.

Closing as duplicate of #1924.

**Closed by thc202** 2018-08-29 08:34 UTC
