### ISSUE TITLE
Zap freezes when inspecting Alerts window

### ISSUE THREAD

**Issue by pglezen** [zaproxy/zaproxy#5188] opened 2019-01-14 04:50 UTC
**Describe the bug**
The Zap UI freezes if I click any expanded content within the **Alerts** window.

**To Reproduce**
1. Run **Attack** in **Standard Mode** on small website running on my local workstation.
2. Scan completes.
3. Click **Alerts** button.  This displays four alerts.
4. Expand one of the nodes by clicking the arrow icon.  This reveals three sub-entries.  UI is still responsive at this point.  I can click other tabs and back to **Alerts**.
5. Select one of the sub-entries.  Details display in right-hand side.  But the entire UI is unresponsive.
6. Perform **force quit** on Zap.

**Expected behavior**
I expected the UI to continue to be responsive.

**Screenshots**
The last thing I see before a freeze.

![image](https://user-images.githubusercontent.com/1967533/51096612-7e0cf600-1772-11e9-9b75-147c9eaf40fe.png)

**Software versions**
 - ZAP: `7.2.0`
 - Add-on: None that I know of.
 - OS: macOS `10.12.6`
 - Java: `1.8.0_65`
 - Browser: Using **QuickStart**.

**Errors from the zap.log file**
I tailed `zap.log` during my navigation into the **Alerts** menu.  No entries are added.  This log seems to grow mostly during a test.

**Additional context**
* CPU utilization for Zap hovers at 100% (out of 400% for a quad-core) during the freeze.
* I **force quit** to stop it.
* Once (out of seven times) the problem didn't immediately happen.  I was able to navigate within the **Alert** panel for about 10 seconds before the UI froze.
* No other Zap panels give me this issue.
* Behavior is the same before and after updating all plugins.

**Comment by thc202** [comment] 2019-02-11 21:01
Are you able to obtain a thread dump when that happens?

**Comment by andresti** [comment] 2019-10-31 12:34
The same is happening to me, but I managed to wait long enough to find out that passive scan was running and when it finally finished, the interface became responsive again.

The output that eventually appeared was like this: 

> 542185 [ZAP-PassiveScanner] WARN org.zaproxy.zap.extension.pscan.PassiveScanThread  - Passive Scan rule html_mailto took 257 seconds to scan https://...somejavascript.js application/javascript 2794301
> 1940274 [ZAP-PassiveScanner] WARN org.zaproxy.zap.extension.pscan.PassiveScanThread  - Passive Scan rule X-Content-Type-Options Header Missing took 1397 seconds to scan https://...someother.chunk.js application/javascript 50944

**Comment by ChristosMylonas** [comment] 2020-07-20 13:02
Sounds similar to #5862.

**Comment by thc202** [comment] 2020-07-20 13:25
Yeah, based on the info provided it's that. Closing as duplicate of #5791.

**Closed by thc202** 2020-07-20 13:25 UTC
Labels: bug

**Comment by pglezen** [comment] 2020-07-22 04:55
Indeed, I no longer see this problem after upgrading.
