### ISSUE TITLE
TokenGen Addon - Unhandled Exceptions

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2338] opened 2016-03-19 02:38 UTC
Looks like there are some unhandled exceptions.

What should the retry policy be for timeouts? I'm going to suggest encounter a timeout, try 2 more times (for a total of 3). Try 2 other (different/new) requests, if they both fail 3 times each then abort (9 failures).

It looks like the request was skipped after 20s (at least I see a 20s/0 length response row in the results).

> 158939 [SwingWorker-pool-1-thread-3] ERROR org.zaproxy.zap.extension.tokengen.TokenGenerator  - Read timed out
> java.net.SocketTimeoutException: Read timed out
>   at java.net.SocketInputStream.socketRead0(Native Method)
>   at java.net.SocketInputStream.socketRead(Unknown Source)
>   at java.net.SocketInputStream.read(Unknown Source)
>   at java.net.SocketInputStream.read(Unknown Source)
>   at java.io.BufferedInputStream.fill(Unknown Source)
>   at java.io.BufferedInputStream.read(Unknown Source)
>   at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
>   at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
>   at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
>   at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
>   at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
>   at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
>   at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
>   at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
>   at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
>   at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
>   at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
>   at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
>   at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
>   at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
>   at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
>   at org.zaproxy.zap.extension.tokengen.TokenGenerator.doInBackground(TokenGenerator.java:66)
>   at org.zaproxy.zap.extension.tokengen.TokenGenerator.doInBackground(TokenGenerator.java:29)
>   at javax.swing.SwingWorker$1.call(Unknown Source)
>   at java.util.concurrent.FutureTask.run(Unknown Source)
>   at javax.swing.SwingWorker.run(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at java.lang.Thread.run(Unknown Source)

...

> 230665 [Thread-13] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "Thread-13"
> java.lang.NullPointerException
>   at org.zaproxy.zap.extension.tokengen.CharacterFrequencyMap.checkCharacterTransitions(CharacterFrequencyMap.java:221)
>   at org.zaproxy.zap.extension.tokengen.TokenAnalyserThread.run(TokenAnalyserThread.java:103)

**Comment by thc202** [comment] 2016-03-21 11:42
Technically all requests are the same, I guess 2 consecutive failed retries (i.e. 3 consecutive failed requests) would be enough to abort.

**Comment by kingthorin** [comment] 2016-12-19 01:46
So I've put together a simple fix for this. SocketTimeoutException is caught now and the token generation count is reduced by one (so if you ask for 20000 samples, have 16 timeouts, you endup with a table with 20016 results). 

I wasn't able to recreate the NPE secondary issue with any regularity, I did see it, but couldn't make it happen on demand :(

Along the way I also noticed that the initial dialog isn't properly sized (`pack()` is never called). So on my system at least it initially appears with a scroll bar.

I also noticed that this addon hasn't had zaproxy/zaproxy#2000 (Title Caps) treatment.

Can I bundle all 3 together as a single PR? Or should I separate the TimeOut fix as one and then bundled UI and Title Caps as one?

**Comment by thc202** [comment] 2016-12-21 11:35
How often did the NPE happen? I'm not able to reproduce that at all :/ (it seems to be concurrency issue, token should not be null).

**Comment by kingthorin** [comment] 2016-12-21 16:11
Maybe like 5% of the times I've run it.

**Comment by thc202** [comment] 2017-01-03 10:29
Fixed in zaproxy/zap-extensions#672.

**Closed by thc202** 2017-01-03 10:29 UTC
Labels: add-on, bug
