### ISSUE TITLE
Missing response.url when calling zest script-based authentication

### ISSUE THREAD

**Issue by cjuroz** [zaproxy/zaproxy#4879] opened 2018-07-27 11:11 UTC
We are trying to integrate ZAP in our CI/CD process. To authenticate in our websites (we are unable to handle saml request/response within ZAP) we are using "script-based authentication" and zest script.

- Zest script looks like this:
![image](https://user-images.githubusercontent.com/10542942/43316903-695ff750-91cd-11e8-809a-ae79b77af334.png)

Context object authentication uses above zest script with "LoginURL" parameter, also user is added in context object and passed to zest script as "Username" and "Password".

When scan process is triggered on login page (Sites -> Attack -> Spider...):

1. ZAP triggers authentication by running zest script. 
2. Zest script will open firefox instance and successfully login but from ZAP point of view authentication will fail and 
3. It will retry by executing again zest script. Because of this, firefox instances will keep popup as authentication always will fails.

After checking zap logs we found this is causing whole authentication process to fail: 

`2018-07-27 18:14:03,400 [ZAP-SpiderThreadPool-0-thread-1] DEBUG ZestZapRunner - getVariable response.url : null`

And after inspecting this stacktrace:

`2018-07-27 18:14:03,401 [ZAP-SpiderThreadPool-0-thread-1] ERROR ScriptBasedAuthenticationMethodType - An error occurred while trying to authenticate using the Authentication Script: Contoso auth
javax.script.ScriptException: org.apache.commons.httpclient.URIException: URI-Reference required
	at org.zaproxy.zap.extension.zest.ZestAuthenticationRunner.authenticate(ZestAuthenticationRunner.java:111)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethod.authenticate(ScriptBasedAuthenticationMethodType.java:237)
	at org.zaproxy.zap.users.User.authenticate(User.java:255)
	at org.zaproxy.zap.users.User.processMessageToMatchUser(User.java:171)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:497)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:362)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(SpiderTask.java:424)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.commons.httpclient.URIException: URI-Reference required
	at org.apache.commons.httpclient.URI.parseUriReference(URI.java:1901)
	at org.apache.commons.httpclient.URI.<init>(URI.java:179)
	at org.zaproxy.zap.extension.zest.ZestAuthenticationRunner.authenticate(ZestAuthenticationRunner.java:97)
	... 12 more`

We found the problem is in this part of code: https://github.com/zaproxy/zap-extensions/blob/d84572fba670e8877bdebed3d7759c2fe1b9a6fa/src/org/zaproxy/zap/extension/zest/ZestAuthenticationRunner.java#L96

For some reason ZAP is not passing to Zest (or we are missing something here?) `response.url, request.method, request.url, request.header, request.body, response.header, response.body`

Any advice on this will be highly appreciated!

**Comment by thc202** [comment] 2020-09-16 17:46
Closing as duplicate of #5940.

**Closed by thc202** 2020-09-16 17:46 UTC
Labels: add-on, bug, duplicate
