### ISSUE TITLE
Allow to filter WebSocket messages on Payload through the UI

### ISSUE THREAD

**Issue by gaardiolor** [zaproxy/zaproxy#4716] opened 2018-06-01 14:00 UTC
**Is your feature request related to a problem? Please describe.**
The filter option in the 'Websockets' tab is limited, it only allows to filter on message type. It would be nice to be able to filter on payload (regex). 

**Describe the solution you'd like**
Change the UI in order to make it possible to filter on payload text, using a regex. 

**Describe alternatives you've considered**
Probably this is possible through the API, I haven't tried yet. Regardless, it'd be nice if it's possible in the UI. 

**Additional context**
Current options:
![image](https://user-images.githubusercontent.com/22920143/40844661-d70a547a-65b4-11e8-9163-cb9c9c72430f.png)

**Comment by ManosMagnus** [comment] 2018-06-01 14:11
That has been already implemented. Please take a look at https://github.com/zaproxy/zap-extensions/pull/1506.

**Comment by thc202** [comment] 2018-06-01 14:12
Yes. Closing, duplicate of #1382. It's included in the weekly releases. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Closed by thc202** 2018-06-01 14:12 UTC

**Comment by gaardiolor** [comment] 2018-06-01 14:16
Nice! Sorry I didn't see that. Thanks.

**Comment by ManosMagnus** [comment] 2018-06-01 14:26
No problem. If you want to help zap websocket scanning project, let as know about more websocket protocol example https://groups.google.com/forum/#!msg/zaproxy-develop/kAUD7XbIetQ/1OdbdRnKAwAJ
