### ISSUE TITLE
zap-api-scan.py is missing the  -I option

### ISSUE THREAD

**Issue by mr-duke** [zaproxy/zaproxy#6048] opened 2020-06-24 16:04 UTC
**Describe the bug**
zap-api-scan.py is missing the  -I option

**To Reproduce**
I'm using GitLab CI and owasp/zap2docker-stable as the base image
Here's my gitlab-ci.yml:
```
script: 
   zap-api-scan.py
      -t ABC/swagger/swagger.json
      -f openapi
      -r ${FILENAME_ZAP_REPORT}.html
      -I
```

**Expected behavior**
It shouldn't return error code 2 even if there are warnings.

**Software versions**
- Gitlab CI
- owasp/zap2docker-stable as the base image

**Errors from the zap.log file**
Error Message from GitLab:
`2020-06-24 15:48:21,095 Invalid option I : option -I not recognized`

**Would you like to help fix this issue?**
According to the [source code ](https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-api-scan.py)of the Python script the -I option is included. Why is it not recognized anymore?

**Comment by kingthorin** [comment] 2020-06-24 16:21
That was [fixed/added in April](https://github.com/zaproxy/zaproxy/commits/develop/docker/zap-api-scan.py), if you're using stable docker you don't have that update.

You have two options:
1. Use the weekly or live image.
2. Don't use the option until it hits the stable image. (After 2.10.0 [or whatever] is released.)

**Comment by kingthorin** [comment] 2020-06-24 16:47
Closing as duplicate of zaproxy/zaproxy#5928

**Closed by kingthorin** 2020-06-24 16:47 UTC
Labels: Docker, duplicate, question
