### ISSUE TITLE
Remove code deprecated in 2.5.0

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#7069] opened 2022-02-03 17:10 UTC
This is a handle turning exercise - no coding skill is needed, you just need to be thorough :)

1. Find out what needs to be removed: `grep -R deprec zap/src/main/java | grep "2.5.0"` - there should be 41 matches
2. Remove the classes / methods / fields found above
3. Add a `ZAP` header to any `paros` code changed (see examples below)
4. Add the affected classes / methods / fields to `zap/zap.gradle.kts` (see below)
5. Run `spotlessApply`
6. Run `./gradlew japicmp` - it should pass, if not check the report it generates
7. Update the corresponding help file (see below)

Example PRs:

2.2.0 + 2.3.0: code: https://github.com/zaproxy/zaproxy/pull/7067 help: https://github.com/zaproxy/zap-core-help/pull/414
2.4.x: code: https://github.com/zaproxy/zaproxy/pull/7068 help: https://github.com/zaproxy/zap-core-help/pull/415

**Comment by njmulsqb** [comment] 2022-02-03 17:57
Hi @psiinon, 

Though I have no idea about paros, spotlessApply and japicmp but I would love to learn, if you don't mind me asking questions here about problems I face during work on this issue, please assign this to me! :)

**Comment by psiinon** [comment] 2022-02-03 18:02
Assigned :D 
You'll need to set up a ZAP development environment - more details here https://www.zaproxy.org/docs/developer/
Let us know how you get on!

**Comment by njmulsqb** [comment] 2022-02-04 16:43
> Assigned :D You'll need to set up a ZAP development environment - more details here https://www.zaproxy.org/docs/developer/ Let us know how you get on!

Hi, I have set up the development environment today using intelliJ IDEA, it took me way longer than I expected, I have cloned zap-hud, zaproxy and zap extensions and upon building its failing. It has took lots of time for gradle to download its dependencies

Here's the screenshot of error when I try to run ZAP.main()
![image](https://user-images.githubusercontent.com/47940898/152567863-4fd461cb-9291-45a9-85f2-64bdfe2a7315.png)

**Comment by thc202** [comment] 2022-02-04 16:48
Use Java 8 or 11 to build ZAP.

**Comment by njmulsqb** [comment] 2022-02-05 07:58
I changed the machine and downloaded JDK 11, repeated the process all over again, now its showing this.
I have tried
1. Invalidating cache
2. Rebuilding gradle 
The issue persists
![image](https://user-images.githubusercontent.com/47940898/152633669-e1e9cb71-da39-484f-b5f9-0b04c7a0a99f.png)
![image](https://user-images.githubusercontent.com/47940898/152633699-6947074c-3491-4169-848d-a6da7100a639.png)

**Comment by thc202** [comment] 2022-02-05 08:09
In the zap-extensions project run the Gradle task `copyMandatoryAddOns` https://www.zaproxy.org/docs/developer/quick-start-build/#installing-zap-add-ons

**Comment by njmulsqb** [comment] 2022-02-10 17:03
> In the zap-extensions project run the Gradle task `copyMandatoryAddOns` https://www.zaproxy.org/docs/developer/quick-start-build/#installing-zap-add-ons

I really want to start work on this issue, but am just unable to build ZAP from source. I ran `copyMandatoryAddOns` many times. I have taken fresh clones from the forks I have made after fetching upstream to have the latest code but still...
![image](https://user-images.githubusercontent.com/47940898/153458421-662864ed-a79b-4fe2-8a84-88f6c4d3374e.png)
Apologies for being such a noob

**Comment by psiinon** [comment] 2022-02-10 17:09
Are you _sure_ you have followed the instructions exactly?
I did this a couple of days ago and it worked fine :/

**Comment by njmulsqb** [comment] 2022-02-10 17:17
> Are you _sure_ you have followed the instructions exactly? I did this a couple of days ago and it worked fine :/

Yeah I believe so, have a look at above steps I have shared, am I missing something?
I have tried three different OS now

**Comment by njmulsqb** [comment] 2022-02-10 17:26
> Are `zaproxy` and `zap-extensions` contained in the same directory?

Yes they're
![image](https://user-images.githubusercontent.com/47940898/153462578-3e9c819f-0848-4743-9919-f07207932f89.png)

**Comment by kingthorin** [comment] 2022-02-10 17:44
This is likely a windows issue. That's the path the copy add-ons tasks use, so if it doesn't exist they probably fail. In which case the dev version attempts to use `C:\Users\<username>\OWASP ZAP_D\`.

I don't have any further advice, IntelliJ seems to be a P.I.T.A. to work with :cry:

I think we do have one person that uses it regularly, so it does work. I just don't know what other steps they may have had to go through, plus I think they're on Linux.

**Comment by njmulsqb** [comment] 2022-02-10 17:46
> This is likely a windows issue. That's the path the copy add-ons tasks use, so if it doesn't exist they probably fail. In which case the dev version attempts to use `C:\Users\<username>\OWASP ZAP_D\`.
> 
> I don't have any further advice, IntelliJ seems to be a P.I.T.A. to work with 😢
> 
> I think we do have one person that uses it regularly, so it does work. I just don't know what other steps they may have had to go through, plus I think they're on Linux.

I was facing same issues on WSL Kali Linux, will switching IDE help?

**Comment by kingthorin** [comment] 2022-02-10 18:14
Hmmm you can see at timestamp 4447 in your screenshot callhome and network were installed.

**Comment by thc202** [comment] 2022-02-10 18:23
If ZAP is not finding the add-ons when running from the IDE it is most likely caused by "wrong" working directory, there are instructions on how to set it for IntelliJ IDEA in: https://www.zaproxy.org/docs/developer/building-zap-with-intellij-idea/

**Comment by njmulsqb** [comment] 2022-02-11 06:36
> If ZAP is not finding the add-ons when running from the IDE it is most likely caused by "wrong" working directory, there are instructions on how to set it for IntelliJ IDEA in: https://www.zaproxy.org/docs/developer/building-zap-with-intellij-idea/#running-zap

This worked, thanks a much mate! 

> Does the folder `zaproxy\zap\bin\main\plugin\` exist?

ZAP is building fine but this directory path is still not present, is it okay? Can I move on and start work on this issue?

**Comment by thc202** [comment] 2022-02-11 08:14
Yes, you can.

**Comment by njmulsqb** [comment] 2022-02-23 11:17
Hi,

First of all, I want to apologize for such slow progress from my side as always, actually I am a full time employee and also taking part in #100DaysOfHacking challenge these days so contributing actively to FOSS is getting tough for me. But that never means that I am not willing to contribute, I always love FOSS and I want to see ZAP surpassing Burp one day in every aspect#6947 

Now coming to point, as I am doing it on Windows and it doesn't  have support for `grep` so I first tried to use the builtin search of IntelliJ IDEA within the mentioned directory to look for 2.5.0 but it returned 100+ results which is contrary to what mentioned by @psiinon i.e 41

Then I moved to `findstr` (alternative of grep in windows) its syntax was somewhat difficult to get used to, and the command that I used to fetch the number of instances of 2.5.0 in the mentioned directory was `findstr /S "2.5.0" * | find /c /v ""` which returned 190 results which again is wrong. I was trying to understand it as one should not be platform dependent but after spending some time I moved back to git bash unfortunately and the following command worked for me `grep -R deprec zap/src/main/java | grep "2.5.0" | wc -l` . I used the flag `-n` with grep to see the line number but it was returning incorrect ones e.g first finding was in line 55 of `zap/src/main/java/org/parosproxy/paros/control/Control.java` whereas actually examining the file revealed the finding is on line 610. Any idea of this behavior from grep?

Now coming to the first finding it looks something like:
![image](https://user-images.githubusercontent.com/47940898/155307234-bf7871c4-d812-47ce-93e9-75adac5ea020.png)
Now I am a bit confused what exactly to remove, I have observed the previous PRs mentioned at the top of this issue, but I think its better to confirm before committing code
1. Do I need to remove the line 609 to 610 only? Or 609 to 615? Or completely until the appearance of next comment block i.e from line 609 to 633? Can you please specify how to recognize what exactly to remove and what not?

2. After removing this if the code was under directory `paros` I will add the following tag at the top of the code **// ZAP: YYYY/MM/DD Remove deprecated createAndOpenUntitledDb() and sessionOpened()** Am I Right?  

3. In `zap.gradle.kts` I will add under methodExcludes the following lines `org/parosproxy/paros/control/Control#createAndOpenUntitledDb()` and `org/parosproxy/paros/control/Control#sessionOpened()`. Right? 
4. I can understand method and class but what exactly is field?
5. How can I find the relevant help file to add the entries?
6. In the help I will be adding following lines `<li><code>org/parosproxy/paros/control/Control#createAndOpenUntitledDb()</code></li>` and <li><code>org/parosproxy/paros/control/Control#sessionOpened()</code></li>`

I am asking questions and documenting in detail so that the issues I work on can be helpful for other newbies to read and understand that how I approached an issue as a beginner and what right/wrong approach I took?

Thanks

**Comment by kingthorin** [comment] 2022-02-23 12:20
In your example is would be 609 to 623 that you remove. Ex: The javadoc and entirety of the method it applies to.

For the zap comment in paros classes I’d suggest a generic comment like `Removed code previously deprecated in 2.5.0` or something like that.

**Comment by njmulsqb** [comment] 2022-02-24 06:28
Hi, 

I have made the changes I asked for yesterday, kindly review them.

If everything is fine, give me the green signal so that I may start work on rest of the code.

Also, I have one question, I changed the code in zap repo through IDE and pushed it, but for zap-core-help I added the changes via Github Website. Is it okay?

**Comment by njmulsqb** [comment] 2022-02-25 12:23
If a method is accepting `Plugin plugin` as one of its argument, how can I mention it in `zap.gradle.kts` file? I tried `Plugin` but japicmp fails

**Comment by psiinon** [comment] 2022-02-25 12:28
Via the full class name, as per the previous PRs mentioned in the very first comment, e.g. https://github.com/psiinon/zaproxy/blob/be03aa6d1c8eceb348091ec0b7264e6ce0a696b8/zap/zap.gradle.kts#L211 :)

**Comment by njmulsqb** [comment] 2022-02-26 07:51
FYI. These are the two PRs
1. https://github.com/zaproxy/zaproxy/pull/7102
2. https://github.com/zaproxy/zap-core-help/pull/420

**Comment by thc202** [comment] 2022-02-28 10:03
Closing, referenced PRs have been merged.

**Closed by thc202** 2022-02-28 10:03 UTC
Labels: Maintainability, IdealFirstBug, good first issue
