### ISSUE TITLE
use unstructured http request headers

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#7392] opened 2022-07-26 10:01 UTC
### Describe the bug

Hello team, when you trying to send unstructured http request headers to get an error response from the target app
zap will give you an error and it will not send the request

### Steps to reproduce the behavior

1. open re-send tab
2. send this request
```
GET https://www.knas.me HTTP/1.1
Host: www.knas.me
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
Pragma: no-cache
Cache-Control: no-cache
hello
```

### Expected behavior

send the request without parsing the value of the header `hello`

### Software versions

2.11.1 - Linux

### Screenshots

![image](https://user-images.githubusercontent.com/45688522/180980072-714cd65a-ff26-43d9-8ed1-88d1372ab148.png)

### Errors from the zap.log file

```
wModel - Could not Save Header: GET https://www.knas.me HTTP/1.1
Host: www.knas.me
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
Pragma: no-cache
Cache-Control: no-cache
hello
org.parosproxy.paros.network.HttpMalformedHeaderException: null
	at org.parosproxy.paros.network.HttpHeader.setMessage(HttpHeader.java:189) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:286) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:312) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpRequestHeader.<init>(HttpRequestHeader.java:189) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpMessage.setRequestHeader(HttpMessage.java:403) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.httppanel.view.impl.models.http.request.RequestHeaderStringHttpPanelViewModel.setData(RequestHeaderStringHttpPanelViewModel.java:52) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.httppanel.view.syntaxhighlight.HttpPanelSyntaxHighlightTextView.save(HttpPanelSyntaxHighlightTextView.java:185) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.save(HttpPanelComponentViewsManager.java:300) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.httppanel.component.split.request.RequestSplitComponent.save(RequestSplitComponent.java:195) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.httppanel.HttpPanel.saveData(HttpPanel.java:361) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.requester.ManualRequestEditorPanel.lambda$getBtnSend$0(ManualRequestEditorPanel.java:140) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6616) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3398) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6381) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4991) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4823) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4823) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2022-07-26 10:29
Closing as duplicate of #1318.

This is a known limitation of existing release versions of ZAP.

**Closed by kingthorin** 2022-07-26 10:29 UTC
Labels: bug

**Comment by thc202** [comment] 2022-07-26 10:47
That's specific to the Host header though, #4127 covers this case.
