### ISSUE TITLE
ZAP 2.5.0 crash on fullscreen - Kali

### ISSUE THREAD

**Issue by AntiGov** [zaproxy/zaproxy#3348] opened 2017-03-31 16:48 UTC
im using kali-linux rolling 2.0 the zapproxy 2.5.0 kept craching in fullscreen and but works normally in the regular size that zapproxy used par default

**Comment by psiinon** [comment] 2017-03-31 16:57
Its likely to be a kali issue rather than a ZAP one, so worth raising an issue on their tracker: https://bugs.kali.org/main_page.php

**Comment by thc202** [comment] 2017-04-24 22:38
@AntiGov version 2.6.0 is now available in Kali, although this issue is most likely caused by the JRE, would you mind trying the new version?
In any case raising an issue in Kali would greatly increase the chances of getting fixed (based on past Kali/JRE issues that affected ZAP).

**Comment by kingthorin** [comment] 2017-06-05 16:42
Closing, InsufficientEvidence

**Closed by kingthorin** 2017-06-05 16:42 UTC
Labels: InsufficientEvidence, kali

**Comment by AntiGov** [comment] 2017-07-29 23:14
i update jre to version 8 and works just fine, thanks for your replay

**Comment by thc202** [comment] 2017-07-30 09:23
Thanks for letting us know!
