### ISSUE TITLE
Unable to configure any option settings

### ISSUE THREAD

**Issue by shanpig** [zaproxy/zaproxy#6953] opened 2021-11-28 03:30 UTC
**Describe the bug**
After opening OWASP ZAP, I was not able to set the local proxy. 

**To Reproduce**
1. Open ZAP
2. Click on Tools > Options > Local Proxies
3. Click ok on the bottom right 

**Expected behavior**
When click ok, the local proxy settings should save without errors

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31932700/143727679-5ed318a8-d4e8-49a3-ab0f-42f7151d89e7.png">

**Software versions**
 - ZAP: 2.11.0
 - OS: windows 11
 - Java: 1.8.0_311
 - Browser: irrelevant

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.
```java
2021-11-28 11:26:49,143 [AWT-EventQueue-0] INFO  SSLConnector - ClientCert disabled
2021-11-28 11:26:49,143 [AWT-EventQueue-0] ERROR AbstractParamContainerPanel - Failed to save the panel: 
java.lang.NullPointerException: null
	at org.zaproxy.zap.extension.selenium.SeleniumOptions.setBrowserExtensions(SeleniumOptions.java:391) ~[?:?]
	at org.zaproxy.zap.extension.selenium.SeleniumOptionsPanel.saveParam(SeleniumOptionsPanel.java:422) ~[?:?]
	at org.parosproxy.paros.view.AbstractParamContainerPanel.saveParam(AbstractParamContainerPanel.java:681) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.view.AbstractParamDialog.saveParam(AbstractParamDialog.java:387) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.view.AbstractParamDialog$1.actionPerformed(AbstractParamDialog.java:218) [zap-2.11.0.jar:2.11.0]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_311]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_311]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_311]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_311]
	at java.awt.WaitDispatchSupport$2.run(Unknown Source) [?:1.8.0_311]
	at java.awt.WaitDispatchSupport$4.run(Unknown Source) [?:1.8.0_311]
	at java.awt.WaitDispatchSupport$4.run(Unknown Source) [?:1.8.0_311]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311]
	at java.awt.WaitDispatchSupport.enter(Unknown Source) [?:1.8.0_311]
	at java.awt.Dialog.show(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.show(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.setVisible(Unknown Source) [?:1.8.0_311]
	at java.awt.Window.setVisible(Unknown Source) [?:1.8.0_311]
	at java.awt.Dialog.setVisible(Unknown Source) [?:1.8.0_311]
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:136) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:445) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:73) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:64) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.view.MainMenuBar$3.actionPerformed(MainMenuBar.java:238) [zap-2.11.0.jar:2.11.0]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_311]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_311]
	at javax.swing.AbstractButton.doClick(Unknown Source) [?:1.8.0_311]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) [?:1.8.0_311]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_311]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_311]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_311]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_311]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_311]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_311]
```

**Additional context**

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by kingthorin** [comment] 2021-11-28 03:35
Closing as duplicate of #6951 

A fix should be available on Monday.

**Closed by kingthorin** 2021-11-28 03:35 UTC
Labels: bug, duplicate
