### ISSUE TITLE
Source Code Disclosure SVN Throws False Positive

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#1713] opened 2015-07-20 13:44 UTC
@bpapez
Per: https://github.com/zaproxy/zaproxy/issues/1498#issuecomment-122814767

Opening new issue.

> I have 2.4.0 installed and still get several false positives with Source Code Disclosure - SVN. The response codes I get are 400 Bad Request or 500 Internal Server Error and still this is counted as if SVN related sources were found.

**Comment by kingthorin** [comment] 2015-09-15 12:01
Dev ref: https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java#L134

**Comment by ElColmo** [comment] 2015-09-15 12:19
Can you clarify your attack configuration?  What "Attack Strength" have you specified?

What status code does the original request return?

The lines of code you're referring to above determine if the check is attempted at all, not whether the alert is raised.  The issue is more likely to be at lines 262-268.

Is your base assumption that "source code disclosure" is only likely to have occurred if the response code from the attack request is in the 200 - 299 range?  That might make more sense than the current implementation, admittedly.

**Comment by kingthorin** [comment] 2015-09-15 12:43
@ElColmo
I was just listing it as a developer reference for when I go to address the original issue, which was raised on someone else's behalf (refer to the original entry(ies)). I have no insight into how the original person had their scan configured. This was reported months ago, I'm just getting around to dealing with it now.

My pan for fixing the originally reported issue is to change [134-137] (https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java#L134-L137) to check HttpStatusCode.isServerError and HttpStatusCode.isClientError; at Low and Medium per the existing implementation. Leaving those still available for High and Insane. At High and Insane the checks at lines [262-268] (https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/ascanrulesBeta/SourceCodeDisclosureSVN.java#L262-L268) will still apply. I believe that maintains alignment with: [ZAP's help documentation on scanner Strength] (https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsScanpolicy#strength)

I'll also update the help entry along the way and perhaps add some "otherInfo" info :smile:

**Comment by kingthorin** [comment] 2015-09-15 12:46
Now that you've got me talking about this though, what is unclear is whether the original reporter meant that the 400s and 500s were being encountered on the original or 'attack' responses.

Reading it again I now think they may have meant the 'attack' responses which means my change would need to occur at 262-268 and also account for strength.

**Comment by ElColmo** [comment] 2015-09-15 12:51
That's what i was just thinking.  I wrote the original code, and my thinking was that, if the URL/script exists (regardless of what status it returns in normal usage), it might be possible to extract its source, if SVN files were deployed.  Following that logic, I agree the changes are needed at 262-268, and should probably be as simple as checking for a status code of 200-299. If a file has been served successfully, its either going to be a 200 series or possibly a 304 not modified (assuming cache-control request headers were not sent).

**Comment by ElColmo** [comment] 2015-09-15 12:56
Re "Other Info", what do you have in mind?  IIRC, The URL on which the alert is raised is the underlying SVN URL (rather than the URL which was attacked in the first place), so that covers the main item that the developers would need to know.

**Comment by kingthorin** [comment] 2015-09-15 13:00
For "Other Info" I'm just thinking that I'll outline the behavior delta at different strengths so that the end user knows that they can or should alter their strength setting for the particular scanner. Something like: https://github.com/zaproxy/zap-extensions/blob/master/src/org/zaproxy/zap/extension/pscanrules/resources/Messages.properties#L14

**Comment by ElColmo** [comment] 2015-09-15 13:03
Sounds good to me.

**Comment by kingthorin** [comment] 2015-09-16 00:10
@ElColmo do you have a good set of tests mocked up for this? If I produce a patch are you willing to test it?

**Comment by ElColmo** [comment] 2015-09-16 08:28
@kingthorin  I used to, but not any more, for space reasons.  My test cases comprised a couple of Subversion repos (for different versions of Subversion) for a few open source projects (including Zap!) dropped into the Apache web root /var/www folder.    I then scanned each Subversion sub folder in turn, and checked that the number of alerts for each subfolder matched what I expected.  It wasn't exactly a quick process, and it wasn't something that  I could have easily checked in as test cases either, unfortunately.

I can certainly test this looking for true positives.  In terms of test cases for false negatives, I'd probably drop in place a few PHP scripts and JSPs that return various statuses, and scan them. I'm unlikely to be able to do this today, however.

**Comment by kingthorin** [comment] 2015-09-16 12:29
@ElColmo I don't think there's any rush. This ticket has been open since July with no input from the original requester. To be honest I don't think I've encountered a hit from this scanner on a scan yet so it might be best if you review the code and do some testing (you know what you were originally seeing and after). I'm good with taking another week or two to collaborate on code and testing if that works for you?

I knocked together the code last night. I'll try to review it tonight and get you a patch (though I haven't tried generating a patch since we moved to git so that'll be a new thing too :wink:

Its also not a huge change, really its the same change applied in a few different places so simple code review might even be enough to make us comfortable with committing it.

**Comment by ElColmo** [comment] 2015-09-16 16:07
@kingthorin Sounds good to me.  I have some loose ends to take care of elsewhere that I need to attend to first, but I'll get back to this.

**Comment by kingthorin** [comment] 2015-09-23 10:53
@ElColmo just wanted to let you know that this is still on my TODO list. I've been having powersupply issues with my dev machine. Hopefully I'll be able to get you the patch later today or sometime tomorrow.

**Comment by kingthorin** [comment] 2015-09-24 00:43
Patch is here:
http://pastebin.com/VWcxZYCM
(Wish you could attach something other than images to issues on github :cry:

**Comment by ElColmo** [comment] 2015-09-24 08:26
Hi.

Nice one.  I'll need to work through the changes, and set up my environment
to test them, but the principle of what needs to be done seems right.  I
have no chance of getting that done until mid next week due to other
commitments, however.  If you want to test it yourself, I'd suggest copying
a few ".svn" folders from different projects (created using different SVN
versions, and unmodified using most recent versions) into an Apache / NGinx
folder.  I had folders for each of the SVN version numbers mentioned in the
code, but it took up lots of space as a result..

Colm

**Comment by oxitech239** [comment] 2015-10-10 17:13
i'm the original poster, i posted this based on a review of a website analysis, i did not have the actual scanner at hand or access to it's configuration.

**Comment by oxitech239** [comment] 2015-10-10 17:18
I'm the poster who posted on a the redirect preceding this thread, can i be of any assitance ? I still have a report with the erroneous redirect handling lying around somewhere.

**Comment by kingthorin** [comment] 2015-10-18 01:05
@oxitech239 I believe your issue with redirects was fixed some time ago, you'll need to ensure you update ZAP and your extensions. If you're still running an install from last year without update you'll still encounter the same problem. As for this change you'd need a ZAP dev environment in order to grab the posted patch and test it. Thanks for the offer! Let us know how you're setup and what you're up for if anything.

**Comment by kingthorin** [comment] 2015-12-31 17:36
With google code gone I no longer have access to any SVN repo to test this against.

Any objection to me creating the PR and approving just based on analysis of the logic implemented?

**Comment by ElColmo** [comment] 2016-01-01 17:16
Fine by me. I'm not in a position to test this at the moment.

**Comment by kingthorin** [comment] 2016-01-02 03:14
Check it out:
https://github.com/zaproxy/zap-extensions/pull/173

**Comment by thc202** [comment] 2016-01-13 10:12
Fixed in zaproxy/zap-extensions@81ff2243c0f62e20934f9804f2df4ff0863aa483.

**Closed by thc202** 2016-01-13 10:12 UTC
Labels: enhancement, FalsePositive, Priority-Medium
