### ISSUE TITLE
Bulk edit and shortcuts to manipulate Alerts

### ISSUE THREAD

**Issue by br-olf** [zaproxy/zaproxy#6319] opened 2020-11-24 13:18 UTC
**Is your feature request related to a problem? Please describe.**

When I'm working on in the GUI I'm getting frustrated when I need to double click every single alert to change the Confidence level.

**Describe the solution you'd like**
I want either a keyboard shortcut to set the confidence level and/or a bulk edit possibility to set the confidence level of multiple alerts at once.

**Would you like to help implementing this feature?**
I could try but I'm unfamiliar with the code and would need help. Also I've very limited time currently.

**Comment by kingthorin** [comment] 2020-11-24 13:29
You can mark False Positives from the right click context menu.

I guess that functionality could be turned into a menu/sub-menu with all confidences.

It could be modeled/re-worked based on: https://github.com/zaproxy/zaproxy/pull/5844

You can also make bulk changes by script as outlined here: https://github.com/zaproxy/zaproxy/issues/1603#issuecomment-447031828

**Comment by kingthorin** [comment] 2020-11-24 13:30
Closing as duplicate of zaproxy/zaproxy#1603

**Closed** 2020-11-24 13:30 UTC
Labels: duplicate, enhancement

**Comment by psiinon** [comment] 2020-11-24 14:02
We could always enhance Alert filters to optionally handle confidence as well as risk...

**Comment by kingthorin** [comment] 2020-11-24 14:27
To be clear the FP context menu will only be available in weeklies after ~Feb 10. 2020. (It's not available in 2.9, but will be in the up-coming 2.10.)
