### ISSUE TITLE
Change whitelist and blacklist terms

### ISSUE THREAD

**Issue by olucheye** [zaproxy/zaproxy#6189] opened 2020-09-21 17:06 UTC
Hello guys, 

Having worked on similar OSS projects recently, and also seeing current changes sweeping the ecosystem, I strongly believe that Zaproxy could make-do with a **terminology upgrade** from ones deemed hurtful, **to more functionally specific terms like "allowlist" and "blocklist"**

This could be done as a deprecation where for a period of time both terms could be used (some sort of mapping), until a specific version/date where only the new terms would work. I have done a sweep through the codebase and I would like to effect these changes if I have the team's go ahead.

**Comment by thc202** [comment] 2020-09-21 17:09
Closing as duplicate of #6029.

**Closed by thc202** 2020-09-21 17:09 UTC
Labels: Type-Task, duplicate

**Comment by psiinon** [comment] 2020-09-21 18:05
@olucheye but PRs for anything we havnt addressed yet much appreciated :)
