### ISSUE TITLE
Update error with every new network addon version

### ISSUE THREAD

**Issue by MichaelVetter** [zaproxy/zaproxy#7904] opened 2023-06-09 16:28 UTC
### Describe the bug

An update error occurs with every new network addon version and zap stops working correctly because other errors occur.
Furthermore we removed the -addonupdate option but the new plugin is still downloaded and installed.

### Steps to reproduce the behavior

Start zap via maven plugin and the following cli options when a new network addon version is available for download.
<zapOptions>-daemon -config api.disablekey=true -config api.incerrordetails=true -config network.localServers.mainProxy.enabled=false -config network.connection.httpProxy.enabled=true -config network.connection.httpProxy.host=${owasp.maven.proxy.host} -config network.connection.httpProxy.port=${owasp.maven.proxy.port} -config network.connection.httpProxy.exclusions.exclusion.host=${owaspZapTargetHost} -config network.connection.defaultUserAgent="${owaspZapDefaultUserAgent}" -config network.connection.timeoutInSecs=300 -config anticsrf.tokens.token.name=_csrf -dir ${owaspZapWork} -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta -addoninstall pscanrules -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta -addoninstall ascanrules -addoninstall spider -addoninstall spiderAjax -addoninstall reports  -newsession test</zapOptions>
            

### Expected behavior

I would expect that the new network addon is not updated when the the -addonupdate option is not used or that
that the network addon update works without an error or that zap still works correctly after a failed addon update.

### Software versions

DaemonBootstrap - OWASP ZAP 2.12.0 

### Errors from the zap.log file
```
13229 [ZAP-daemon] INFO  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - There is/are 1 newer addons
14348 [ZAP-DownloadInstaller] ERROR org.zaproxy.zap.control.AddOnInstaller - An error occurred while uninstalling libraries for [id=network, version=0.8.0]
java.nio.file.FileSystemException: c…\target\owasp-zap-work\addOnData\network\libs\bcmail-jdk18on-1.72.jar: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
	at java.nio.file.Files.delete(Files.java:1142) ~[?:?]
	at org.zaproxy.zap.control.AddOnInstaller$1.visitFile(AddOnInstaller.java:632) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnInstaller$1.visitFile(AddOnInstaller.java:627) ~[zap-2.12.0.jar:2.12.0]
	at java.nio.file.Files.walkFileTree(Files.java:2725) ~[?:?]
	at java.nio.file.Files.walkFileTree(Files.java:2797) ~[?:?]
	at org.zaproxy.zap.control.AddOnInstaller.deleteDir(AddOnInstaller.java:625) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnLibs(AddOnInstaller.java:594) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnLoader.deleteAddOn(AddOnLoader.java:691) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(AddOnLoader.java:665) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnLoader.removeAddOn(AddOnLoader.java:609) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(ExtensionAutoUpdate.java:1258) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOns(ExtensionAutoUpdate.java:1632) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOn(ExtensionAutoUpdate.java:1618) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1209) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.lambda$installNewExtensions$0(ExtensionAutoUpdate.java:647) ~[zap-2.12.0.jar:2.12.0]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(ExtensionAutoUpdate.java:643) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(ExtensionAutoUpdate.java:568) ~[zap-2.12.0.jar:2.12.0]
14357 [ZAP-DownloadInstaller] WARN  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - It's recommended to restart ZAP. Not all add-ons were successfully uninstalled: [[id=network, version=0.8.0]]
14436 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on downloaded to: …\target\owasp-zap-work\plugin\network-beta-0.9.0.zap
......
2103639 [ZAP-IO-Server-1-67] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/xml/spider/action/scan/] from [127.0.0.1]:
org.zaproxy.zap.extension.api.ApiException: no_implementor
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:445) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:100) ~[?:?]
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2023-06-09 16:50
Closing as duplicate of #7589. This should be already fixed in the weeklies.

**Closed by thc202** 2023-06-09 16:50 UTC
Labels: bug, duplicate

**Comment by MichaelVetter** [comment] 2023-06-12 07:13
@thc202 : Thank you, but what about the part with the -addonupdate option? Why is that setting ignored here?

**Comment by thc202** [comment] 2023-06-12 08:10
btw, the `-config network.localServers.mainProxy.enabled=false` has no effect, the main proxy is always enabled.
