### ISSUE TITLE
Active scan is not working on sequence scripts on ZAP 2.4.3

### ISSUE THREAD

**Issue by sukhghos** [zaproxy/zaproxy#2396] opened 2016-04-13 02:03 UTC
Steps:

1) Created a sequence of steps in Sequence scripts
2) Right click -> Active scan
No progress.

Also observed that ZAP frequently hangs when trying to modify sequence scripts or run the same.

**Comment by thc202** [comment] 2016-04-13 08:45
Might be a duplicate of #2120?
Which ZAP and Zest add-on versions are you using? (the latter can be checked in the Manage Add-ons dialogue [1])

Would you mind checking ZAP's log file to see if there's any error? (file zap.log located in ZAP's default directory or the directory manually specified [2]).

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons
[2] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by sukhghos** [comment] 2016-04-14 08:05
I was able to resolve the issue by selecting the Active scan option from Tools, and selecting the sequence and there. Please close this issue

**Closed** 2016-04-14 08:33 UTC

**Comment by thc202** [comment] 2016-04-14 08:56
@sukhghos it would be great if you could confirm (or not) that latest version of Zest add-on allows to run the Sequence script directly.
