### ISSUE TITLE
SourceCodeDisclosureSVN - Can't write to temp DB

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2177] opened 2016-01-17 12:20 UTC
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

Perhaps this is a zapbot setup issue? 

> 6124232 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | SourceCodeDisclosureSVN strength HIGH threshold MEDIUM
> 6234697 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SourceCodeDisclosureSVN  - Error executing SQL on temporary SVN SQLite database 'jdbc:sqlite:/tmp/sqlite_svn_wc_db6362615595800330987.tmp': java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
> 6234773 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SourceCodeDisclosureSVN  - Error executing SQL on temporary SVN SQLite database 'jdbc:sqlite:/tmp/sqlite_svn_wc_db470559557489452896.tmp': java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
> 6234973 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SourceCodeDisclosureSVN  - Error executing SQL on temporary SVN SQLite database 'jdbc:sqlite:/tmp/sqlite_svn_wc_db6124757841626700074.tmp': java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
> 6234973 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SourceCodeDisclosureSVN  - Error executing SQL on temporary SVN SQLite database 'jdbc:sqlite:/tmp/sqlite_svn_wc_db7042272777000175990.tmp': java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
> 6235174 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.SourceCodeDisclosureSVN  - Error executing SQL on temporary SVN SQLite database 'jdbc:sqlite:/tmp/sqlite_svn_wc_db8444117355723002456.tmp': java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is encrypted or is not a database)
> 6304414 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | SourceCodeDisclosureSVN in 180.182s

**Comment by kingthorin** [comment] 2016-01-21 13:11
@ElColmo any thoughts on this?

**Comment by ElColmo** [comment] 2016-01-21 13:32
IIRC, this error occurs if the file is empty, or is not a valid SQLite DB.

The scanner requests ".../.svn/wc.db", then creates a temp file, and drops the response body into the temp file. The scanner then treats the temp file as a SQLite db, and attempts to query it using a SQL statement.

The most likely things (in no particular order) are: 
- the temp folder is not writable?
- the filesystem on which the temp folder resides is full?
- the URL (above) being requested returns a "valid" response (not 404 / 301 / 302 / 303 / 304, etc), but does not actually return a valid wc.db file (ie, it does not return a valid SQLite database file)
- some updated "SQLite" file format?

If it's 1 or 2, then it's just a straightforward environment setup issue.

If it's 3 (which is what I think is the most likely case), I'd suggest that we could add a valid check to see if the response body binary blob actually looks like a valid SQLite db before attempting to query it as a SQLite db.  

If it's 4 (which I think is unlikely), then the SQLite library might need to be updated to support it.

**Comment by kingthorin** [comment] 2016-01-21 15:00
Good points. I think we can probably come up with a way to address most of them.

I'm going to include a few things here for reference going forward:
http://stackoverflow.com/questions/3888529/how-to-tell-if-sqlite-database-file-is-valid-or-not
http://stackoverflow.com/questions/7100597/how-do-i-check-whether-a-sqlite-database-file-exists-using-java

https://www.sqlite.org/fileformat2.html :

> **1.2.1 Magic Header String**
> 
> Every valid SQLite database file begins with the following 16 bytes (in hex): 53 51 4c 69 74 65 20 66 6f 72 6d 61 74 20 33 00. This byte sequence corresponds to the UTF-8 string "SQLite format 3" including the nul terminator character at the end.

**Comment by ElColmo** [comment] 2016-01-21 16:15
I'm not 100% certain if the SQLite database used by SVN is always expected to be version >=3 (particularly for older versions of SVN), so using the "magic header string" option could be risky.  

Maybe executing "pragma schema_version;" and checking for exceptions (or a zero response?) might be the safest way to go?

**Comment by kingthorin** [comment] 2016-02-03 12:37
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by kingthorin** [comment] 2016-04-02 02:09
Finally got back to looking at this. It seems like checks are in place to catch the majority of conditions we're concerned about here. There is a small chance that a temp file is created that doesn't have SQLite content and then a connection and query are attempted with it. However, the resultant exception is actually caught. Then the error in the original ticket details logged.

Is that overly verbose for end users? Should we log the error as is but only include the exception when isDebug is true?

**Comment by thc202** [comment] 2016-04-05 23:15
If it's case 3, IMHO it should not be logged with error level, that's expected to happen and it's not a bug/issue in ZAP. So, debug level is fine to me.

Were you able to reproduce the issue locally?

**Comment by kingthorin** [comment] 2016-04-06 03:25
Fair enough I can change the logging to accommodate that.

No I was not able to reproduce locally.

**Comment by thc202** [comment] 2016-04-18 13:26
Fixed in zaproxy/zap-extensions#305.

**Closed by thc202** 2016-04-18 13:26 UTC
Labels: BasedOnZAPBOTResults
