### ISSUE TITLE
Command output: exec /zap/zap-baseline.py: exec format error

### ISSUE THREAD

**Issue by mig5** [zaproxy/zaproxy#8441] opened 2024-04-11 21:24 UTC
### Describe the bug

I pulled the latest weekly image (`0cdb38b63e71`), which I do every week, but I got a surprise error:

```
+ sudo docker pull owasp/zap2docker-weekly:latest
latest: Pulling from owasp/zap2docker-weekly
[...]
Digest: sha256:94198b8ad41fa263bd76961efdf71903bbc8ecbb4426a99d8b4935bcfbe1e0a7
Status: Downloaded newer image for owasp/zap2docker-weekly:latest
docker.io/owasp/zap2docker-weekly:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
Command output: exec /zap/zap-baseline.py: exec format error
```

I'm not sure if the arm64 is the cause here - I don't recall having seen that before.

The previous image `ab1b4a7b9cf2d9fe280a1abdabd425b57e0b648880339a8a08882ef6a19e98a0` worked perfectly fine, just earlier in the same day.

### Steps to reproduce the behavior

```
docker pull owasp/zap2docker-weekly

docker run --user root -v /path/to/dir:/zap/wrk/:rw \
   --network=host -t owasp/zap2docker-weekly zap_baseline.py  \
   -l FAIL -I -j --hook=/zap/wrk/my-hooks.py \
   -m 10 -T 5 \
   -t https://example.com \
   -w report.html
```

### Expected behavior

ZAP should run as normal

### Software versions

```
owasp/zap2docker-weekly                                   latest    0cdb38b63e71   6 hours ago    1.71GB
```

Host is Ubuntu 20.04 amd64

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2024-04-11 21:40
Duplicate of https://github.com/zaproxy/zaproxy/issues/8440

---

OWASP ZAP Docker images are no more, this should not be news:
https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/#docker-hub
https://www.zaproxy.org/blog/2023-10-12-zap-2-14-0/#rebranding-and-docker-hub-move

(And many more posts in the user group and other places.)

For images that should be used: https://www.zaproxy.org/docs/docker/about/#install-instructions

---

Please refer to: https://www.zaproxy.org/download/#docker

As ZAP is no longer an OWASP project the images are moving away from the OWASP Docker org and will soon no longer be available there.

The images published today/this week are still a work in progress.

**Closed by kingthorin** 2024-04-11 21:40 UTC
Labels: duplicate, Docker
