### ISSUE TITLE
java.lang.OutOfMemoryError on the API

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#7041] opened 2022-01-21 02:45 UTC
hello team, I'm using zaproxy Docker image on my server and i tried to send a simple GET request from my server (on localhost) and it works but if you try to send the same request outside the server you will get this error

```
$ docker run -u zap -p 8081:8081 -i owasp/zap2docker-stable zap.sh -Xmx1024m -daemon -host 0.0.0.0 -port 8081 -config api.addrs.addr.name=0.0.0.0 -config api.addrs.addr.regex=true -config api.key=123456789

------------- --------------------
181891 [ZAP-ProxyThread-908] WARN  org.parosproxy.paros.core.proxy.ProxyThread - Failed to read http://SERVER_IP:8081/ within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
181894 [ZAP-ProxyThread-548] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "ZAP-ProxyThread-548"
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.lang.Thread.start0(Native Method) ~[?:?]
        at java.lang.Thread.start(Thread.java:798) ~[?:?]
        at org.parosproxy.paros.extension.history.ProxyListenerLog.onHttpResponseReceive(ProxyListenerLog.java:144) ~[zap-2.11.1.jar:2.11.1]
        at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerResponseReceive(ProxyThread.java:733) ~[zap-2.11.1.jar:2.11.1]
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:591) ~[zap-2.11.1.jar:2.11.1]
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) ~[zap-2.11.1.jar:2.11.1]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
i tried to change the memory size from JVM variables but it doesn't make any difference 

### Env
* Docker: owasp/zap2docker-stable
* OS : Ubuntu 21
* MEM : 4 GB
* DISK: 150GB

best regards

**Comment by kingthorin** [comment] 2022-01-21 03:34
This doesn't quite make sense.
`-config api.addrs.addr.name=0.0.0.0 -config api.addrs.addr.regex=true` isn't regex for one.

How are you trying to send the GET from outside the server? What's your API call?

Did you try setting the JVM memory settings to take more RAM? How long was the ZAP docker container running when it went OOM? How many requests had you proxied, spidered, active scanned, etc.

**Comment by knassar702** [comment] 2022-01-21 03:47
just a GET request to the root path via CURL, i tried `api.addrs.addr.name=` option but it doesn't work

Did you try setting the JVM memory settings to take more RAM : yes
How many requests had you proxied, spidered, active scanned : nothing

**Comment by kingthorin** [comment] 2022-01-21 04:35
No you can't leave it blank. It needs to be an actual pattern as outlined.

**Comment by thc202** [comment] 2022-01-21 06:02
This is a duplicate of #3594.

**Closed** 2022-02-02 11:21 UTC
Labels: question
