### ISSUE TITLE
network: change normal removal of Accept-Encoding header to being filtered to supported encoding

### ISSUE THREAD

**Issue by double16** [zaproxy/zaproxy#8124] opened 2023-10-15 11:35 UTC
### Is your feature request related to a problem? Please describe.

IMHO, ZAP should look like a legit browser as much as possible. Otherwise, site scans may be filtered.

The current behavior and recommendation from the ZAP documentation is to remove Accept-Encoding. I propose to change this to:
1. Keep the incoming Accept-Encoding values, filtering out unsupported encodings.
2. For non-proxy requests, add the supported Accept-Encoding values.

### Describe the solution you'd like

1. Keep the incoming Accept-Encoding values, filtering out unsupported encodings.
2. For non-proxy requests, add the supported Accept-Encoding values.

### Describe alternatives you've considered

A proxy script.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-10-15 12:41
Closing as duplicate of #2198.

**Closed by thc202** 2023-10-15 12:41 UTC
Labels: duplicate

**Comment by thc202** [comment] 2023-11-17 10:09
Splitting from #2198 to discuss first what behaviour we want.
