### ISSUE TITLE
Bug: Export Report... Reports issues that have been deleted from Alerts

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6106] opened 2020-07-31 13:38 UTC
**Describe the bug**
After an Active Scan runs I go through and delete out all the false positives from the Alerts tab. Then I run a report which should then give me the alerts that are left over. Unfortunately the report reports on all the findings, even the ones that have been deleted. This makes the report 'noisy' as our devs call it, and that makes them unhappy as it's more difficult to move through the report to find the things needing fixing.

**To Reproduce**
prerequesite: Completed active scan
1. Go to Alerts tab 
![image](https://user-images.githubusercontent.com/10052587/89038526-d26dcb80-d340-11ea-8ab1-aceb766f4fc8.png)

2. Delete a few false positive alerts
![image](https://user-images.githubusercontent.com/10052587/89038753-355f6280-d341-11ea-82cd-4e056b0586a5.png)

3. Go to Export Report
![image](https://user-images.githubusercontent.com/10052587/89038613-f9c49880-d340-11ea-9355-3f7e9bbdb6c6.png)

4. The false positives show up in the final report
![image](https://user-images.githubusercontent.com/10052587/89038713-22e52900-d341-11ea-9cee-1a1508ab8e30.png)

**Expected behavior**
When deleting alerts, kind of expect them to be gone, deleted, no longer a part of the scan.

**Screenshots**
inline

**Software versions**
 - ZAP: D-2020-07-28
 - Add-on: 
[2020-07-31ZAPInstalledAddOns.xlsx](https://github.com/zaproxy/zaproxy/files/5007212/2020-07-31ZAPInstalledAddOns.xlsx)

 - OS:
[Environment]::OSVersion.VersionString
Microsoft Windows NT 10.0.18363.0

 - Java: Bellsoft Liberica JDK 14
on has occurred. Program will exit.
 java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+13)
OpenJDK 64-Bit Server VM (build 14.0.2+13, mixed mode, sharing)

 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]
Chrome: Version 84.0.4147.105 (Official Build) (64-bit)
Firefox: 79.0 (64-bits)

**Errors from the zap.log file**
[2020-07-31_ZAPExportReportError.log](https://github.com/zaproxy/zaproxy/files/5007263/2020-07-31_ZAPExportReportError.log)

**Additional context**
I snapshotted the Database just before running the report.

**Would you like to help fix this issue?**
Glad to help test a fix. Thanks for having a look at this issue.

**Comment by globeone** [comment] 2020-07-31 13:38
Ooh forgot to say I exported as .XHTML

**Comment by thc202** [comment] 2020-07-31 13:43
Could you provide the whole log?

Closing as duplicate of #2593.

**Closed by thc202** 2020-07-31 13:43 UTC
Labels: bug

**Comment by globeone** [comment] 2020-07-31 13:53
[zap.log](https://github.com/zaproxy/zaproxy/files/5007348/zap.log)
The log just rolled over. here is the current log.
I'll provide the log.1 in a bit.

**Comment by globeone** [comment] 2020-07-31 14:12
[2020-07-31_zap.log.1.log](https://github.com/zaproxy/zaproxy/files/5007413/2020-07-31_zap.log.1.log)
Here is the sanitized log.1 log file as requested

**Comment by thc202** [comment] 2020-07-31 14:29
Thank you!
