### ISSUE TITLE
Use log4j 2.15.0 with zap 2.11.1 ???

### ISSUE THREAD

**Issue by happylie** [zaproxy/zaproxy#7126] opened 2022-03-08 04:59 UTC
### Describe the bug

Use log4j 2.15.0 with zap 2.11.1 ???

![log4j](https://user-images.githubusercontent.com/24468970/157168952-26e78c2b-3c40-4434-a075-fe48301bc419.png)

### Steps to reproduce the behavior

Use MacOS
I checked it below.

/Applications/OWASP ZAP.app/Contents/Java/lib

### Expected behavior

It would be better to proceed with the version update.

### Software versions

Zap 2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-03-08 06:30
Closing as duplicate of #6980.

**Closed by thc202** 2022-03-08 06:30 UTC
Labels: bug
