### ISSUE TITLE
zap-api-python: stick to one version scheme

### ISSUE THREAD

**Issue by blshkv** [zaproxy/zaproxy#4890] opened 2018-07-30 23:58 UTC
Hello, I'm a Pentoo maintainer and I find it is difficult to maintain your python package.
The official name is "zap-api-python", I would expect "zap-api-python-0.0.14.tar.gz" release name but this is not the case. The current release name is <x.y-a.b.c>, and x.y could have been an API version of zaproxy but this is not true either. Finally, it is getting published with a new URL at pypi
https://pypi.org/project/python-owasp-zap-v2/
https://pypi.org/project/python-owasp-zap-v2.4/

I can't figure out the logic of all this. Please stick it to one version scheme, it would help a lot with its maintenance.

**Comment by psiinon** [comment] 2018-07-31 07:40
We've only changed the name once in 4 years, which doesnt seem too bad to me ;)

**Comment by blshkv** [comment] 2018-07-31 07:47
I guess it is not so bad then, but that exactly does it reflects? If the answer is "nothing", can you just drop it and use a.b.c?

**Comment by psiinon** [comment] 2018-07-31 07:50
So you want us to change the name yet again??
Sorry, couldnt resist ;)
TBH part of the problem is that we're java devs and so are not so familiar with python naming conventions.
Can you suggest how we should be naming this package and its releases?

**Comment by blshkv** [comment] 2018-07-31 08:01
hehe.

well, the "traditional" way would be ```zap-api-python-0.0.14.tar.gz```.

**Comment by thc202** [comment] 2023-04-13 21:34
I think we can close this, we have not changed the name in 8 years (and counting!). (Yes, having the "v2.4" is not that great but we avoid renaming it again.)

**Comment by kingthorin** [comment] 2023-04-13 21:52
Agreed.

Malay this point there’s probably no hood argument to change until or even if we ever. Roll ZAP to 3.0

**Comment by ricekot** [comment] 2023-04-14 02:53
What we can do is create a new package and add it as a dependency for the current one. That way, things wouldn't break for people using the current package and we could encourage new users to start using the newer package. Maybe the newer package could just be called `zaproxy` in line with our primary repo name. We could use https://github.com/simonw/pypi-rename for convenience.

Not sure about the versioning though. While it would be nice to have the same version for the API client as the major ZAP version, I think that may prove difficult since the add-on APIs may change and require a package update.

**Comment by thc202** [comment] 2023-04-14 07:14
But is the current name really a problem?

**Comment by ricekot** [comment] 2023-04-14 09:08
I don't have any problems with it, I was just sharing an approach we could take if we do decide to rename the package.

**Comment by thc202** [comment] 2023-04-14 12:42
So good to close? :)

**Closed** 2023-04-14 13:57 UTC
Labels: API Client
