### ISSUE TITLE
Build instructions are generally out of date.

### ISSUE THREAD

**Issue by the-maldridge** [zaproxy/zaproxy#5519] opened 2019-08-12 01:09 UTC
**Describe the bug**
The build instructions are out of date.  The instructions clearly mention the presense of a build.xml file which can be used to generate a complete build with apache-ant.  This file, and the mentioned directory that contained it, are not part of release 2.8.0 or later.

**To Reproduce**
1.  Read the instructions in BUILDING.md
2. Observe they are not in sync with the archive that contains them.

**Expected behavior**
I expected build instructions that would lead to a build of the software.

**Screenshots**
Not Applicable

**Software versions**
Release Tag v2.8.0, void-packages collections

**Errors from the zap.log file**
Not Applicable.

**Additional context**
I encountered the issue while trying to upgrade Void's packaged copy of zaproxy.  Within void's ecosystem we are currently treating the package as Fails To Build From Source (FTBFS) and as such are considering it a candidate for removal.  Given that the recommended ways to build involve IDEs or a provided shell wrapper which downloads arbitrary build components from the internet, the current build system does not meet package guidelines for inclusion in Void's repo.  I'm happy to just expunge the package, but figured I'd check here first to see if the instructions were just out of date.

Matched Void Issue: void-linux/void-packages#13607

**Comment by kingthorin** [comment] 2019-08-12 01:41
BUILDING.md is up-to-date, what did you feel was out of sync? If you found mention of build.xml you were likely looking at an out-of-date fork. (We’ve moved from ant to gradle.)

This is at least a partial duplicate of https://github.com/zaproxy/zaproxy/issues/5094

**Comment by the-maldridge** [comment] 2019-08-12 01:49
Unless github.com/zaproxy/zaproxy is a fork, the can be chaulked up to out of date docs in the release.

Pull the archive at 2.8.0 and you will find that at the bottom of BUILDING.md, the instructions are to use ant to produce a bare build.

**Comment by psiinon** [comment] 2019-08-12 07:20
Both the master and develop branches are up to date https://github.com/zaproxy/zaproxy/blob/master/BUILDING.md
Yes, the 2.8.0 archive might be out of date, we probably updated the build instructions after that, but we're not going to re tag it now.

**Closed by psiinon** 2019-08-12 07:20 UTC
Labels: Component-Docs, third-party

**Comment by thc202** [comment] 2019-08-12 09:01
Which 2.8.0 archive are referring to? https://github.com/zaproxy/zaproxy/archive/v2.8.0.zip ? The `BUILDING.md` file was added during the migration (from Ant to Gradle) so it can't mention Ant anywhere. 

> Given that the recommended ways to build involve IDEs

That's if you want to develop/change it.

> or a provided shell wrapper which downloads arbitrary build components from the internet

You don't need to use the Gradle wrapper if you don't want to: https://docs.gradle.org/current/userguide/getting_started.html#gs:installation
