### ISSUE TITLE
Bug: Can't generate reports from saved Session data

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#2736] opened 2016-08-02 15:39 UTC
If you save a session and then restore it later, and then try to generate HTML or XML reports, now of the issues saved and restored are included in the report. If you do more scanning and new issues are found, they are included, but not the old ones.

**Comment by kingthorin** [comment] 2016-08-03 00:34
What version of ZAP are you using? Is the saved session generated with the same version?

**Comment by davewichers** [comment] 2016-08-03 00:42
Yes. And the vulns load fine. I can see them in the alerts tab. They just
don't get included on the reports.

**Comment by kingthorin** [comment] 2016-08-03 00:45
What version of ZAP? Are you generating the report via the UI or the API?

**Comment by davewichers** [comment] 2016-08-03 01:05
2.5.0 and the latest weekly. Via the UI.

**Comment by kingthorin** [comment] 2016-08-03 01:09
Hmmm weird, I just tested this with a dev version and it seems to work fine. Are the sessions you're working with particularly large?

**Comment by davewichers** [comment] 2016-08-03 01:12
I'll send you the save file via Dropbox tomorrow.

**Comment by kingthorin** [comment] 2016-08-03 01:22
Sounds good, thanks Dave.

**Comment by kingthorin** [comment] 2016-08-05 22:14
Any luck on that file Dave?

**Comment by davewichers** [comment] 2016-08-07 13:50
Sorry. Lost track of this while I was on vacation. Here you go:

https://www.dropbox.com/s/nv61o0zqoipx9a7/FullZAPScan-Banchmark-20160729-131556.session.zip?dl=0

-Dave

**Comment by kingthorin** [comment] 2016-08-08 01:15
Was this file manipulated outside of ZAP?

If you select the first level within the site tree, goto the alerts tab and click the globe icon "Link with Sites Selection", no alerts are shown....

Note the site tree also doesn't show any alert flags.

**Comment by thc202** [comment] 2016-08-09 16:14
@davewichers [attached the XML report](https://github.com/zaproxy/zaproxy/files/409367/FullZAPScan-Banchmark-20160729-131556.txt) (file extension is txt, though) generated from the session, in case you don't want to wait for the fix.

@kingthorin it generated that many messages, but the session no longer has that number. The alerts are not being correctly loaded.

**Comment by JordanGS** [comment] 2016-08-09 17:15
@kingthorin I can confirm this issue, do we know of any version that isn't affected by this? I have been working on a jenkins plugin for zap and since it loads the session after it can't properly generate the report.

**Comment by davewichers** [comment] 2016-08-15 19:56
Guys,

Sorry for the lack of replies. I was on vacation the last 3 weeks and not
paying a lot of attention to things. So, sounds like a bug was confirmed
and fixed. Is that correct?

When/what version of ZAP will have a fix so that I can try it out myself?
I'm guessing the current or next weekly release?

Thanks, Dave

**Comment by davewichers** [comment] 2016-08-21 15:16
I just downloaded the latest weekly (dated 8-15-2016), and I still get a
blank XML report when I load an existing session. Has this change been
pushed out so it 'should' be in the latest weekly or does something still
need to be done to make that happen?

Thanks, Dave

**Comment by thc202** [comment] 2016-08-22 07:50
The issue was not yet fixed in the weeklies (nor develop branch).

**Comment by davewichers** [comment] 2016-08-22 12:45
Oh. When do you expect it to get into the weekly?

Dave

On Aug 22, 2016 3:50 AM, "thc202" <notifications@github.com> wrote:

The issue was not yet fixed in the weeklies (nor develop branch).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zaproxy/zaproxy/issues/2736#issuecomment-241337697>,
or mute
the thread

**Comment by tammyhayes** [comment] 2016-08-24 16:05
I'm also experiencing this issue. Any idea when this will be fixed?

**Closed** 2016-08-30 07:28 UTC
Labels: bug

**Comment by thc202** [comment] 2016-08-31 09:13
@davewichers, @tammyhayes latest weekly contains a fix for this issue.
