### ISSUE TITLE
Error with an outgoing proxy with NTLM authentication (Unsupported or unrecognized SSL message)

### ISSUE THREAD

**Issue by farnulfo** [zaproxy/zaproxy#7714] opened 2023-01-31 17:04 UTC
### Describe the bug

To access internet websites we must use an outgoing proxy which require an NTLM authentification.
This proxy is configured in Tools/Options/Network/Connection/HTTP Proxy.
But I get error in console.

### Steps to reproduce the behavior

1. Go To Tools/Options/Network/Connection/HTTP Proxy
2. Check Enabled
3. set the Host to our outgoing proxy hostname
4. set the port to 8080
5. Check Authenticate check box
6. Set the User Name to the windows User Name
7. Set the Password
8. Click OK
9. Go to Help/Check for Update
10. Click Check for Updates
11. Error window with : Error encountered. Please check manually for new updates..."

### Expected behavior

No error

### Software versions

OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=14.0.0],
[id=ascanrules, version=49.0.0], [id=ascanrulesBeta,
version=42.0.0], [id=automation, version=0.19.0],
[id=bruteforce, version=12.0.0], [id=callhome,
version=0.5.0], [id=commonlib, version=1.11.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=14.0.0], [id=encoder, version=0.7.0], [id=exim,
version=0.3.0], [id=formhandler, version=6.1.0], [id=fuzz,
version=13.8.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.11.0],
[id=help, version=15.0.0], [id=hud, version=0.15.0],
[id=importurls, version=9.0.0], [id=invoke, version=12.0.0],
[id=network, version=0.3.0], [id=oast, version=0.13.0],
[id=onlineMenu, version=10.0.0], [id=openapi,
version=29.0.0], [id=pscanrules, version=44.0.0],
[id=quickstart, version=35.0.0], [id=replacer,
version=11.0.0], [id=reports, version=0.16.0],
[id=requester, version=7.0.0], [id=retest, version=0.4.0],
[id=retire, version=0.16.0], [id=reveal, version=5.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=soap, version=15.0.0], [id=spider,
version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips,
version=10.0.0], [id=wappalyzer, version=21.13.0],
[id=webdriverlinux, version=46.0.0], [id=webdrivermacos,
version=47.0.0], [id=webdriverwindows, version=46.0.0],
[id=websocket, version=27.0.0], [id=zest, version=37.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 11.0.14.1
System's Locale: fr_FR
Display Locale: en_GB
Format Locale: fr_FR
Default Charset: windows-1252
ZAP Home Directory: C:\Users\farnulfo\OWASP ZAP\
ZAP Installation Directory: C:\Applications\Tools\ZAP_2.12.0_Crossplatform\ZAP_2.12.0\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Errors from the zap.log file

```
7487162 [ZAP-cfu] ERROR org.zaproxy.addon.callhome.ExtensionCallHome - Unsupported or unrecognized SSL message
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1501) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1411) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:451) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:422) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:303) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.SslConnectionSocketFactory.connectSocket(SslConnectionSocketFactory.java:195) ~[?:?]
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181) ~[?:?]
        at org.apache.hc.client5.http.impl.io.ZapHttpClientConnectionOperator.connect(ZapHttpClientConnectionOperator.java:95) ~[?:?]
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:433) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:159) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:169) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:146) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:158) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:394) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:297) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:103) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:298) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:266) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:222) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:193) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:57) ~[?:?]
        at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:478) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:211) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.getServiceData(ExtensionCallHome.java:230) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.getCheckForUpdatesData(ExtensionCallHome.java:239) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.get(ExtensionCallHome.java:249) ~[?:?]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getRemoteConfiguration(ExtensionAutoUpdate.java:991) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$4.run(ExtensionAutoUpdate.java:1119) ~[zap-2.12.0.jar:2.12.0]
```

### Additional context

The following code is working with the same proxyhostname, port, userame, password.
Using org.apache.httpcomponents.client5:httpclient5:5.2.1 library with the same JDK ZAP is using and on the same PC.

```java
public class ClientProxyAuthentication {

    public static void main(final String[] args) throws Exception {
        final CredentialsProvider credsProvider = CredentialsProviderBuilder.create()
                .add(new AuthScope("ourNTLMproxyhostname", 8080), "farnulfo", "mypassword".toCharArray())
                .build();
        final HttpHost proxy = new HttpHost("ourNTLMproxyhostname", 8080);
        try (final CloseableHttpClient httpclient = HttpClients.custom()
                .setProxy(proxy)
                .setDefaultCredentialsProvider(credsProvider)
                .build()) {

            final RequestConfig config = RequestConfig.custom()
                .build();
            final HttpGet httpget = new HttpGet("https://httpbin.org/headers");
            httpget.setConfig(config);

            System.out.println("Executing request " + httpget.getMethod() + " " + httpget.getUri() +
                    " via " + proxy);

            httpclient.execute(httpget, response -> {
                System.out.println("----------------------------------------");
                System.out.println(httpget + "->" + new StatusLine(response));
                System.out.println( EntityUtils.toString(response.getEntity()));
                EntityUtils.consume(response.getEntity());
                
                return null;
            });
        }
    }
}
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-01-31 17:15
Update the add-ons, this seems to be a duplicate of #7594.

**Comment by farnulfo** [comment] 2023-01-31 18:05
Hi,

Thansk, I've downloaded https://github.com/zaproxy/zap-extensions/releases/download/network-v0.6.0/network-beta-0.6.0.zap and Import it manually in ZAP and now it's OK.

Would this version of the add-ons be included in the next release of ZAP ?

**Comment by kingthorin** [comment] 2023-01-31 18:16
Add-ons are updated separately form ZAP. That's much of the benefit of having things as add-ons.

There are some existing issues with regard to add-on, updates but they're being worked on.

As for the version included in the next release, it'll be whatever the relevant version is at the time.

**Closed** 2023-01-31 18:23 UTC
Labels: bug, add-on
