### ISSUE TITLE
PIIScanner false postive

### ISSUE THREAD

**Issue by sashank** [zaproxy/zaproxy#5124] opened 2018-11-21 06:14 UTC
**Describe the bug**
Current Zap Extensions package (alpha) release has a bug in PIIScanner. The string in our code "8.46786664623715e-47" is being flagged as Mastero card because of wrong regex matching. 

**To Reproduce**
Just run the PIIScanner with the string mentioned above. 

**Expected behavior**

In the below file 

> https://github.com/zaproxy/zap-extensions/blob/alpha/src/org/zaproxy/zap/extension/pscanrulesAlpha/PiiScanner.java

The regular expression for detecting Maestero card mentioned is below

`   MASESTRO("Maestro", "(?:(?:5[0678]\\d\\d|6304|6390|67\\d\\d)\\d{8,15})"),`

This should not get fired for a string like ours ""8.46786664623715e-47"" 

**Screenshots**
None.

**Software versions**
 - ZAP-Extensions : Alpha version

**Comment by kingthorin** [comment] 2019-02-17 01:56
The regex seems to be working as intended. 

As you can see here https://www.regexplanet.com/share/index.html?share=yyyyyq6d1nr (click `java` then `test`), it does indeed return `6786664623715` and in the scanner code the values are even further checked via Luhn algo.

The name of the alert could be made more specific "PII Scanner - Potential Maestro CC Number" (or something like that). Maybe the confidence of the alerts should be reduced to "Medium"?

End users can always edit the alert and mark it `False Positive`, or leverage [Context Alert Filters](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAlertFiltersAlertFilter) for repeat scans, or even disable the particular plugin.

**Comment by kingthorin** [comment] 2019-03-18 09:59
Fixed in https://github.com/zaproxy/zap-extensions/pull/1958

**Closed by kingthorin** 2019-03-18 09:59 UTC
Labels: FalsePositive, add-on

**Comment by globeone** [comment] 2020-01-31 17:02
The point is more that a credit card number is neither a Floating-point number nor a number in Scientific notation. In the earlier example and in this example where a conversion rate is being calculated. Yes it matches VISA and LUN-10 but it's not a credit card number. 

So we need to filter out Floating-Point and Scientific notation numbers which are clearly not Credit Card numbers first before performing the check if it's a valid credit card number.

Pseudo code: 
```
If 
  number is a floating-point number
  # 2.4 is not going to be a credit card number

  or is a number written in Scientific Expression
  # ends in "E-[0-9]" is not going to be a credit card number
 
  exit
else
 Check regular expression and Luhn()

```
example code that was flagged by ZAP as a Visa credit card:
```
"common.shared.conversion_rate.to_eur.mur&q;
:&q;
2.4670000000000001E-2&q;"
```
