### ISSUE TITLE
Failed to generate reports with requests and responses

### ISSUE THREAD

**Issue by MrTheV** [zaproxy/zaproxy#8416] opened 2024-03-22 16:24 UTC
### Describe the bug

Hello

Whatever the report template I use, when I want to generate a report with requests and responses it fails.
My session DB is quite large (54GB).

### Steps to reproduce the behavior

1/ Use Report / Generate report. Select a template with requests and responses
2/ Click Generate
3/ The process fails with "Failed to generate report: Exception evaluating OGNL expression:". The expression that generates the error is not always the same. It can be 

### Expected behavior

Report should be generated without error...

### Software versions

ZAP 2.14.0 (Windows). 
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
Report Generation 0.30.0

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/29263427/ef47cad1-7342-4f57-8a00-f10018316c1c)

### Errors from the zap.log file
```
2024-03-22 16:51:22,382 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template Traditional HTML Report with requests and responses
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "instance.userObject.message.requestHeader.toString.length" (template: "C:\Users\Toto\ZAP\reports\traditional-html-plus\report.html" - line 388, col 9)
at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:199) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:104) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.MessageExpression.executeMessageExpression(MessageExpression.java:256) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:69) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:437) ~[?:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:502) ~[?:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:428) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:411) ~[zap-2.14.0.jar:2.14.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: ognl.OgnlException: source is null for getProperty(null, "requestHeader")
2024-03-22 16:51:22,382 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template Traditional HTML Report with requests and responses
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "instance.userObject.message.requestHeader.toString.length" (template: "C:\Users\Toto\ZAP\reports\traditional-html-plus\report.html" - line 388, col 9)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:199) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:104) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.MessageExpression.executeMessageExpression(MessageExpression.java:256) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:69) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:437) ~[?:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:502) ~[?:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:428) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:411) ~[zap-2.14.0.jar:2.14.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: ognl.OgnlException: source is null for getProperty(null, "requestHeader")
2024-03-22 16:33:24,940 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template Modern HTML Report with themes and options
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "instance.userObject.message.requestBody.length" (template: "C:\Users\Toto\ZAP\reports\modern\report.html" - line 495, col 13)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:199) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:104) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.MessageExpression.executeMessageExpression(MessageExpression.java:256) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:69) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:437) ~[?:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:502) ~[?:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:428) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:411) ~[zap-2.14.0.jar:2.14.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: ognl.OgnlException: source is null for getProperty(null, "requestBody")
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2024-03-22 16:28
Closing as duplicate of #6880 (note this specific issue was already addressed but not yet released).

**Closed by thc202** 2024-03-22 16:28 UTC
Labels: bug, duplicate, add-on, in:reports
