### ISSUE TITLE
Issues with ZAP PHP API client

### ISSUE THREAD

**Issue by fulgore83** [zaproxy/zaproxy#2168] opened 2016-01-12 10:09 UTC
Hello,

when I try use php API to call scan i got error:

GET http://zap/JSON/spider/action/scan/?zapapiformat=JSON&apikey=12345&url=http%3A%2F%2Fexample.com&maxChildren=&recurse=&contextName= HTTP/1.1

HTTP/1.1 400 Bad Request
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Headers: ZAP-Header
X-Clacks-Overhead: GNU Terry Pratchett
Content-Length: 50
Content-Type: application/json; charset=UTF-8

{"code":"does_not_exist","message":"Nie istnieje"}

Can You help me?

Best regards
Grzegorz

**Comment by thc202** [comment] 2016-01-12 10:20
The problem is caused by the empty "contextName" (#2122).

What version of the PHP API are you using?

**Comment by fulgore83** [comment] 2016-01-12 10:32
I use in composer on files from repo which downloaded today:

"zaproxy/php-owasp-zap-v2": "=dev-develop"

This problem is occure when i use connection to new ZAP 2.4.3. On Zap 2.4.1 is fine.

**Comment by fulgore83** [comment] 2016-01-12 10:41
and my additional question:

when i use Yours requires with composer:

"zaproxy/php-owasp-zap-v2": ">=0.1.0",

i got :+1: 
Problem 1
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.1, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.2, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.3, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.4, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.5, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.6, dev-develop].
    - Can only install one of: zaproxy/php-owasp-zap-v2[0.1.7, dev-develop].
    - Installation request for zaproxy/php-owasp-zap-v2 dev-develop -> satisfiable by zaproxy/php-owasp-zap-v2[dev-develop].
    - Installation request for zaproxy/php-owasp-zap-v2 >0.1.0 -> satisfiable by zaproxy/php-owasp-zap-v2[0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7].

How can i use 0.1.7?

**Comment by thc202** [comment] 2016-01-12 11:25
OK, we should update the PHP client to not send empty parameters.

To select 0.1.7 you can use the following:
"zaproxy/php-owasp-zap-v2": "=0.1.7"
Although that might be too old, "2.4.x-dev" is probably better.

**Comment by fulgore83** [comment] 2016-01-12 11:50
i see one more problem:

You try get $this->zap->baseother variable in example core file but in Zapv2 class is only base_other variable.

**Comment by thc202** [comment] 2016-01-13 10:16
Fixed in eeacf0152cca36b085e8f20762cfd826a59f6360.

**Closed by thc202** 2016-01-13 10:16 UTC
Labels: bug, Type-Task
