### ISSUE TITLE
show column 'Size Resp. Body' of history in bytes

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#2994] opened 2016-11-10 12:20 UTC
The 'Size Resp. Body' column currently shows response sizes as 4.08KiB, 13.69KiB, 50 bytes, etc. This makes it hard to notice small changes is response length, so there could be an option to show all sizes as bytes or that could be the default behaviour.

Copying the rows of the table works fine when analyzing larger listings of history.

**Comment by a1ec** [comment] 2016-12-14 12:37
I second Juha's request to show this as a full integer of bytes as default and have the option to choose; a size like 4.08KiB is too coarse when a change of a few bytes out of thousands may indicate an issue. Please assign to a dev :)

**Comment by psiinon** [comment] 2016-12-14 13:42
Re "Please assign to a dev": open source doesn't work that way I'm afraid, contributors pick and choose what they want to work on. Very happy for this to be implemented but I cant assign it to anyone (apart from myself). Best approach is to explain why its so useful (which to be fair @juhakivekas has already done) and hope a contributor agrees with you;)

**Comment by kingthorin** [comment] 2016-12-14 13:57
We happily accept contributions from new people as well, so if you feel like tackling it that's cool as well 👍

**Comment by psiinon** [comment] 2016-12-14 14:14
You can also vote on ZAP issues you want fixed here: https://www.bountysource.com/teams/zap/issues and even put bounties on them if you like ;) We do keen an eye on this so if an easy to issue gets a few votes it will be more likely to get fixed before others.

Re the implementation - an easy way for the user to choose would be to add a new 'Size Resp. Body (bytes)" column to the relevant table then default to showing that instead of the other one - the user will then be able to switch them (or display both) via the existing tables controls - no need for a new option.

**Comment by a1ec** [comment] 2016-12-18 10:42
psiinon, kingthorin thanks for the response, I didn't mean to sound like a twat with the assign remark, rather I saw the empty assignees list on the github page and thought it might be an issue that is to be  worked on.
I think the feature will help bring the tool in line competitively with Burp in the area of HTTP response analysis. By no means a dev by any stretch but I'll look at the code when I get a chance.

**Comment by thc202** [comment] 2016-12-18 21:19
Issues are (usually) only assigned when someone is actively working on them, that's why the assignees list is empty. That does not mean the issue is not useful/wanted/needed or it's not going to be implemented, far from that. If it's still open it means it's something that should be done :)

I've this on my TODO list since the talk in IRC channel, I'll tackle it soon (probably tomorrow).

**Closed** 2016-12-28 11:22 UTC
Labels: Component-UI, enhancement, Usability
