### ISSUE TITLE
BUG: ZAP 2.9 hangs when walking through the Alerts URLs (large JavaScript)

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#5862] opened 2020-02-12 17:57 UTC
**Describe the bug**
When the scan of a very large site is finished and one walks through the Alerts URLS to validate for False Positives. ZAP stops responding completely and doesn't accept any input from the keyboard nor mouse. If one waits about 5 minutes ZAP seems to recover and you can make a single click which then hangs ZAP again for 5 minutes. In ProcMon64 I see that the session receives a .lck extension (guessing this means Lock). 
This also happened when ZAP gave back control and I tried to run a HTML report.

**To Reproduce**
- Run a giant scan of a huge website returning giant JavaScripts (boostrap)
- When finished walk through the Alerts
- When clicking on one of the giant JavaScript URLS ZAP will go into a kind of LOCK mode and no longer respond to user input.
- Click on Report HTML
- ZAP no longer responds to user input.

**Expected behavior**
- It would be nice if there were some kind of Visual feedback that ZAP was in LOCK mode.
-- This way the user doesn't need to panic and try to shut down ZAP loosing all their scan data.
- It would be nice if the keyboard and mouse interrupted the LOCK mode by stopping the current processing and gave control back to the user.  
-- Lock conditions can be very intimidating for users, especially new users who might feel they broke something. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/74362055-44b91680-4dc8-11ea-8080-f1d67a94fc00.png)

**Software versions**
 - ZAP: 2.9
 - Add-on:  Passive Scanning Rules removed for this scan
[2020-02-12_InstalledAddOns_NoPassiveScanning.csv.txt](https://github.com/zaproxy/zaproxy/files/4193958/2020-02-12_InstalledAddOns_NoPassiveScanning.csv.txt)

 - OS: Windows 10 19.09
 - Java:  java -version
openjdk version "13.0.2" 2020-01-15
OpenJDK Runtime Environment (build 13.0.2+9)
OpenJDK 64-Bit Server VM (build 13.0.2+9, mixed mode, sharing)
 - Browser: Firefox 73

**Errors from the zap.log file**
Sanitized
[2020-02-12_BugLocked_zap.log](https://github.com/zaproxy/zaproxy/files/4193986/2020-02-12_BugLocked_zap.log)

**Additional context**

The screenshot shows .lck and .data when the system is locked I only see .lck and nothing else.

**Comment by globeone** [comment] 2020-02-12 17:59
Here is what it looks like when there is no mouse or keyboard input possible in zap.
![image](https://user-images.githubusercontent.com/10052587/74362830-ac239600-4dc9-11ea-8f8b-a5fb36bdedf0.png)

**Comment by thc202** [comment] 2020-02-12 18:01
Closing as duplicate of #5791.

**Closed by thc202** 2020-02-12 18:01 UTC
Labels: bug
