### ISSUE TITLE
GraphQL importer generates an invalid introspection query 

### ISSUE THREAD

**Issue by yaakov123** [zaproxy/zaproxy#6921] opened 2021-11-11 12:46 UTC
**Describe the bug**
When attempting to import a GraphQL using only the endpoint URL, the newest version of ZAProxy fails. The reason for this is a version difference in the graphql-java. In a functional version of ZAP the library version is - com.graphql-java:graphql-java:15.0, but in the non-functional version it's using com.graphql-java:graphql-java:17.0. 

The reason this breaks is because the v17 generates an introspection query that isn't valid as seen here:
https://github.com/graphql-java/graphql-java/blob/v17.0/src/main/java/graphql/introspection/IntrospectionQuery.java

Whereas the v15 generates a valid query as seen here:
https://github.com/graphql-java/graphql-java/blob/v15.0/src/main/java/graphql/introspection/IntrospectionQuery.java

**To Reproduce**
1) Attempt to import a GraphQL schema using only the endpoint URL

**Expected behavior**
The import should work as expected

**Comment by psiinon** [comment] 2021-11-11 12:50
@yaakov123  Thanks - do you know offhand if this is fixed in later GraphQL releases?
We would want to wait for their fix rather than patching our own in their code...

**Comment by yaakov123** [comment] 2021-11-11 13:26
What do you mean by a later GraphQL release? If you're talking about the graphql-java library, v17 is the latest version.

**Comment by kingthorin** [comment] 2021-11-11 13:38
Looks like there is a 17.3 release not sure if it addresses the issue.

**Comment by psiinon** [comment] 2021-11-11 13:52
@yaakov123 Well yes, I thought that would be obvious from the context, but obviously not ;)
Do you know if this issue has been reported on that repo or fixed in one of the later releases that kingthorin pointed out?
If it has not been fixed or reported then I suggest you report it on that repo - we have no desire to maintain our own fork of it.

**Comment by yaakov123** [comment] 2021-11-11 13:58
I have no idea, for now I monkey-patched the latest version of ZAP to include the v0.6.0 of the graphql importer addon

**Comment by yaakov123** [comment] 2021-11-11 14:00
A brief check at the offending file in v17.3 shows that the problematic query is still there.

**Comment by psiinon** [comment] 2021-11-11 14:08
@yaakov123 If you want this fixed in our add-on then I suggest you report it to them. We dont want to depend on an out of date library. We can of course report it, but you are the one most affected and so should be able to give them more context than we can.

**Comment by yaakov123** [comment] 2021-11-11 14:27
Opened an issue:
https://github.com/graphql-java/graphql-java/issues/2608

**Comment by kingthorin** [comment] 2022-04-12 02:22
The upstream issue has been closed with an explanation that was accepted by the user. It seems the issue is caused by features which are not yet part of the spec.

**Closed** 2022-04-20 12:29 UTC
Labels: bug, InsufficientEvidence, add-on
