### ISSUE TITLE
Error parsing small valid OpenAPI spec

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6042] opened 2020-06-17 22:28 UTC
**Describe the bug**
I'm working on generating OpenAPI 3.0 docs for OWASP Benchmark, and testing it with ZAP. I'm just getting started but already ran into a ZAP bug. I'm going to attach the generated openapi files, where are considered valid by: https://apitools.dev/swagger-parser/online/

**To Reproduce**
1. Click on Import --> 'Import OpenAPI definition from local file system'
2. Click on 'Choose File'
3. Select the file and hit Open
4. Click Import and see the Error

**Expected behavior**
I think it should be able to parse these openapi files. And it would be nice, before you fix the actual problem, if you could figure out a way to get some level of error details into the Output tab of ZAP itself. Right now nothing shows up at all in the Output tab.

It might also make sense to add a comment to the 'Failed to parse OpenAPI definition' dialog like: "Make sure your OpenAPI spec is valid. Trying testing it somewhere like: https://apitools.dev/swagger-parser/online/"

**Software versions**
 - ZAP: 2.9.0
 - OS: MacOS 10
 - Java: "1.8.0_232"

**Errors from the zap.log file**
When importing the .json file, I simply get this in the log:
```
2020-06-17 17:47:34,221 [ZAP-Import-OpenAPI-1] WARN  ExtensionOpenApi -
java.lang.NullPointerException
        at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:82)
        at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateBody(RequestModelConverter.java:79)
        at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:42)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:164)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:158)
        at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:235)
```
For the .yaml file I get more:
```
2020-06-17 17:56:39,461 [ZAP-Import-OpenAPI-5] WARN  DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
	at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:156)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:139)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:133)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:195)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:235)
Caused by: while parsing a block mapping
 in 'string', line 15, column 3:
      /crypto-00/BenchmarkTest00020:
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 33, column 5:
        post:
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
	... 12 more
2020-06-17 17:56:39,497 [ZAP-Import-OpenAPI-5] ERROR SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"openapi: 3.0.1
info:
  title: OWASP Benchmark Test Application
  description: 'This is the OWASP Benchmark AppSec Tools Test application for Java.  You
    can find more info at: [https://github.com/OWASP/Benchmark](https://github.com/OWASP/Benchmark)'
  contact:
    email: dave.wichers@owasp.org
  license:
    name: GNU GPL 2.0
    url: https://choosealicense.com/licenses/gpl-2.0/
  version: "1.2"
servers:
- url: https://localhost:8443/benchmark
paths:
  /crypto-00/BenchmarkTest00020:
     get:"[truncated 901 chars]; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:114)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertV1ToV2(SwaggerConverter.java:216)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:197)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:235)
2020-06-17 17:56:45,039 [ZAP-Import-OpenAPI-5] WARN  ExtensionOpenApi - Failed to parse swagger defn null
org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Failed to parse swagger defn null
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:173)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:235)
```

**Additional context**
Here are the openapi files (I had to add .txt extensions to be able to attach them this way):

[openapi.yaml.txt](https://github.com/zaproxy/zaproxy/files/4795346/openapi.yaml.txt)
[openapi.json.txt](https://github.com/zaproxy/zaproxy/files/4795347/openapi.json.txt)

**Comment by thc202** [comment] 2020-06-18 13:17
I'm not able to reproduce the YAML warnings with the YAML file provided.

**Comment by davewichers** [comment] 2020-06-18 14:25
What version of ZAP are you using? I'm going to upgrade to the latest available in dev and see if I can repeat this problem or not. I saw another ticket that you added support for OpenAPI 3 late 2019. Did that enhancement make it into ZAP 2.9.0?

**Comment by kingthorin** [comment] 2020-06-18 14:28
OpenAPI is an addon not core.

**Comment by thc202** [comment] 2020-06-18 14:52
I tested with the same version as you used (latest, based on the stack traces. It does include OpenAPI 3 support).
With the provided YAML I'm just getting the NPE (same one as with JSON). In any case those warnings are logged by the Swagger parser (which we don't have access to from ZAP).

**Comment by davewichers** [comment] 2020-06-18 15:15
But you are able to produce the errors in ZAP itself. I.e., it does NOT work for you, just like it doesn't work for me. Correct?

**Comment by thc202** [comment] 2020-06-18 15:27
Yes, I'm able to reproduce the error (that should be fixed in the PR) just not the YAML warnings.

**Closed** 2020-06-19 15:28 UTC
Labels: add-on, bug
