### ISSUE TITLE
NPEs during zapbot WAVSEP scans

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2176] opened 2016-01-17 12:13 UTC
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

> 9173228 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | IntegerOverflow strength HIGH threshold MEDIUM
> 9207443 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9207444 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9207754 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9207754 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9207842 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9207842 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9208045 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException

snip - lots of the same

> 9213951 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9214150 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9214150 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9224414 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
> 9224415 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
> 9224417 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose synched
> 9224422 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose script done
> 9224422 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
> 9225248 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
> 9225273 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
> 9225273 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 5516379
> 9255185 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9255382 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9255383 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9255586 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9255586 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException

snip - lots of the same

> 9307284 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9307885 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9309865 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9309870 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
> java.lang.NullPointerException
> 9321131 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | IntegerOverflow in 147.903s

**Comment by kingthorin** [comment] 2016-02-03 12:37
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by thc202** [comment] 2016-02-03 15:06
Updated the issue name since the NPEs happen in several scanners and start earlier with Csrftokenscan:
```
6452206 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | Csrftokenscan strength HIGH threshold MEDIUM
6479839 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
6479839 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
6479842 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose synched
6479846 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose script done
6479846 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
6480134 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
6480176 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
6480176 [HSQLDB Timer @5c065f2b] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 2945029
6519516 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
	at org.parosproxy.paros.model.SiteNode.hasAlert(SiteNode.java:321)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:330)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:335)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:335)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:335)
	at org.parosproxy.paros.model.HistoryReference.addAlert(HistoryReference.java:410)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTreeEventHandler(ExtensionAlert.java:249)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTree(ExtensionAlert.java:200)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(ExtensionAlert.java:149)
	at org.zaproxy.zap.extension.ascan.ActiveScanController$1.alertFound(ActiveScanController.java:111)
	at org.parosproxy.paros.core.scanner.Scanner.notifyAlertFound(Scanner.java:357)
	at org.parosproxy.paros.core.scanner.HostProcess.alertFound(HostProcess.java:507)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:351)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:314)
	at org.zaproxy.zap.extension.ascanrulesBeta.Csrftokenscan.scan(Csrftokenscan.java:195)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by psiinon** [comment] 2016-02-03 15:11
Note that this change a01bb50954fbd42ed2f9af0a25dfd3878b0d5acf was made partly to help us diagnose this problem - I couldnt reproduce it locally.

**Comment by kingthorin** [comment] 2016-02-26 11:04
This is still happening and the weekly doesn't seem to be showing the info we were hoping for:
https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/gh-pages/reports/wavsep-1.5-weekly-All-M-M.logs.txt

```
6184972 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
	at org.parosproxy.paros.model.SiteNode.hasAlert(SiteNode.java:326)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:338)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.HistoryReference.addAlert(HistoryReference.java:410)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTreeEventHandler(ExtensionAlert.java:249)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTree(ExtensionAlert.java:200)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(ExtensionAlert.java:149)
	at org.zaproxy.zap.extension.ascan.ActiveScanController$1.alertFound(ActiveScanController.java:111)
	at org.parosproxy.paros.core.scanner.Scanner.notifyAlertFound(Scanner.java:357)
	at org.parosproxy.paros.core.scanner.HostProcess.alertFound(HostProcess.java:486)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:351)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:314)
	at org.zaproxy.zap.extension.ascanrulesBeta.Csrftokenscan.scan(Csrftokenscan.java:198)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
	at java.lang.Thread.run(Thread.java:745)
6184977 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
	at org.parosproxy.paros.model.SiteNode.hasAlert(SiteNode.java:326)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:338)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.SiteNode.addAlert(SiteNode.java:343)
	at org.parosproxy.paros.model.HistoryReference.addAlert(HistoryReference.java:410)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTreeEventHandler(ExtensionAlert.java:249)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.addAlertToTree(ExtensionAlert.java:200)
	at org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(ExtensionAlert.java:149)
	at org.zaproxy.zap.extension.ascan.ActiveScanController$1.alertFound(ActiveScanController.java:111)
	at org.parosproxy.paros.core.scanner.Scanner.notifyAlertFound(Scanner.java:357)
	at org.parosproxy.paros.core.scanner.HostProcess.alertFound(HostProcess.java:486)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:351)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.bingo(AbstractPlugin.java:314)
	at org.zaproxy.zap.extension.ascanrulesBeta.Csrftokenscan.scan(Csrftokenscan.java:198)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
	at java.lang.Thread.run(Thread.java:745)
6185172 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
6185178 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
6185373 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
6185373 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
6185573 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
6185573 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.alert.ExtensionAlert  - 
java.lang.NullPointerException
```

**Comment by thc202** [comment] 2016-02-26 16:11
I was able to reproduce the issue locally. I still need to confirm but it seems to me that the problem happens during the clone of the "alerts" collection (done in `getAlerts()`).

**Comment by kingthorin** [comment] 2016-05-14 10:58
The RBAJ-M-M job doesn't seem to have run for 4mo :(

**Comment by thc202** [comment] 2016-05-16 07:52
Right, it was disabled in zapbot/zap-mgmt-scripts@325de2bde68f708512d12e19b6a3c216baccd5da (because of an add-on installation issue).

**Comment by kingthorin** [comment] 2016-05-16 09:18
Okay

**Comment by thc202** [comment] 2016-08-30 23:25
This is still happening as of `OWASP ZAP D-2016-08-22`:
https://github.com/zapbot/zap-mgmt-scripts/blob/c3dc8c770cd90114aa39a1f9de4022b4e4913949/reports/wavsep-1.5-weekly-RB-M-M.logs.txt#L603-L622

This should be addressed with the changes done in #2840.

**Comment by thc202** [comment] 2016-09-06 10:01
Closing per latest results (`OWASP ZAP D-2016-09-05`):
https://github.com/zapbot/zap-mgmt-scripts/blob/66fc789cf52d78d9325d16a85b30da04fdc07785/reports/wavsep-1.5-weekly-RB-M-M.logs.txt#L600-L601

**Closed by thc202** 2016-09-06 10:01 UTC
Labels: BasedOnZAPBOTResults

**Comment by thc202** [comment] 2016-10-04 16:21
This is also happening (intermittently) with version 2.5.0:
https://github.com/zapbot/zap-mgmt-scripts/blob/c8ff83a5b4b7a2738a9e1a87e93b1b845a85b1ac/reports/wavsep-1.5-2.5.0-All-M-M.logs.txt#L619-L637

**Comment by kingthorin** [comment] 2016-10-04 18:44
Re-open?

**Comment by thc202** [comment] 2016-10-05 08:52
I don't think we need, it's no longer happening with the weekly versions.
