### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.zaproxy.addon.network.internal.server.http.LocalServer.isStarted()" because "this.mainProxyServer" is null

### ISSUE THREAD

**Issue by digininja** [zaproxy/zaproxy#8662] opened 2024-10-03 09:18 UTC
### Describe the bug:

I've just installed 2.15 on Ubuntu using the installer.

When it started it told me the certificate was out of date and I told it to generate a new one. It showed me the new certificate, I clicked OK, and then I got this error:

```
java.lang.NullPointerException: Cannot invoke "org.zaproxy.addon.network.internal.server.http.LocalServer.isStarted()" because "this.mainProxyServer" is null
```

This is the full stack trace.

```
    org.zaproxy.addon.network.ExtensionNetwork.removeStartedLocalServers(ExtensionNetwork.java:1151)
    org.zaproxy.addon.network.LocalServersOptionsPanel$ServersPanel.validateListeningAddresses(LocalServersOptionsPanel.java:255)
    org.zaproxy.addon.network.LocalServersOptionsPanel$ServersPanel.validate(LocalServersOptionsPanel.java:228)
    org.zaproxy.addon.network.LocalServersOptionsPanel.validateParam(LocalServersOptionsPanel.java:103)
    org.parosproxy.paros.view.AbstractParamContainerPanel.validateParam(AbstractParamContainerPanel.java:686)
    org.parosproxy.paros.view.AbstractParamDialog.validateParam(AbstractParamDialog.java:373)
    org.parosproxy.paros.view.AbstractParamDialog$1.actionPerformed(AbstractParamDialog.java:218)
    java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
    java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
    java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
    java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
    java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
    java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
    java.desktop/java.awt.Component.processEvent(Component.java:6386)
    java.desktop/java.awt.Container.processEvent(Container.java:2266)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
    java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The certificate bit is probably nothing to do with it, but mentioned it just in case.

### Steps to reproduce the behavior:

The above caused the bug, I've just tried closing down and restarting and it hasn't happened again.

I think I had 2.9 installed before this, my guess is that a config item in there clashed with the new install, the new install then fixed it after I closed the error, and it is going to work fine from now on.

### Expected behavior:

Upgrade shouldn't fail

### Software versions:

2.15 installed by the Linux installer

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2024-10-03 09:54
Closing as duplicate of #8499.

**Closed by thc202** 2024-10-03 09:54 UTC
Labels: bug

**Comment by digininja** [comment] 2024-10-03 10:00
So it was the certificate after all! Glad it is fixed.
