### ISSUE TITLE
Dockerhub: amd64 images

### ISSUE THREAD

**Issue by ollieSayer** [zaproxy/zaproxy#8447] opened 2024-04-15 07:48 UTC
### Describe the bug

Hi, 

I currently use the 'owasp/zap2docker-weekly' to scan one of my applications. However, the latest release looks to only be built for the 'linux/arm64' platform.  Is this intentional going forward or will amd64 also be published / supported?

### Steps to reproduce the behavior

On a instance with a amd64 chipset try to run the latest 'owasp/zap2docker-weekly' docker image

`docker run -it --network host owasp/zap2docker-weekly /bin/bash`

Which results in 

`$ docker run -it --network host owasp/zap2docker-weekly /bin/bash
...
Status: Downloaded newer image for owasp/zap2docker-weekly:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested`

Trying to pull a specific platform also doesn't look to work - looking in the dockerfile I can see hard coded entries to arm64 so not sure if this is now intentional?

`$ docker pull --platform linux/amd64/v4 owasp/zap2docker-weekly
Using default tag: latest
latest: Pulling from owasp/zap2docker-weekly
Digest: sha256:94198b8ad41fa263bd76961efdf71903bbc8ecbb4426a99d8b4935bcfbe1e0a7
Status: Image is up to date for owasp/zap2docker-weekly:latest
image with reference docker.io/owasp/zap2docker-weekly:latest was found but does not match the specified platform: wanted linux/amd64/v4, actual: linux/arm64

$ docker pull --platform linux/amd64 owasp/zap2docker-weekly
Using default tag: latest
latest: Pulling from owasp/zap2docker-weekly
Digest: sha256:94198b8ad41fa263bd76961efdf71903bbc8ecbb4426a99d8b4935bcfbe1e0a7
Status: Image is up to date for owasp/zap2docker-weekly:latest
image with reference docker.io/owasp/zap2docker-weekly:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
$ docker buildx list
`

### Expected behavior

Running the image starts a container correctly on amd64 environments 

`$ docker run -it --network host owasp/zap2docker-weekly /bin/bash
...
[root@4d1c602f8d85 /]# `

### Software versions

2.14.0?

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2024-04-15 07:59
Duplicate of #8440

**Closed by psiinon** 2024-04-15 07:59 UTC
Labels: bug
