### ISSUE TITLE
When I run Ajax spider I get ' Failed to start 'Firefox', is the browser installed/available' pop up

### ISSUE THREAD

**Issue by sbunde** [zaproxy/zaproxy#2149] opened 2015-12-21 16:29 UTC
1) Right click the site URL, click on attack-> AJAX spider
2) Ajax spider window opens and I click start scan
3) The firefox browser opens and closes automatically without opening the URL
4) ' Failed to start 'Firefox', is the browser installed/available' pop up is shown
5) When I check the proxy setting of that opened browser the no-proxy radio button was selected.

**Comment by athspk** [comment] 2015-12-21 16:43
I got the same today after updating Firefox to latest version.
(which btw disabled the pnh plugin)

**Comment by kingthorin** [comment] 2015-12-21 17:12
Re: pnh, probably because of new signing requirements [1]

[1] https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by kingthorin** [comment] 2015-12-21 17:38
pnh work around (for Firefox 43.x):
https://wiki.mozilla.org/Add-ons/Extension_Signing

* type `about:config` into the URL bar in Firefox
*  in the Search box type `xpinstall.signatures.required`
*  double-click the preference, or right-click and selected "Toggle", to set it to `false`.

**Comment by sbunde** [comment] 2015-12-23 10:22
Sorry for late reply, I tried with the workaround given for FF 43.x, but could not make it. ' Failed to start 'Firefox', is the browser installed/available' pop up is shown

**Comment by psiinon** [comment] 2015-12-23 10:27
Can you try installing the latest ZAP Selenium add-on from the Marketplace - hopefully that will solve this problem. It was released yesterday.

**Comment by thc202** [comment] 2015-12-23 10:27
The issue should be fixed with latest version (4) of "Selenium" add-on. It can be updated from within ZAP using the "Manage Add-ons" dialogue. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsManageaddons

**Comment by thc202** [comment] 2015-12-23 10:28
Oops, sorry for the noise...

**Comment by sbunde** [comment] 2015-12-24 08:50
I have updated the selenium add-on, still same message is shown.

**Comment by kingthorin** [comment] 2015-12-24 11:18
Reopening.

Is Firefox in your $PATH ?
Though the new version of the addons should load dynamically, it can'take hurt to shutdown ZAP and start it again.

**Comment by pierreyves-jegou** [comment] 2015-12-25 21:56
Hello,

Same problem here with ZAP 2.4.3 and Firefox 43.0.2.
The proposed fix relative to selenium add-on and the change of the firefox parameter (xpinstall.signatures.required) didn't make it either.

Firefox is set up in the PATH variable.

Best regards,

**Comment by dyba** [comment] 2015-12-29 23:03
I think the problem is that the browser window that ZAP opens doesn't have the proxy settings configured to proxy traffic through localhost:8080.

**Comment by thc202** [comment] 2015-12-30 10:03
Could you (@pierreyves-jegou and @sbunde) provide the messages that are in zap.log [1] file after `WARN  SpiderThread - Failed to start browser firefox`?

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by sbunde** [comment] 2015-12-30 10:26
PFA log file 
[zap.zip](https://github.com/zaproxy/zaproxy/files/74759/zap.zip)

**Comment by kingthorin** [comment] 2015-12-31 17:46
I'm not sure how this closed based on a commit to a personal repo....something strange here. Reopening.

**Comment by dyba** [comment] 2015-12-31 18:57
Here's the output I get from the zap.log file. I'm running Firefox 43.0.3.

```
2015-12-31 10:52:55,800 [Thread-146] INFO  SpiderThread - Running crawljax targeting http://localhost:3000
2015-12-31 10:52:55,800 [Thread-146] INFO  SpiderThread - Starting proxy...
2015-12-31 10:52:55,800 [Thread-146] INFO  SpiderThread - Proxy started, listening at port [51961].
2015-12-31 10:52:56,097 [Thread-146] WARN  Plugins - No plugins loaded. There will be no output
2015-12-31 10:53:42,917 [Thread-146] WARN  SpiderThread - Failed to start browser firefox
com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows:
tcy16mrf987dtnlz/T/anonymous4317419788794979668webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1451587977000,"updateDate":1451587977000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8235030,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451587978247   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"4QvkCl2GGXHA","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451430373000,"updateDate":1451430373000,"applyBackgroundUpdates":1,"skinnable":true,"size":8170,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451587978247   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451587978247   DeferredSave.extensions.json    DEBUG   Save changes
1451587978247   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1451587978247   addons.xpi-utils        DEBUG   Updating add-on states
1451587978248   addons.xpi-utils        DEBUG   Writing add-ons list
1451587978255   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1451587978256   addons.manager  DEBUG   Provider finished startup: XPIProvider
1451587978256   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1451587978256   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Starting provider: GMPProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1451587978262   addons.manager  DEBUG   Provider finished startup: GMPProvider
1451587978262   addons.manager  DEBUG   Starting provider: PluginProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1451587978263   addons.manager  DEBUG   Provider finished startup: PluginProvider
1451587978263   addons.manager  DEBUG   Completed startup sequence
1451587978917   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1451587978917   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1451587978917   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1451587979016   DeferredSave.extensions.json    DEBUG   Starting write
1451587979101   addons.repository       DEBUG   No addons.json found.
1451587979102   DeferredSave.addons.json        DEBUG   Save changes
1451587979106   DeferredSave.addons.json        DEBUG   Starting timer
1451587979128   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1451587979130   DeferredSave.extensions.json    DEBUG   Write succeeded
1451587979131   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1451587979158   DeferredSave.addons.json        DEBUG   Starting write
1451587979171   DeferredSave.addons.json        DEBUG   Write succeeded

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PNMAC-213DDB', ip: '10.13.9.224', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_79'
Driver info: driver.version: FirefoxDriver
  at com.crawljax.di.ConfigurationModule.configure(ConfigurationModule.java:47)
  while locating com.crawljax.browser.EmbeddedBrowser
    for parameter 0 at com.crawljax.core.CrawlerContext.<init>(CrawlerContext.java:32)
  while locating com.crawljax.core.CrawlerContext
    for parameter 0 at com.crawljax.core.Crawler.<init>(Crawler.java:73)
  while locating com.crawljax.core.Crawler
    for parameter 2 at com.crawljax.core.CrawlTaskConsumer.<init>(CrawlTaskConsumer.java:30)
  while locating com.crawljax.core.CrawlTaskConsumer

1 error
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.crawljax.core.CrawlController.call(CrawlController.java:65)
        at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)
        at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:193)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows:
tcy16mrf987dtnlz/T/anonymous4317419788794979668webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1451587977000,"updateDate":1451587977000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8235030,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451587978247   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"4QvkCl2GGXHA","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451430373000,"updateDate":1451430373000,"applyBackgroundUpdates":1,"skinnable":true,"size":8170,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451587978247   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451587978247   DeferredSave.extensions.json    DEBUG   Save changes
1451587978247   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1451587978247   addons.xpi-utils        DEBUG   Updating add-on states
1451587978248   addons.xpi-utils        DEBUG   Writing add-ons list
1451587978255   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1451587978256   addons.manager  DEBUG   Provider finished startup: XPIProvider
1451587978256   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1451587978256   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Starting provider: GMPProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1451587978262   addons.manager  DEBUG   Provider finished startup: GMPProvider
1451587978262   addons.manager  DEBUG   Starting provider: PluginProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1451587978263   addons.manager  DEBUG   Provider finished startup: PluginProvider
1451587978263   addons.manager  DEBUG   Completed startup sequence
1451587978917   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1451587978917   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1451587978917   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1451587979016   DeferredSave.extensions.json    DEBUG   Starting write
1451587979101   addons.repository       DEBUG   No addons.json found.
1451587979102   DeferredSave.addons.json        DEBUG   Save changes
1451587979106   DeferredSave.addons.json        DEBUG   Starting timer
1451587979128   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1451587979130   DeferredSave.extensions.json    DEBUG   Write succeeded
1451587979131   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1451587979158   DeferredSave.addons.json        DEBUG   Starting write
1451587979171   DeferredSave.addons.json        DEBUG   Write succeeded

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PNMAC-213DDB', ip: '10.13.9.224', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_79'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:223)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:134)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:241)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:224)
        at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:355)
        at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:326)
        at com.google.inject.util.Providers$3.get(Providers.java:109)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        ... 4 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
tcy16mrf987dtnlz/T/anonymous4317419788794979668webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1451587977000,"updateDate":1451587977000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8235030,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1451587978247   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"4QvkCl2GGXHA","location":"app-global","version":"43.0.3","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1451430373000,"updateDate":1451430373000,"applyBackgroundUpdates":1,"skinnable":true,"size":8170,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.3","maxVersion":"43.0.3"}],"targetPlatforms":[]}
1451587978247   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1451587978247   DeferredSave.extensions.json    DEBUG   Save changes
1451587978247   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1451587978247   addons.xpi-utils        DEBUG   Updating add-on states
1451587978248   addons.xpi-utils        DEBUG   Writing add-ons list
1451587978255   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1451587978256   addons.manager  DEBUG   Provider finished startup: XPIProvider
1451587978256   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1451587978256   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1451587978256   addons.manager  DEBUG   Starting provider: GMPProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1451587978262   addons.manager  DEBUG   Provider finished startup: GMPProvider
1451587978262   addons.manager  DEBUG   Starting provider: PluginProvider
1451587978262   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1451587978263   addons.manager  DEBUG   Provider finished startup: PluginProvider
1451587978263   addons.manager  DEBUG   Completed startup sequence
1451587978917   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1451587978917   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1451587978917   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1451587979016   DeferredSave.extensions.json    DEBUG   Starting write
1451587979101   addons.repository       DEBUG   No addons.json found.
1451587979102   DeferredSave.addons.json        DEBUG   Save changes
1451587979106   DeferredSave.addons.json        DEBUG   Starting timer
1451587979128   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1451587979128   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1451587979130   DeferredSave.extensions.json    DEBUG   Write succeeded
1451587979131   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
1451587979158   DeferredSave.addons.json        DEBUG   Starting write
1451587979171   DeferredSave.addons.json        DEBUG   Write succeeded

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
        ... 30 more
2015-12-31 10:53:54,955 [Thread-146] INFO  SpiderThread - Stopping proxy...
2015-12-31 10:53:55,056 [Thread-146] INFO  SpiderThread - Proxy stopped.
2015-12-31 10:53:55,088 [Thread-146] INFO  SpiderThread - Finished crawljax targeting http://localhost:3000
```

**Comment by Harinus** [comment] 2016-01-18 15:27
While working on #2173 i found out that the Selenium (2.48.2) basically works with Firefox 43+ when using in a simple project.
I was also able to reproduce @dyba s Error log. As far as i can see The AJAX Spider uses crawljax in Version 3.6 which imports Selenium below 2.46.0 (See: https://github.com/crawljax/crawljax/commits/master/pom.xml) Updating that dependency might fix the issue.

**Comment by Harinus** [comment] 2016-01-19 09:23
Using the weekly build: "D-2015-12-21" with updated Selenium Plugin (V4) and Spider (V15) i get the following exception:
```
java.lang.LinkageError: loader constraint violation: loader (instance of org/zaproxy/zap/control/AddOnClassLoader) previously initiated loading for a different type with name "org/openqa/selenium/WebDriver"
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:355)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:326)
	at com.google.inject.util.Providers$3.get(Providers.java:109)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	at com.crawljax.core.CrawlController.call(CrawlController.java:65)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:193)
	at java.lang.Thread.run(Unknown Source)
```
Cross checking with ZAP 2.4.2 & Selenium (v4) / Spider (V15) -> Working!

The commit https://github.com/zaproxy/zaproxy/commit/a7a2837389a95798e8e1a4f272fbf03401e924c5 which changed the AddOnClassLoader was made before the 2.4.3 release. Together with the required Selenium update something goes wrong.

@thc202 Please review :)

**Comment by thc202** [comment] 2016-01-19 10:53
https://github.com/zaproxy/zaproxy/issues/2149#issuecomment-172560928
Could you explain what "simple project" means in this case?
Are you also using a Mac?

The AJAX Spider add-on (thus Crawljax) depends on Selenium add-on, that means that AJAX Spider add-on will use the Selenium version bundled in Selenium add-on (currently, version 2.48.2).

I was also working on #2173, but I changed Selenium add-on instead of AJAX Spider add-on.

https://github.com/zaproxy/zaproxy/issues/2149#issuecomment-172787851
Would you mind raising an issue?
Could you provide more details on how to reproduce the issue? For example, are you building the add-ons from source? If so, with which changes?
I'm not sure the problem is in that commit, AFAICT the behaviour of the class loader is the same unless the add-on is restricting which classes can (or not) be loaded.

**Comment by Harinus** [comment] 2016-01-19 12:22
OK, so lets go into detail:
1) Reproduce the error
The logs that were posted can be reproduced by using Version "D-2015-12-21" (and possibly others) with the packaged selenium-3 and ajaxspider-14. The log file is except for some system details the same.
2) Verify solution
Verifiying with the mentionend "simple project": 2.48.2 is functional
```
import static org.junit.Assert.assertEquals;

import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxBinary;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class caseIDE {
	private WebDriver driver;
	private String baseUrl;

	@Before
	public void setUp() throws Exception {

		Proxy p = new Proxy();
		p.setHttpProxy("localhost:8080");
		p.setSslProxy("localhost:8080");
		p.setFtpProxy("localhost:8080");

		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(CapabilityType.PROXY, p);

		FirefoxProfile fp = new FirefoxProfile();
		
		fp.setPreference("browser.startup.homepage", "about:blank");
		fp.setPreference("startup.homepage_welcome_url", "about:blank");
		fp.setPreference("startup.homepage_welcome_url.additional", "about:blank");
		fp.setPreference("network.proxy.type", 1);
		fp.setPreference("network.proxy.http", "localhost");
		fp.setPreference("network.proxy.http_port", 8080);

		driver = new FirefoxDriver(new FirefoxBinary(), fp, cap);


		baseUrl = "http://10.202.0.147/login.php";
		driver.manage().timeouts().implicitlyWait(3000, TimeUnit.SECONDS);

	}

	@Test
	public void testIpw() throws Exception {
		driver.get(baseUrl + "/");
		Thread.sleep(50000);
		assertEquals("1", "1");
	}

	@After
	public void tearDown() throws Exception {
		driver.quit();
	}
}
```
3) 2.48.2 Dependency:
Crawljax itself has a dependency on 2.44.0. If the class loader uses the Selenium add-on bundeled 2.48.2 as you said thats fine. Not sure how it works internally.

4) Work on #2173:
Keep going.. i am implementing a quick workaround as i need FFox Dev Edition ASAP.. myself i wont commit anything on that case.

4) org/zaproxy/zap/control/AddOnClassLoader Linkage Error
Solved this one.. Had copied another jar (seleneserunner) to the lib folder which is required somewhere else. Seleneserunner also bundles Selenium.... My Bad

5) Conclusion: There should be no issues with the updated Selenium Addon. If the error persists i suggest verifying if there is the correct selenium*.zap in the plugin folder. If yes, does the code from 2) work? Maybe its related to Java 7 ... using 8 here.

**Comment by thc202** [comment] 2016-12-16 23:28
Closing, Selenium add-on now explicitly mentions the supported versions of Firefox. [1] If you have an issue with one of the supported versions, please, let us know through the [User Group](https://groups.google.com/group/zaproxy-users) (or, another issue). Also, note #2743.

@Harinus, raised #3076 to allow to test the browser directly from the options (similar to what is done in step 2). Thanks for the suggestion!

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsSeleniumIntro

**Closed by thc202** 2016-12-16 23:28 UTC
Labels: add-on, bug
