### ISSUE TITLE
Failed to start ZAP 2.4.1

### ISSUE THREAD

**Issue by renehoek** [zaproxy/zaproxy#1856] opened 2015-08-27 14:35 UTC
ZAP 2.4.1 does not start on OSX Yosemite (version 10.10.5)

The first time ZAP launches the dock items 'jumps' for some time and then exists. Attempting to start again result in a failure to start. The console logs the following:

```
8/27/15 4:29:58.407 PM com.apple.xpc.launchd[1]: (org.zaproxy.zap.ZAP.136352[550]) Service exited with abnormal code: 1
```
ZAP 2.4.0 worked perfectly on my machine, I updated to 2.4.1 today.

---------

When I start through the terminal (execute the 'zap.sh' script in '/Applications/OWASP ZAP.app/Contents/Java', I get the following:

```
Exiting: ZAP requires a minimum of Java 7 to run, found 1.6.0_65
```
So it is using the system-default Java interpreter (which is 1.6.x). But If understand the download information correctly, Java 1.7.x should be included?  [Java 1.7 included](https://github.com/zaproxy/zaproxy/wiki/Downloads?tm=2#zap-241-standard)

**Comment by psiinon** [comment] 2015-08-27 15:00
Thats weird, Java 7 should be included in the release :/
Consulting with our Mac guru now...

**Comment by marumari** [comment] 2015-08-27 15:11
There were a lot of bugs discovered around the OS X launching system post-2.4.1, as it was completely gutted and replaced in that version.  Can you try this:

Download the current zap.sh file:
https://raw.githubusercontent.com/zaproxy/zaproxy/develop/src/zap.sh

chmod 755 ~/Downloads/zap.sh
mv ~/Downloads/zap.sh /Applications/OWASP\ ZAP.app/Contents/Java/
(tweaking directories as needed)

And then try to start it up with that version of zap.sh?  If it fails, could you paste the entire output into this issue?

Thanks!

**Comment by renehoek** [comment] 2015-08-27 15:14
Workarround:
I edited the script 'zap.sh' in   '/Applications/OWASP ZAP.app/Contents/Java'.

I disabled line 20 till 25. On these lines a check is done on the system default java interpreter. See code:

```bash
if [ $JAVA_MAJOR_VERSION -ge 1 ] && [ $JAVA_MINOR_VERSION -ge 7 ]; then
	echo "Found Java version $JAVA_VERSION"
else
	echo "Exiting: ZAP requires a minimum of Java 7 to run, found $JAVA_VERSION"
	exit 1
fi
```

Later in the script 'zap.sh' (line 85 till 90) the OS platform is checked. If this is 'Darwin', then the Java 7 provided in the ZAP package is used. 

```bash
#Start ZAP

if [ "$OS" = "Darwin" ]; then
  exec ../PlugIns/jre*/Contents/Home/bin/java ${JMEM} -XX:PermSize=256M -Xdock:icon="../Resources/ZAP.icns" -jar "${BASEDIR}/zap-2.4.1.jar" "$@"
else
  exec java ${JMEM} -XX:PermSize=256M -jar "${BASEDIR}/zap-2.4.1.jar" "$@"
fi
```

I think that the check in line 20 till 25 is not needed if running Darwin, because later in the script a check is made on the OS platform. If the OS platform is Darwin, the provided Java 7 is always used.

So, something like this on line 20 till 25:

```bash
if [ $JAVA_MAJOR_VERSION -ge 1 ] && [ $JAVA_MINOR_VERSION -ge 7 ]; then
	echo "Found Java version $JAVA_VERSION"
else
        if [ "$OS" != "Darwin" ]; then
	     echo "Exiting: ZAP requires a minimum of Java 7 to run, found $JAVA_VERSION"
	     exit 1
        fi
fi
```

**Comment by marumari** [comment] 2015-08-27 15:18
Yep, all that stuff (should) actually be fixed in 2.4.2, which uses the zap.sh file I linked you to.  If you could still test with it, that would be great!  I really appreciate your troubleshooting on this!

**Comment by renehoek** [comment] 2015-08-27 15:41
Thank you for this startup file:
https://raw.githubusercontent.com/zaproxy/zaproxy/develop/src/zap.sh

The first run gave this:

```bash
zyra:Java renevanhoek$ ./zap.sh
Found Java version 1.7.0_79
./zap.sh: line 63: [: ~/Library/Application: binary operator expected
Available memory:  8192 MB
Setting jvm heap size: -Xmx512m
Error: Unable to access jarfile /Applications/OWASP ZAP.app/Contents/Java/zap-dev.jar
```
I changed the code on line 63 from this:

```bash
# Work out best memory options
if [ -f $JVMPROPS ]; then
  # Local jvm properties file present
  JMEM=$(head -1 $JVMPROPS)
elif [ "$OS" = "Linux" ]; then
  MEM=$(expr $(sed -n 's/MemTotal:[ ]\{1,\}\([0-9]\{1,\}\) kB/\1/p' /proc/meminfo) / 1024)
elif [ "$OS" = "Darwin" ]; then
  MEM=$(system_profiler SPMemoryDataType | sed -n -e 's/.*Size: \([0-9]\{1,\}\) GB/\1/p' | awk '{s+=$0} END {print s*1024}')
elif [ "$OS" = "SunOS" ]; then
  MEM=$(/usr/sbin/prtconf | awk '/Memory/{print $3}')
elif [ "$OS" = "FreeBSD" ]; then
  MEM=$(($(sysctl -n hw.physmem)/1024/1024))
fi
```
into this (note the double [[ and ]] on the first 'if' statement):

```bash
# Work out best memory options
if [[ -f $JVMPROPS ]]; then
  # Local jvm properties file present
  JMEM=$(head -1 $JVMPROPS)
elif [ "$OS" = "Linux" ]; then
  MEM=$(expr $(sed -n 's/MemTotal:[ ]\{1,\}\([0-9]\{1,\}\) kB/\1/p' /proc/meminfo) / 1024)
elif [ "$OS" = "Darwin" ]; then
  MEM=$(system_profiler SPMemoryDataType | sed -n -e 's/.*Size: \([0-9]\{1,\}\) GB/\1/p' | awk '{s+=$0} END {print s*1024}')
elif [ "$OS" = "SunOS" ]; then
  MEM=$(/usr/sbin/prtconf | awk '/Memory/{print $3}')
elif [ "$OS" = "FreeBSD" ]; then
  MEM=$(($(sysctl -n hw.physmem)/1024/1024))
fi
```
which resulted in the output:

```bash
zyra:Java renevanhoek$ ./zap.sh
Found Java version 1.7.0_79
Available memory:  8192 MB
Setting jvm heap size: -Xmx512m
Error: Unable to access jarfile /Applications/OWASP ZAP.app/Contents/Java/zap-dev.jar
```

So the syntax error on line 63 is gone.

The last error about not finding 'zap-dev.jar' is to be expected. I am using a 'stable' release. So I changed the last part of the script:

```bash
# Start ZAP; it's likely that -Xdock:icon would be ignored on other platforms, but this is known to work
if [ "$OS" = "Darwin" ]; then
  # Strip the automatic -psn_x_xxxxxxx argument that OS X automatically passes into apps, since
  # it freaks out ZAP
  ZAP_ARGS=()
  for value in "$@"; do
    [[ $value != -psn_* ]] && ZAP_ARGS+=( "$value" )
  done

  # It's likely that -Xdock:icon would be ignored on other platforms, but this is known to work
  exec java ${JMEM} -Xdock:icon="../Resources/ZAP.icns" -jar "${BASEDIR}/zap-dev.jar" "${ZAP_ARGS[@]}"
else
  exec java ${JMEM} -jar "${BASEDIR}/zap-dev.jar" "$@"
fi
```

To use 'zap-2.4.1.jar' instead of 'zap-dev.jar'.

which result in a running 'Zap 2.4.1'. Thank you :)

**Comment by thc202** [comment] 2015-09-24 10:47
Closing as duplicate of #1772.
The issue with spaces in the path is being handled in #1877.

**Closed by thc202** 2015-09-24 10:47 UTC
Labels: bug, duplicate, OpSys-OSX
