### ISSUE TITLE
Active Scan -> Input Vectors, configurable in Automation Framework

### ISSUE THREAD

**Issue by tomaszn** [zaproxy/zaproxy#8039] opened 2023-08-30 21:55 UTC
### Is your feature request related to a problem? Please describe.

"I'm frustrated when" I can't reproduce my GUI scan results with Automation Framework.

### Describe the solution you'd like

It seems impossible to enable additional "Injectable Targets", which in GUI are available in "Active Scan" window, "Input Vectors" tab. Specifically, I want to enable "Add URL Query Parameter ?" and "URL Path".

### Describe alternatives you've considered

As an alternative, I tried `zap-full-scan.py`, but it doesn't run with additional input vectors enabled.

### Screenshots

![Active-Scan](https://github.com/zaproxy/zaproxy/assets/981572/7c64e7ea-f4ec-41e1-84a4-358c9d88a906)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-08-30 22:27
Closing as duplicate of #7012. (You can use -config args to enable.)

**Closed by thc202** 2023-08-30 22:27 UTC
Labels: enhancement

**Comment by psiinon** [comment] 2023-08-31 07:33
@tomaszn give #7012 a 👍 to let us know it's important to you.
And comment on it if you would like to help fix it - we can guide you in that...
