### ISSUE TITLE
The Request and Response tab bug intermittently during ActiveScan.

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#7264] opened 2022-05-03 15:02 UTC
### Describe the bug

Hi team :D

Intermittently with ActiveScan running, the Req/Res tab forces the contents of ActiveScan to be rendered. This means that when you click an item in History, Alert, etc., you will not be able to verify the correct content.

![](https://user-images.githubusercontent.com/13212227/166475688-6f2a9e5f-d9cf-4494-94e5-aec6b4bf6241.gif)

> I'm trying to see mozillia's req/res in history, but the www.hahwul.com page is forced to view because activescan is currently running on www.hahwul.com.

However, it does not occur unconditionally, but it seems to be an issue that occurs intermittently or under conditions. 

Oh, and it's not a sudden issue. It's an issue that I knew, but it's not that uncomfortable, so I didn't report it separately. However, the frequency has increased a little recently 😭

### Steps to reproduce the behavior

1. Open ZAP
2. Run active scan (site A / Default Policy)
3. Open Active Scan tab and click record
> ![](https://user-images.githubusercontent.com/13212227/166478382-3c33df95-8678-433b-8439-94201194858d.png)
5. Open History tab and click history record (site B)
> But, the req/res being shows a page that you clicked on the ActiveScan Tab.
6. Open Alerts tab and click alerts record and details (site C)
> But, the req/res being shows a page that you clicked on the ActiveScan Tab.

### Expected behavior

During ActiveScan, you should be able to see the record you selected on the History tab, etc.

### Software versions

- ZAP 2.11.1
- macOS Monterey 12.3.1

```
OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=ZAPRemix, version=2.2.1],
[id=accessControl, version=7.0.0], [id=alertFilters,
version=13.0.0], [id=allinonenotes, version=2.0.0], [id=amf,
version=3.0.0], [id=ascanrules, version=46.0.0],
[id=ascanrulesAlpha, version=38.0.0], [id=ascanrulesBeta,
version=40.0.0], [id=attacksurfacedetector, version=1.1.4],
[id=authstats, version=2.0.0], [id=automation,
version=0.15.0], [id=beanshell, version=7.0.0],
[id=browserView, version=5.0.0], [id=bruteforce,
version=11.0.0], [id=bugtracker, version=3.0.0],
[id=callgraph, version=5.0.0], [id=callhome, version=0.3.0],
[id=codedx, version=9.0.0], [id=commonlib, version=1.9.0],
[id=communityScripts, version=14.0.0], [id=custompayloads,
version=0.11.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=12.0.0], [id=encoder, version=0.6.0],
[id=evalvillain, version=0.1.1], [id=exim, version=0.1.0],
[id=fileupload, version=1.1.0], [id=formhandler,
version=4.0.0], [id=fuzz, version=13.6.0], [id=fuzzdb,
version=8.0.0], [id=gettingStarted, version=13.0.0],
[id=graaljs, version=0.2.0], [id=graphql, version=0.9.0],
[id=groovy, version=3.1.0], [id=help, version=14.0.0],
[id=highlighter, version=8.0.0], [id=hud, version=0.13.0],
[id=imagelocationscanner, version=3.0.0], [id=importurls,
version=9.0.0], [id=invoke, version=11.0.0], [id=jruby,
version=8.0.0], [id=jsonview, version=2.0.0], [id=jwt,
version=1.0.2], [id=jython, version=12.0.0], [id=kotlin,
version=1.1.0], [id=neonmarker, version=1.4.0], [id=network,
version=0.2.0], [id=oast, version=0.10.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=27.0.0], [id=plugnhack,
version=12.0.0], [id=portscan, version=9.0.0],
[id=pscanrules, version=40.0.0], [id=pscanrulesAlpha,
version=35.0.0], [id=pscanrulesBeta, version=29.0.0],
[id=quickstart, version=33.0.0], [id=reflect,
version=0.0.11], [id=regextester, version=2.0.0],
[id=replacer, version=9.0.0], [id=reports, version=0.13.0],
[id=requester, version=5.0.0], [id=retest, version=0.2.0],
[id=retire, version=0.10.0], [id=reveal, version=4.0.0],
[id=revisit, version=4.0.0], [id=saml, version=9.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=30.0.0], [id=selenium,
version=15.8.0], [id=sequence, version=6.0.0], [id=soap,
version=13.0.0], [id=spiderAjax, version=23.7.0],
[id=sqliplugin, version=15.0.0], [id=sse, version=10.0.0],
[id=svndigger, version=4.0.0], [id=tips, version=9.0.0],
[id=tokengen, version=15.0.0], [id=treetools,
version=8.0.0], [id=viewstate, version=3.0.0],
[id=wappalyzer, version=21.9.0], [id=webdrivermacos,
version=39.0.0], [id=websocket, version=25.0.0], [id=zest,
version=35.0.0]]
---
Operating System: Mac OS X
Java Version: Eclipse Foundation 11.0.12
System's Locale: ko_KR
Display Locale: en_GB
Format Locale: ko_KR
ZAP Home Directory: /Users/ichei/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)
```

### Screenshots

Original video: [aaa.mov.zip](https://github.com/zaproxy/zaproxy/files/8611396/aaa.mov.zip)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-05-03 15:07
Closing as duplicate of #6404.

**Closed by thc202** 2022-05-03 15:07 UTC
Labels: bug
