### ISSUE TITLE
Strange Site Tree behavior with root node params

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4642] opened 2018-05-04 14:05 UTC
Consider the following screenshot:

![image](https://user-images.githubusercontent.com/7570458/39632125-31aacda4-4f82-11e8-8f77-06248fc5e93f.png)

When message 1 was originally access it appeared in the site tree. Until /test/index.html was accessed then it disappeared. Shouldn't both:
/?foo=bar and /test/index.html appear in the site tree?

Note: This only seems to happen at the root node, if a additional path layer is introduced the behavior is as expected.
![image](https://user-images.githubusercontent.com/7570458/39632281-9ebf6152-4f82-11e8-884d-ca328ce5534e.png)

**Comment by thc202** [comment] 2023-02-10 18:32
I can't reproduce with latest version (probably fixed by #6350, though there might be other changes).

**Closed by thc202** 2023-02-10 18:32 UTC
Labels: bug, Component-UI, Usability
