### ISSUE TITLE
AMD64 docker images not longer available in Docker Hub

### ISSUE THREAD

**Issue by jlouros** [zaproxy/zaproxy#8443] opened 2024-04-12 08:18 UTC
### Describe the bug

All previously existing images available at https://hub.docker.com/r/owasp/zap2docker-stable were replaced with tags `latest`, `2.14.0` and `2.13.0` but just with support for **linux/arm64** architecture. 

### Steps to reproduce the behavior

1. using a non ARM64 machine, run `docker pull owasp/zap2docker-stable:latest`
2. see error **WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested**

### Expected behavior

Should be able to use zap2docker-stable on a non ARM machine

### Software versions

2.14.0 and 2.13.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2024-04-12 08:27
Duplicate of #8440.

**Closed by thc202** 2024-04-12 08:27 UTC
Labels: bug
