### ISSUE TITLE
Directory Navigation Issue

### ISSUE THREAD

**Issue by twright-0x1** [zaproxy/zaproxy#2594] opened 2016-06-16 15:57 UTC
In ZAP 2.5.0, if open a directory browser (e.g., to open a new session, to find a place to store a report), upon clicking the "Up One Level" button in the browser dialog, the file list displayed is not updated.  Upon clicking the "Up One Level" button a second time causes the file list to be updated.

**Comment by thc202** [comment] 2016-06-16 16:03
Which JRE and OS are you using?

This might be an issue in the JRE.

**Comment by twright-0x1** [comment] 2016-06-17 18:43
I'm using OpenJDK 1.8.0_91 under Kali (Rolling):

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-2-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by thc202** [comment] 2016-06-17 21:18
OK, I was able to reproduce that issue, it seems caused by `assistive_technologies`, a workaround is mentioned in #2432.

Please, let me know if the workaround also works for you.

**Comment by twright-0x1** [comment] 2016-06-19 00:59
Perfect:  that fixed the issue!

**Comment by kingthorin** [comment] 2016-06-19 10:18
Thanks for letting us know.

**Comment by thc202** [comment] 2016-06-20 11:53
An issue has been raised in Kali's bug tracker:
https://bugs.kali.org/view.php?id=3367

(Reopening, until it's fixed in Kali.)

**Comment by thc202** [comment] 2016-07-04 10:51
Fixed in build 1.8.0_91-8u91-b14-3-b14, already available in Kali.
It was an issue in the JRE, triggered by `assistive_technologies`. [1]

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827795

**Closed by thc202** 2016-07-04 10:51 UTC
Labels: kali
