### ISSUE TITLE
ZAP 2.8.1. Linux WebDrivers v 13.0.0 update causes 'Explore your application / Launch Browser / Firefox' to fail

### ISSUE THREAD

**Issue by jasonculligan** [zaproxy/zaproxy#5700] opened 2019-11-23 16:42 UTC
**Describe the bug**
ZAP 2.8.1. Linux WebDrivers update causes 'Explore your application / Launch Browser / Firefox' to fail

**To Reproduce**

1. Download latest Linux ZAP 2.8.1 and extract and run ./zap.sh.
2. Confirm that the Launch Browser button (with a browser selected) works and that it starts the browser under ZAP's control.
3. Confirm that the bundled version of the Linux WebDrivers package is version 10.0.0.
4. Now either allow ZAP to detect new updates or perform a manual updates check, and install any new updates.
5. Confirm that Linux WebDrivers has now been upgraded from version 10.0.0 to version 13.0.0
6. Try the Launch Browser button again.  It will not start the browser.
7. Observe a time out and connection failure to a local control socket in the ZAP logs.

**Expected behavior**
Launch Browser button should start the browser.

**Software versions**
 - ZAP: 2.8.1
 - Add-on: Linux WebDrivers 13.0.0
 - OS: Lubuntu Disco 19.04
 - Java: OpenJDK 11.0.4
 - Browser: N/A

**Errors from the zap.log file**
Connection to localhost failed.  Connection refused.

**Temporary workaround**
Do not perform a package update.  Keep using Linux WebDrivers version 10.0.0.  If you did upgrade and are experiencing the issue, delete your ZAP_2_8_1 application directory and ~/.ZAP directory, and untar a fresh setup and start again.

**Comment by thc202** [comment] 2019-11-23 18:07
That's most likely caused by an unsupported/older Firefox version: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html

**Comment by jasonculligan** [comment] 2019-11-23 23:22
It's happening with Firefox 70.0.1

**Comment by thc202** [comment] 2019-11-23 23:45
Are you sure it's using that version? Could you provide the output when that happens?

That version works fine here with v13 (also, the HUD integrations tests are also using the same geckodriver and Firefox versions).

**Comment by jasonculligan** [comment] 2019-11-24 22:01
Confirmed Firefox 70.0.1.  After further investigation, I've observed that prior to upgrading Linux WebDriver to v13, a process called _geckodriver_ opens on a random high-order port, and ZAP makes the connection to it, then the browser starts.  However after upgrading Linux WebDriver to 13, geckodriver does not start and does not start a random listening TCP port.  Then ZAP times out trying to connect to the non-existent port and the logs show a connection timeout.  ZAP log below showing timeout:

```
50322 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch  - org.apache.http.conn.HttpHostConnectException: Connect to localhost:12820 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'lubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.0.0-36-generic', java.version: '11.0.4'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12820 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'lubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.0.0-36-generic', java.version: '11.0.4'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:777)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:700)
        at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:639)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:509)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:602)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:566)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:552)
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:542)
        at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2.run(ExtensionQuickStartLaunch.java:227)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:12820 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:138)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:86)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        ... 15 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:591)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 30 more
```

**Comment by thc202** [comment] 2019-11-25 09:19
Did you check the version in the browser launched by ZAP? This will require enabling geckodriver trace log to see why it's failing to start/connect.

**Comment by kingthorin** [comment] 2019-12-12 01:36
@jasonculligan any update on the previous question?

**Comment by kingthorin** [comment] 2020-01-26 02:22
No further input from submitter, closing.

**Closed by kingthorin** 2020-01-26 02:22 UTC
Labels: InsufficientEvidence, add-on, bug
