### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by rabol** [zaproxy/zaproxy#6000] opened 2020-05-21 08:50 UTC
**Describe the bug**

I have scanned a web app and and it found this: X-Content-Type-Options Header Missing

and the reference 
say that more information can be found here:  

https://www.owasp.org/index.php/List_of_useful_HTTP_headers

but that link does not work

**Comment by thc202** [comment] 2020-05-21 08:54
Closing as duplicate of #5962. The fix was not yet released though.

**Closed by thc202** 2020-05-21 08:54 UTC
Labels: add-on, bug
