### ISSUE TITLE
tech detection (wappalyzer): Raise info alerts for found tech

### ISSUE THREAD

**Issue by double16** [zaproxy/zaproxy#8140] opened 2023-10-25 10:06 UTC
### Is your feature request related to a problem? Please describe.

Tech Detection (wappalyzer) does not persist findings. It also doesn't provide a way to re-assess based on history.

### Describe the solution you'd like

Tech Detection (wappalyzer) should raise an info alert for each tech found.

### Describe alternatives you've considered

Only to save off a screen shot or re-type the results into another tool.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2023-10-25 10:08
Thanks - I'll aim to look at this asap, unless anyone else wants to look at it right now...

**Comment by kingthorin** [comment] 2023-10-25 10:09
For my two cents this should be optional and off by default.

**Comment by psiinon** [comment] 2023-10-25 10:10
> For my two cents this should be optional and off by default.

Agreed

**Comment by kingthorin** [comment] 2024-07-23 15:22
Closing as duplicate of https://github.com/zaproxy/zaproxy/issues/8361

**Closed by kingthorin** 2024-07-23 15:22 UTC
Labels: enhancement, add-on, in:wappalyzer
