### ISSUE TITLE
Extra alerts remaining after deletion (not appearing in report)

### ISSUE THREAD

**Issue by simchev** [zaproxy/zaproxy#5663] opened 2019-10-31 19:36 UTC
I need to get a report restricted to the context. I've seen previous issues opened here about this but it looks like it's not possible with ZAP. To go around this, I'm deleting every sites that doesn't match the included regexes of the context. It seemed to be working fine until one specific test where some alerts remain that are not linked to any sites (since there's only one last remaining). My context only has an includeRegex "http://localhost:3000.*". I'm using the node official API.

**Steps my test is doing**:
1. Running a local web server of [Gogs ](https://gogs.io/) on localhost:3000.
2. Using [Puppeteer](https://github.com/GoogleChrome/puppeteer) to automate some actions using ZAP as a proxy.
- Go to the main page
- Click the login button
- Enter informations and login
- Click the repository creation button
- Enter informations and create new repository
- *** Add noise by navigating to google.com.
3. Polling the passive scanner until it's over.
4. Removing the sites that doesn't match the include regexes (http://localhost:3000.*).
5. Generating report

What's weird is that the extra alerts are there, but they don't appear on the reports. This is a problem because I'm using the number of alerts as a treshold to fail the tests, but they mismatch. So I tried to also delete the alerts that doesn't match the include regexes, but the API gives me an internal error. 

**Test output**:
Polling passive scanner.
Poll succeeded after 10.166s.
Removing extra sites scanned.
Removing site: https://fonts.googleapis.com
Removing site: https://ogs.google.com
Removing site: https://apis.google.com
Removing site: https://ajax.googleapis.com
Removing site: https://fonts.gstatic.com
Removing site: https://google.com
Removing site: https://www.gstatic.com
Removing site: https://ssl.gstatic.com
Removing site: https://www.google.com
Removing site: https://secure.gravatar.com
Removing extra alerts remaining.
Removing alert with id "43" for site "https://www.google.com/logos/2019/halloween19/rc1/messages.en.nocache.json"
##[error]500 - {"code":"internal_error","message":"Internal Error"}

**Update**: I tried deleting the alerts before the sites, and the api is not giving an error anymore, but some alerts remain. Looks like it's not just after sites deletion but even after the specific alert deletion.

**Second test output:**
Polling passive scanner.
Poll succeeded after 10.165s.
Removing extra alerts outside of context.
...
Removing alert with id "43" for site "https://www.google.com/logos/2019/halloween19/rc1/messages.en.nocache.json"
...
Removing extra sites scanned outside of context.
Removing site: https://fonts.googleapis.com
Removing site: https://ajax.googleapis.com
Removing site: https://apis.google.com
Removing site: https://fonts.gstatic.com
Removing site: https://google.com
Removing site: https://ogs.google.com
Removing site: https://www.gstatic.com
Removing site: https://ssl.gstatic.com
Removing site: https://www.google.com
Removing site: https://secure.gravatar.com
Writing HTML report.
Writing XML report.
Alerts: {"High":0,"Low":7,"Medium":2,"Informational":1}

Alerts on the report are "Low": 3, "Medium": 1, "Informational": 1.

**Comment by kingthorin** [comment] 2019-10-31 19:43
This is likely a duplicate of: https://github.com/zaproxy/zaproxy/issues/2593

**Comment by simchev** [comment] 2019-10-31 19:49
You're right, looks like a duplicate.

**Comment by simchev** [comment] 2019-10-31 20:06
As a workaround, I'm parsing the report to get the number of alerts.

**Comment by thc202** [comment] 2019-11-04 15:17
For your use case you might want to enable "Only scan messages in scope" https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsPscanner

**Comment by kingthorin** [comment] 2019-11-04 15:19
Closing as duplicate of zaproxy/zaproxy#2593

**Closed** 2019-11-04 15:22 UTC
Labels: duplicate
