### ISSUE TITLE
ZAP Active scan for soap end point is not working

### ISSUE THREAD

**Issue by BhavaMada** [zaproxy/zaproxy#4832] opened 2018-07-12 09:32 UTC
details are at this user group:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/zaproxy-develop/LTlb8L8fGCo/HywdPB5uBgAJ

I have installed SOAPScanner add-on in my ZAP 2.7.0.
Imported wsdl and ran active scan from the Sites tree. I got 0 alerts. 
When I look at the log, I see SOAP* attacks were showing '**0 message(s) sent** and 0 alert(s) raised.'

see below log details:

2018-07-11 20:32:34,542 [Thread-118] INFO  HostProcess - start host https://xxxxxxxxx | SOAPActionSpoofingActiveScanner strength MEDIUM threshold MEDIUM
2018-07-11 20:32:34,542 [Thread-118] INFO  HostProcess - completed host/plugin https://xxxxxxxxx | SOAPActionSpoofingActiveScanner in 0s with 0 message(s) sent and 0 alert(s) raised.
2018-07-11 20:32:34,543 [Thread-118] INFO  HostProcess - start host https://xxxxxx | SOAPXMLInjectionActiveScanner strength MEDIUM threshold MEDIUM
2018-07-11 20:32:34,544 [Thread-118] INFO  HostProcess - completed host/plugin xxxxxxx | SOAPXMLInjectionActiveScanner in 0.001s with 0 message(s) sent and 0 alert(s) raised.
2018-07-11 20:32:34,545 [Thread-118] INFO  HostProcess - completed host xxxxxxxxxxxx in 22.027s
2018-07-11 20:32:34,545 [Thread-117] INFO  Scanner - scanner completed in 22.029s

**Comment by kingthorin** [comment] 2018-07-12 09:49
Can you share your wsdl?

**Comment by BhavaMada** [comment] 2018-07-12 10:07
<?xml version="1.0"?>

<definitions
            name="FNCEWS40MTOM"
            targetNamespace="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM/wsdl"
            xmlns="http://schemas.xmlsoap.org/wsdl/"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
            xmlns:mdef="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM/wsdl"
            xmlns:cdef="http://www.filenet.com/ns/fnce/2006/11/ws/wsdl"
            xmlns:ctyp="http://www.filenet.com/ns/fnce/2006/11/ws/schema" >

    <import location="https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi/FNCEWS40MTOM/FNCEWS40.wsdl" namespace="http://www.filenet.com/ns/fnce/2006/11/ws/wsdl"/>

    <binding name="FNCEWS40MTOMBinding" type="cdef:FNCEWS40PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="GetObjects">
            <soap12:operation soapAction="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM#GetObjects"/>
            <input>
                <soap12:header message="cdef:LocalizationHeader" part="header" use="literal"/>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
           </output>
           <fault name="GeneralError">
                <soap12:fault name="GeneralError" use="literal"/>
           </fault>
        </operation>
        <operation name="ExecuteChanges">
            <soap12:operation soapAction="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM#ExecuteChanges"/>
            <input>
                <soap12:header message="cdef:LocalizationHeader" part="header" use="literal"/>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
           </output>
           <fault name="GeneralError">
                <soap12:fault name="GeneralError" use="literal"/>
           </fault>
        </operation>
        <operation name="ExecuteSearch">
            <soap12:operation soapAction="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM#ExecuteSearch"/>
            <input>
                <soap12:header message="cdef:LocalizationHeader" part="header" use="literal"/>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
           </output>
           <fault name="GeneralError">
                <soap12:fault name="GeneralError" use="literal"/>
           </fault>
        </operation>
        <operation name="GetSearchMetadata">
            <soap12:operation soapAction="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM#GetSearchMetadata"/>
            <input>
                <soap12:header message="cdef:LocalizationHeader" part="header" use="literal"/>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
            <fault name="GeneralError">
                <soap12:fault name="GeneralError" use="literal"/>
            </fault>
        </operation>
        <operation name="GetContent">
            <soap12:operation soapAction="http://www.filenet.com/ns/fnce/2006/11/ws/MTOM#GetContent"/>
            <input>
                <soap12:header message="cdef:LocalizationHeader" part="header" use="literal"/>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
           </output>
           <fault name="GeneralError">
                <soap12:fault name="GeneralError" use="literal"/>
           </fault>
        </operation>
    </binding>

    <service name="FNCEWS40Service">
        <documentation>FileNET P8 Content Engine Web Service</documentation>
        <port name="FNCEWS40MTOMPort" binding="mdef:FNCEWS40MTOMBinding">
            <soap12:address location="https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi/FNCEWS40MTOM/"/>
        </port>
    </service>

</definitions>

**Comment by kingthorin** [comment] 2018-07-12 10:34
Thanks

**Comment by BhavaMada** [comment] 2018-07-13 08:07
@kingthorin , do you have any work around/ fix/suggestions to test soap endpoint ?

**Comment by kingthorin** [comment] 2018-07-13 09:38
Not yet.

**Comment by psiinon** [comment] 2018-07-13 10:12
@BhavaMada what url are you scanning from? It looks like the wsdl definition is on a different host to the endpoints. If you just try to scan the wsdl definition then you wont be hitting any of the endpoints.

**Comment by BhavaMada** [comment] 2018-07-13 15:41
@psiinon , scan url is https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi . 

I got that wsdl file from this url - https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi/FNCEWS40MTOM?wsdl

ZAP Sites tree has this POST request - POST https://gte-tprov-hadr2.ibmbrsandbox.com/wsi/FNCEWS40MTOM/ HTTP/1.1

Note: Import WSDL.. functionality is not working after SOAPScanner Add-On installed. so I achieved thr using SoapUI that import the wsdl and proxy to ZAP.

**Comment by psiinon** [comment] 2018-07-13 15:56
If you are scanning from https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi then that wont include the POST request at https://gte-tprov-hadr2.ibmbrsandbox.com/wsi/FNCEWS40MTOM/ - thats on a different domain.
Try scanning from https://gte-tprov-hadr2.ibmbrsandbox.com/wsi/

**Comment by BhavaMada** [comment] 2018-07-13 16:00
@psiinon , fyi. I just used my own simple test soap end point and seems to be not working too.... [webservice running locally in my laptop] here are the details for your troubleshooting:

this time Import WSDL... functionality in ZAP works 

**log**
2018-07-13 16:52:20,342 [Thread-12] INFO  HostProcess - start host http://localhost:8089 | ScriptsActiveScanner strength MEDIUM threshold MEDIUM
2018-07-13 16:52:20,343 [Thread-12] INFO  HostProcess - skipped plugin [no scripts enabled] http://localhost:8089 | ScriptsActiveScanner in 0.001s with 0 message(s) sent and 0 alert(s) raised.
2018-07-13 16:52:20,343 [Thread-12] INFO  HostProcess - start host http://localhost:8089 | SOAPActionSpoofingActiveScanner strength MEDIUM threshold MEDIUM
2018-07-13 16:52:20,346 [ZAP-ActiveScanner-0] ERROR SOAPActionSpoofingActiveScanner - 
java.lang.NullPointerException
	at org.zaproxy.zap.extension.soap.SOAPActionSpoofingActiveScanner.scan(SOAPActionSpoofingActiveScanner.java:112)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:380)
	at java.lang.Thread.run(Thread.java:748)
2018-07-13 16:52:20,347 [Thread-12] INFO  HostProcess - completed host/plugin http://localhost:8089 | SOAPActionSpoofingActiveScanner in 0.004s with **0 message(s) sent** and 0 alert(s) raised.
2018-07-13 16:52:20,348 [Thread-12] INFO  HostProcess - start host http://localhost:8089 | SOAPXMLInjectionActiveScanner strength MEDIUM threshold MEDIUM
2018-07-13 16:52:20,370 [Thread-12] INFO  HostProcess - completed host/plugin http://localhost:8089 | SOAPXMLInjectionActiveScanner in 0.022s with **0 message(s) sent** and 0 alert(s) raised.
2018-07-13 16:52:20,370 [Thread-12] INFO  HostProcess - completed host http://localhost:8089 in 3.542s
2018-07-13 16:52:20,372 [Thread-11] INFO  Scanner - scanner completed in 3.548s

**Comment by BhavaMada** [comment] 2018-07-13 16:02
wsdl file
![image](https://user-images.githubusercontent.com/17451083/42701443-7f302b82-86be-11e8-9e9f-b69ffb49737c.png)

**Comment by BhavaMada** [comment] 2018-07-14 12:37
@psiinon , I have two envi,  https://gte-tprov-hadr2.ibmbrsandbox.com/wsi/ and https://gte-tprov-ansible-pj.ibmbrsandbox.com/wsi . The issue exists in both envi. Sorry for the mixing them in my earlier update. 

Now I am getting same issue when I use my simple soap test endpoint as described above. Here localhost and no issue with domain. Please suggest whats happening here and how to make it working for soap endpoint. Thanks

**Comment by kingthorin** [comment] 2018-07-14 12:41
SOAPActionSpoofingActiveScanner Is encountering a NullPointerException because it can’t find any actions in your wsdl, can’t speak for the other one yet.

**Comment by psiinon** [comment] 2018-07-16 07:39
@BhavaMada - can you attach your wsdl as a text file - we can then try that locally to reproduce the issue(s).
Does this WSDL file actually work in practice (I'm not a SOAP expert;). As @kingthorin has mentioned, the NPE is caused by the code failing to find any actions in your WSDL. We can easily fix the NPE but we might need to make more significant changes to allow the code to extract the actions correctly.

**Comment by BhavaMada** [comment] 2018-07-16 09:44
@psiinon @kingthorin , I got the wsdl files from the server urls, so it comes from the server. The applications have been running for years and all the endpoints are working fine. The sample application  that I wrote is running locally and tested successfully.
[BhavaSoapWS.txt](https://github.com/zaproxy/zaproxy/files/2197125/BhavaSoapWS.txt)
[hadr2-MTOM.txt](https://github.com/zaproxy/zaproxy/files/2197131/hadr2-MTOM.txt)

If possible can you fix that NPE and give me a patch to test and see it works or not.

**Comment by kingthorin** [comment] 2018-07-16 12:35
Fixing the NPE won’t mean that it gets scanned, it’ll just mean that the condition is more elegantly handled. If there’s no actions then there’s nothing for that specific scan rule to do. I still haven’t had a chance to look into the second one.

**Comment by kingthorin** [comment] 2018-07-19 14:03
FYI I did get something setup and working XAMPP.

**Comment by BhavaMada** [comment] 2018-07-19 21:31
Thank you for working on it and I am waiting for a solution asap.

**Comment by kingthorin** [comment] 2018-07-23 13:06
@BhavaMada in fixing this we've identified a bunch of other things in the SOAP extension that need some attention. In the mean time you could look at: https://github.com/RUB-NDS/WS-Attacker

**Comment by kingthorin** [comment] 2019-03-14 01:52
The npe has been addressed, closing.

**Closed by kingthorin** 2019-03-14 01:52 UTC
Labels: add-on

**Comment by thc202** [comment] 2019-03-14 10:24
For the record, it was fixed in zaproxy/zap-extensions#1725.
