### ISSUE TITLE
More clear GUI (menu)

### ISSUE THREAD

**Issue by DelvinBa** [zaproxy/zaproxy#8528] opened 2024-06-20 09:43 UTC
### Describe the bug

In my opinion, the menu bar is a bit overloaded and could be made clearer. Currently, gray bars separate the icons into logical groups, which complicates the overview (see screenshot). A better solution might be to introduce dropdown menus for the various groups. This change could simplify navigation and enhance usability, making it easier for users to find and use different features effectively.

### Steps to reproduce the behavior

-

### Expected behavior

-

### Software versions

2.15.0

### Screenshots

![ZAP-Menüleiste](https://github.com/zaproxy/zaproxy/assets/99075563/3becacfc-7779-4c8f-908c-55e5b3c60bea)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2024-06-20 09:45
Closing as duplicate of #8376.

**Closed by thc202** 2024-06-20 09:45 UTC
Labels: bug
