### ISSUE TITLE
Active Scan Advanced Options Changes Should be Remembered on All Tabs Between Scans

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#6096] opened 2020-07-22 23:01 UTC
**Is your feature request related to a problem? Please describe.**
I manually scanned 6 different folders in OWASP Benchmark one folder at a time. To do this I launched active scan on one folder, turned on Advanced Options, and then made changes on two tabs:

a) I turned one a couple of additional Input Vectors
b) On the Technology tab I unchecked all the DBs.

When I went to scan the second folder I did the same:
a) On the Input Vectors tab I noticed the boxes I checked previously were still checked. (Good)
b) On the Technology tab, all the DBs were enabled again (Bad)

**Describe the solution you'd like**
If someone changes any of the Advanced Scanning settings, can you remember all the changes on every tab so the next scan will use the same settings unless the user changes them again.

It's especially strange to remember changes on one tab, but not on others. That's confusing/unexpected behavior.

It would probably also be nice to save these changes if the user saves a session and restores it, so those changes persist across sessions as well.

**Comment by kingthorin** [comment] 2020-07-22 23:44
I believe this is a duplicate of https://github.com/zaproxy/zaproxy/issues/3538

**Comment by psiinon** [comment] 2020-07-23 11:27
Agreed

**Closed by psiinon** 2020-07-23 11:27 UTC
Labels: duplicate
