### ISSUE TITLE
zap docker API scan

### ISSUE THREAD

**Issue by ssnmworld** [zaproxy/zaproxy#4570] opened 2018-04-04 17:34 UTC
Hi - I am using this command for zap docker for Rest API scan, and would like to override the host parameter in the swagger json file.

docker run  -v "$(pwd)":/zap/wrk/:rw -t owasp/zap2docker-weekly  zap-api-scan.py -d -t abc.json -O http://test.com -r reports/index.html -f openapi

Is -O the option to do the same ? That does not seem to work. Is there any documentation for the same? 

Thanks

**Comment by thc202** [comment] 2018-04-04 17:41
Only the description shown with the help of the script:
`-O                the hostname to override in the (remote) OpenAPI spec`

that's only intended to use with remote (URL) specs, if you have the file locally you are expected to change it.

**Comment by Vivekspkp** [comment] 2022-11-28 20:03
@ssnmworld have you got any solution for this

**Comment by kingthorin** [comment] 2022-11-28 20:44
If the replies above don’t help you, alternatives include:
1. A Replacer rule.
2. A host file entry.

**Comment by Vivekspkp** [comment] 2022-11-29 04:26
@kingthorin could you please explain little details on Replacer rule / host file entry with an example. currently i am trying to replace the host with below code and this is not working for me
docker run -v C:/SampleAPI:/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t app.yml -f openapi -z "-config /zap/wrk/options.prop" -r api_active_scan_report_html -c api-active-scan.conf -O https://abc.serices/v1

Thanks,

**Comment by thc202** [comment] 2022-11-29 09:04
Closing as duplicate of #5510 (which has clearer title).

**Closed by thc202** 2022-11-29 09:04 UTC
Labels: Docker
