### ISSUE TITLE
zap.sh script stop working if JAVA_TOOL_OPTIONS variable set.

### ISSUE THREAD

**Issue by JWebDev** [zaproxy/zaproxy#7390] opened 2022-07-26 09:10 UTC
### Describe the bug

I use Owasp Zap as docker container. In this container runs my small java application.
If i set JAVA_TOOL_OPTIONS as Environment variable, then zap.sh script cannot detect JAVA_MAJOR_VERSION/JAVA_MINOR_VERSION or some other stuff and zap daemon does not starts. 
Error is clear and easy reproducible.

### Steps to reproduce the behavior

Just set Env Variable to docker container
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

### Expected behavior

zap.sh will start independent of such Java Env Variables.

### Software versions

owasp/zap2docker-stable:2.11.1

### Errors from the zap.log file

```
Using ZAP command line options: -host 0.0.0.0 -port 9988
2022-07-25T06:01:37.623944800Z /zap/zap.sh: line 51: [: -ge: unary operator expected
2022-07-25T06:01:37.623972100Z /zap/zap.sh: line 54: [: -ge: unary operator expected
2022-07-25T06:01:37.623974200Z Exiting: ZAP requires a minimum of Java 8 to run, found 
```
And in line 51-54 are checks depends of these vars
```
JAVA_VERSION=$(java -version 2>&1 | awk -F\" '/version/ { print $2 }')
JAVA_MAJOR_VERSION=${JAVA_VERSION%%[.|-]*}
JAVA_MINOR_VERSION=$(echo $JAVA_VERSION | awk -F\. '{ print $2 }')
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2022-10-05 18:18
What version of java is in the container?

**Comment by thc202** [comment] 2022-10-28 06:24
As workaround you can execute the Java command directly instead of starting through the script.

**Comment by dfuentes77** [comment] 2022-11-01 22:39
> As workaround you can execute the Java command directly instead of starting through the script.

I get a failed command even when running `java -version`.  Do you have an example command to run directly, even if `java -version` fails?  Thanks!

**Comment by kingthorin** [comment] 2022-11-01 23:25
This seems to be a duplicate of: https://github.com/zaproxy/zaproxy/issues/7556

please upgrade your runner to handle up-to-date images.

**Closed by kingthorin** 2022-11-01 23:25 UTC
Labels: bug
