### ISSUE TITLE
Adding Client Certificate 

### ISSUE THREAD

**Issue by pbrody4** [zaproxy/zaproxy#5361] opened 2019-05-15 19:37 UTC
I am trying to add a client certificate to OWASP zap, but keep receiving "wrong password or driver" error. The web pages I have been tasked to assess are .mil USMC pages, that require CAC authentication. It seems like with my proxy set to localhost, FF is trying to use OWASP Root CA and the .mil do not like that, thus receiving "fatal handshake error"

How can I add either add my CAC certificates or DOD Root CA to OWASP so that ZAP attempts to use these instead of the OWASP Root CA. 

*Side note, when my browser proxy settings are set to "automatic" i can successfully navigate to .mil webpage and it will prompt me for my CAC credentials and pin.

**Comment by kingthorin** [comment] 2019-05-15 19:39
Please don't ask questions as issues - the ZAP User Group https://groups.google.com/group/zaproxy-users is a much better place for questions.

Additionally this is a duplicate of zaproxy/zaproxy#5357

**Closed by kingthorin** 2019-05-15 19:39 UTC

**Comment by pbrody4** [comment] 2019-05-15 19:43
This is an issue, as I can not preform a web assessment with ZAP not allowing me to use client certificates. 

And i did not receive much help on #5357, so I wanted to re-word.

**Comment by psiinon** [comment] 2019-05-16 08:09
Raising a new issue just to reword an existing one does help. Just update the original one.
