### ISSUE TITLE
Error during SonarQube Scanner execution Caused by: The rule 'ZAProxy:10094' does not exist.

### ISSUE THREAD

**Issue by digitalhuman** [zaproxy/zaproxy#4635] opened 2018-05-01 10:00 UTC
I have no idea what this is about but hopefully you can help me out.

The command executed:
`C:\Users\vangelier\Downloads\sonar-scanner-msbuild-4.0.2.892\sonar-scanner-3.0.3.778\bin\sonar-scanner.bat -e -Dsonar.host.url=http://localhost:9000 -Dsonar.dependencyCheck.severity.critical=7.0 -Dsonar.sourceEncoding=UTF-8 -Dsonar.sources=. -Dsonar.login=3863330d43ae262f582b2a6e062a583d15b31da7 "-Dsonar.exclusions=node_modules/**, platforms/**, plugins/**" -Dsonar.projectKey=ZAP_EXAMPLE_JOB -Dsonar.dependencyCheck.severity.major=4.0 -Dsonar.verbose=true -Dsonar.zaproxy.reportPath=reports/zapproxy_report.xml -Dsonar.projectName=ZAP_EXAMPLE_JOB "-Dsonar.projectBaseDir=C:\Program Files (x86)\Jenkins\workspace\ZAP_EXAMPLE_JOB"`

And then the log from the point where it crashes:
`
09:48:03.971 DEBUG: 'reports/zapproxy_report.xml' generated metadata  with charset 'UTF-8'
09:48:03.972 DEBUG: Count lines in C:/Program Files (x86)/Jenkins/workspace/ZAP_EXAMPLE_JOB/reports/zapproxy_report.xml
09:48:04.203 INFO: Sensor XML Sensor [xml] (done) | time=259ms
09:48:04.203 INFO: Sensor OWASP Zap-Check [zap]
09:48:04.204 INFO: Process ZAP report
09:48:04.239 INFO: Process ZAP report (done) | time=35ms
09:48:04.243 INFO: ------------------------------------------------------------------------
09:48:04.243 INFO: EXECUTION FAILURE
09:48:04.243 INFO: ------------------------------------------------------------------------
09:48:04.243 INFO: Total time: 3.871s
09:48:04.321 INFO: Final Memory: 47M/305M
09:48:04.321 INFO: ------------------------------------------------------------------------
09:48:04.321 ERROR: Error during SonarQube Scanner execution
java.lang.RuntimeException: Can not process ZAP report. Ensure the report are located within the project workspace and that sonar.sources is set to reflect these paths (or set sonar.sources=.)
	at org.sonar.zaproxy.ZapSensor.execute(ZapSensor.java:159)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: The rule 'ZAProxy:10094' does not exist.`

I have debug enabled but I still do not have enough information to find were and why it crashes. I validated the output from the console and Jenkins is correct.

**Comment by thc202** [comment] 2018-05-01 10:16
This should be reported in: https://github.com/Coveros/zap-sonar-plugin

That's caused by missing definition of the rule in: https://github.com/Coveros/zap-sonar-plugin/blob/develop/sonar-zap-plugin/src/main/resources/org/sonar/zaproxy/rules.xml
The rules (IDs) can be found in https://github.com/zaproxy/zaproxy/blob/develop/src/doc/scanners.md so that's because of Base64 Disclosure.

Note that you can add the missing rule:
https://github.com/Coveros/zap-sonar-plugin#plugin-configuration

References:
Coveros/zap-sonar-plugin#4

**Comment by kingthorin** [comment] 2018-05-01 10:16
10094 is Base64 disclosure.
https://github.com/zaproxy/zaproxy/blob/develop/src/doc/scanners.md

Which is a Passive scanner in the alpha package.
https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/pscanrulesAlpha

You'll have to install the appropriate extension to use it.

https://github.com/Coveros/zap-sonar-plugin

**Comment by digitalhuman** [comment] 2018-05-01 10:33
@kingthorin Am I missing a Sonar plugin or a Zap plugin?

**Comment by kingthorin** [comment] 2018-05-01 10:36
ZAP

**Comment by thc202** [comment] 2018-05-01 10:40
None, what's missing is the definition of the rule in the Sonar plugin.

**Comment by digitalhuman** [comment] 2018-05-01 10:54
@thc202 nope, its there:

**Comment by kingthorin** [comment] 2018-05-01 10:58
That’s the details from a report, not the SonarQube definition.

BTW you might want to enable some of the global excludes or define a context you probably don’t want or need results for Firefox’s initiated requests like detectportal (as seen in your example).

**Comment by kingthorin** [comment] 2018-05-01 11:00
As @thc202 suggested earlier, you’re probably better off taking this up with the maintainers of the DonarQube plugin: https://github.com/Coveros/zap-sonar-plugin

**Comment by digitalhuman** [comment] 2018-05-01 11:00
Yeah probably yes. @kingthorin Thanks I will take it up to the Sonar stuff. Thanks anyway;)

**Comment by thc202** [comment] 2018-05-01 11:30
Thanks for raising the issue! Closing, being handled in Coveros/zap-sonar-plugin#21.

**Closed by thc202** 2018-05-01 11:30 UTC
Labels: third-party
