### ISSUE TITLE
Open Session Feature not properly working in Mac

### ISSUE THREAD

**Issue by mdel93** [zaproxy/zaproxy#6996] opened 2021-12-28 13:14 UTC
**Describe the bug**
It's not possible to find a session when it's located in a place that it's not my user folder in Mac

**To Reproduce**
1. Go to File tab
2. Click on Open session
3. Try to find a session in a folder that it's not the user folder(that it's the one redirected by default)

**Expected behavior**
I should be able to find a saved session that it's not placed in my user folder

**Software versions**
 - ZAP: 2.11.1 (but I was also experiencing this problem in the past
 - OS: macOS (observed in different versions)
 - Java: opendjdk 16.0.1

**Comment by thc202** [comment] 2021-12-28 13:30
Closing as duplicate of #6444.

**Closed by thc202** 2021-12-28 13:30 UTC
Labels: bug

**Comment by thc202** [comment] 2021-12-28 13:31
For the record, you need to give ZAP (Java) permissions to access other parts of the file system.
