### ISSUE TITLE
Feature Request: Default Eclipse Formatting Profile and Settings for Eclipse as part of DevGuide lines

### ISSUE THREAD

**Issue by JordanGS** [zaproxy/zaproxy#2843] opened 2016-08-31 15:37 UTC
Standardize how we want the code formatted and what we want eclipse to do on save (remove excess white spaces for example), export this profile and make it publically available.

https://github.com/zaproxy/zaproxy/wiki/DevGuidelines

**Comment by kingthorin** [comment] 2016-08-31 16:23
https://groups.google.com/forum/#!searchin/zaproxy-develop/format%7Csort:date/zaproxy-develop/X5i-1lvuqhc/_nSdDgvYCQAJ

**Comment by kingthorin** [comment] 2018-04-16 01:54
Marking as duplicate of zaproxy/zaproxy#3503, and closing in favor of that other one which is currently assigned and being worked on.

**Closed by kingthorin** 2018-04-16 01:54 UTC
Labels: Type-Task, duplicate
