### ISSUE TITLE
Zap Mac - Apply CPU - Installed binary - Not working

### ISSUE THREAD

**Issue by owndomainhome** [zaproxy/zaproxy#8103] opened 2023-10-05 15:02 UTC
### Describe the bug

The message when i try to open is “OWASP ZAP” cant open because cant verify the developer.

“OWASP ZAP” no se puede abrir porque no se puede verificar el desarrollador.

### Steps to reproduce the behavior

1. Download from https://www.zaproxy.org/download/
2. Install the https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_aarch64.dmg package.
3. Try to execute.

### Expected behavior

The installed app, must run.

### Software versions

https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_aarch64.dmg

### Screenshots

<img width="302" alt="Captura de pantalla 2023-10-05 a la(s) 12 01 20" src="https://github.com/zaproxy/zaproxy/assets/143448956/bdf6b833-eca0-4feb-b258-1a0de7611e08">

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2023-10-05 15:04
Closing as duplicate of #6162. The references issue mentions the workaround.

**Closed by thc202** 2023-10-05 15:04 UTC
Labels: bug
