### ISSUE TITLE
CHOWN from zap to 1337/1000 leads to permission denied writting to mounted /zap/wrk drive

### ISSUE THREAD

**Issue by midwestKC-coder** [zaproxy/zaproxy#7669] opened 2022-12-29 16:58 UTC
### Describe the bug

Changing the ownership of the mounted docker drive from zap to 1337/1000 leads to 'Permission Denied'

### Steps to reproduce the behavior

touch file in /zap/wrk leads to permissions denied.

### Expected behavior

Ability to write files to the docker mounted drive (/zap/wrk)

### Software versions

Latest ZAP 2.12.0 as can be seen by chown on /zap/wrk is 1000.

### Additional context

We have added the following to zap_started to help track down the issue ( code in zap_start_debug_code.txt).

Zap_2.11.1 shows /zap/wrk with owner zap and touch wrk/hi.txt is successful.
Zap_2.12.0 shows /zap/wrk with owner 1000 and touch wrk/hi.txt fails with permission error.
Note : Zap_2.12.0 was working successfully for us until the chown from zap to 1337/1000 was done.

Host information :
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"

[zap_start_debug_code.txt](https://github.com/zaproxy/zaproxy/files/10320573/zap_start_debug_code.txt)
[zap_2.11.1_log_section.txt](https://github.com/zaproxy/zaproxy/files/10320574/zap_2.11.1_log_section.txt)
[zap_2.12.0_log_section.txt](https://github.com/zaproxy/zaproxy/files/10320575/zap_2.12.0_log_section.txt)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-12-29 17:32
Have you built the stable image with #7658?

**Comment by ricekot** [comment] 2022-12-30 11:57
Duplicate of #7655.
The stable image with the fix will be released on the first Monday of the next month (Jan 2, 2023).

**Closed by ricekot** 2022-12-30 11:57 UTC
Labels: bug, Docker
