### ISSUE TITLE
Windows installer is not signed

### ISSUE THREAD

**Issue by surferjeff** [zaproxy/zaproxy#7329] opened 2022-06-09 03:07 UTC
### Describe the bug

I downloaded the Windows 64 installer from:
https://www.zaproxy.org/download/

A box pops up and says, "Do you want to install this program from an _unknown_ publisher?"

No, I don't. 

I never install software that isn't signed.  I especially expect a security tool to be signed.

### Steps to reproduce the behavior

Download and run https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2_11_1_windows.exe on a Windows machine.

### Expected behavior

The installer to be signed.

### Software versions

2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-06-09 04:50
Closing as duplicate of #3337.

**Closed by thc202** 2022-06-09 04:50 UTC
Labels: bug, duplicate
