### ISSUE TITLE
docker: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by barbeque-squared** [zaproxy/zaproxy#7096] opened 2022-02-21 08:48 UTC
### Describe the bug

When running zap2docker-weekly (probably other images are/will be affected as well), we experience the following error:

```
2022-02-21 08:03:56,810 I/O error: HTTPSConnectionPool(host='example.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)
```

### Steps to reproduce the behavior

Minimal example that triggers this:
`docker run --pull always owasp/zap2docker-weekly zap-full-scan.py -t https://example.org`

I am able to reproduce this from a CI environment as well as my own desktop. And although we use a different URL for the actual CI, it does actually trigger on example.org as well

### Expected behavior

This particular error doesn't happen

### Software versions

owasp/zap2docker-weekly
at the time of writing this is
Digest: sha256:c5895a86cf4752e4a030fe854ff09836969776daf00024bc6b71646c19c620ca

### Errors from the zap.log file

The zap log from our CI environment doesn't actually contain the error, so I've copy-pasted the entire output when running it manually from a console:
[console.log](https://github.com/zaproxy/zaproxy/files/8107669/console.log)

### Additional context

Looking at our CI logs, this job last succeeded on Feb 14 (around 3:00 GMT) but has failed since Feb 15 (around 3:00 GMT). It is entirely possible that this will 'fix' itself with tomorrow's run, if that's the case I'll report back here and close this ticket.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2022-02-21 09:25
I could not reproduce this using 

- `docker run --pull always owasp/zap2docker-weekly zap-baseline.py -t https://example.org` 
 
which should be doing the same thing but without actually attacking the target site.

This could therefore be a problem with your environment.
What happens if you run: 

- `docker run -t owasp/zap2docker-stable curl https://www.example.com`

**Comment by barbeque-squared** [comment] 2022-02-21 10:57
A new image has been released in the meantime (sha256:be1601e80abddb209f5f62cf1d1541430bd57964da8f6e717587408498601099) but the issue still remains.

Interestingly, it doesn't error if I run it with your command, ie:
* `zap-baseline.py` - works, no error
* `zap-full-scan.py` - doesn't work, error

`curl` (I ran it on -weekly instead of -stable) also works just fine.

**Comment by psiinon** [comment] 2022-02-21 11:12
I can reproduce this using 

- `docker run --pull always owasp/zap2docker-weekly zap-baseline.py -t https://example.org --autooff`

**Comment by psiinon** [comment] 2022-02-21 11:16
For info

- `docker run --pull always owasp/zap2docker-stable zap-baseline.py -t https://example.org --autooff`

works fine, so thats a work around for the moment

**Comment by psiinon** [comment] 2022-02-21 12:12
This has been announced on the USer Group - if you have questions about this problem then please ask them on that thread rather than this issue.

**Comment by psiinon** [comment] 2022-02-21 12:12
https://groups.google.com/g/zaproxy-users/c/_rEXDz_NhYE/m/ykS6_gKvAQAJ

**Comment by psiinon** [comment] 2022-02-21 12:52
We believe the above mentioned PR will fix this issue. We will regenerate the docker images as soon as that has been merged and is available.
And of course update this ticket with the progress.

**Closed** 2022-02-21 12:52 UTC
Labels: bug, add-on

**Comment by psiinon** [comment] 2022-02-21 13:09
The docker images are being rebuilt now.

**Comment by psiinon** [comment] 2022-02-21 14:07
The Live docker image now works as expected.
We've had a hickup regenerating the weekly image but we think we've fixed that and have kicked off the generation again.

**Comment by psiinon** [comment] 2022-02-21 15:15
And I can confirm that the weekly image is also good :)
