### ISSUE TITLE
Update Crawljax Version in Ajax Spider

### ISSUE THREAD

**Issue by redkit75** [zaproxy/zaproxy#8650] opened 2024-09-24 17:00 UTC
### Is your feature request related to a problem? Please describe.

I'm frustrated that the Ajax Spider plugin is using an outdated version of Crawljax (version 3.7 from 2017). This older version may lack important updates, features, and security patches present in the newer versions. Given that Crawljax has received significant updates, including contributions from @thc202, the Ajax Spider plugin should ideally use a more recent version of Crawljax.

https://github.com/crawljax/crawljax/releases

### Describe the solution you'd like

I would like the Ajax Spider plugin to be updated to use the latest stable version of Crawljax, which is currently version 5.2.3. This update would ensure that ZAP benefits from the latest improvements and bug fixes in Crawljax, providing a more robust and feature-rich experience.

### Describe alternatives you've considered

An alternative could be to manually update the Crawljax version in the plugin, but this might not be feasible for all users and could lead to compatibility issues. It would be better if the update was handled natively within the plugin to ensure consistency and stability.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2024-09-24 17:07
This is a duplicate of #4792 and this is no longer the path forward as per #8646.

Note that we did try update it but the newer version has its issues (e.g. less findings, less stability) and that's the reason it was not done in the end, the version in use while older it's more reliable than the newer one.

**Closed by thc202** 2024-09-24 17:07 UTC
Labels: enhancement

**Comment by redkit75** [comment] 2024-09-24 19:51
I understand, but I think the codes in the current repository are older than version 3.7.1.
https://github.com/zaproxy/crawljax

I couldn't find the repository containing the changes below and others.
https://github.com/zaproxy/zap-extensions/pull/4369
