### ISSUE TITLE
Internet Explorer fail to launch when on Launch Browser button

### ISSUE THREAD

**Issue by pamidiaparna** [zaproxy/zaproxy#5213] opened 2019-02-07 15:32 UTC
**Describe the bug**
When I run ZAP, and try to launch IE from launch browser, it did not launch my browser.

- Installed ZAP from online, did not customized anything neither did any add-on's
- Configured ZAP to run at port 8090
- Changed proxy settings of IE, to use host localhost and port - 8090

**Software versions**
- IE- Version 11
- Zap - Version 2.7
- OS- Window 10
- JDK - 1.7

<sub>Edit: By @kingthorin 20190207 - Added issue details and cleaned up.</sub>

**Comment by kingthorin** [comment] 2019-02-07 15:34
You didn’t bother to actually complete the ticket details?

**Comment by pamidiaparna** [comment] 2019-02-07 16:26
Installed Software Versions
IE- Version 11
Zap - Version 2.7
OS- Window 10
JDK - 1.7
Installed ZAP from online, did not customized anything neither did any add-on's
configured ZAP to run at port 8090
Changed proxy settings of IE, to use host localhost and port - 8090 
when I run ZAP, and try to launch IE from launch browser, it did not launch my browser.

**Comment by psiinon** [comment] 2019-02-07 16:27
Have you updated all of the ZAP add-on, in particular the webdriver ones?

Note that IE does not support selenium (which we use to control the browser) that well, you'll probably be better off using a more modern browser like Firefox or Chrome.

**Comment by pamidiaparna** [comment] 2019-02-07 16:33
yeah, I have checked for updates by clicking on the manage add ons icon, prompts me that it up to date. 
unfortunately, I am not able to use to other browser because my project is limited to IE (the proj has to run on compatibility mode)

**Comment by psiinon** [comment] 2019-02-07 16:35
You can always run IE as normal and then import and trust the ZAP cert and configure IE to proxy via ZAP - that should be a work around: https://github.com/zaproxy/zap-core-help/wiki/HelpStartProxies

**Comment by psiinon** [comment] 2019-02-07 16:40
For info IE does not support ignoring certificate errors pr setting the proxy via selenium, so we might be better off just removing it as a browser launch option.

**Comment by pamidiaparna** [comment] 2019-02-07 16:41
yeah I already did follow above step. 
I was in an assumption that I have to run the project through ZAP (through launch browser), for it to behave as proxy and run the penetration tests.
As, I have already done above step (change lan settings), do you think I can run my browser independent of ZAP launch browser, ZAP will still be able to be as proxy and run the penetration test?

**Comment by kingthorin** [comment] 2019-02-07 16:44
> As, I have already done above step (change lan settings), do you think I can run my browser independent of ZAP launch browser, ZAP will still be able to be as proxy and run the penetration test?

Yes.

**Comment by kingthorin** [comment] 2019-02-07 16:47
> 
> 
> For info IE does not support ignoring certificate errors pr setting the proxy via selenium, so we might be better off just removing it as a browser launch option.

Confirmed:

<details>

<summary>IE Quick Start Failure - Stack Trace</symmary>

```log

310615 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch  - No matching capability sets found.
Unable to match capability set 0: acceptInsecureCerts was 'true', but the IE driver does not allow bypassing insecure (self-signed) SSL certificates
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'redacted', ip: 'redacted', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: acceptInsecureCerts was 'true', but the IE driver does not allow bypassing insecure (self-signed) SSL certificates
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'redacted', ip: 'redacted', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: InternetExplorerDriver
remote stacktrace: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.ie.InternetExplorerDriver.run(InternetExplorerDriver.java:223)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:215)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:192)
	at org.openqa.selenium.ie.InternetExplorerDriver.<init>(InternetExplorerDriver.java:164)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:725)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:652)
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:596)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:487)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:567)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:536)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:524)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:515)
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$4.run(ExtensionQuickStartLaunch.java:335)
	at java.lang.Thread.run(Thread.java:748)

```

<details>

**Comment by pamidiaparna** [comment] 2019-02-07 16:48
So, ZAP will still be able to run test. and log all alerts as usually. 
Just out off curiosity to learn, if it works that way, then what is the need of launch browser option in ZAP?

**Comment by kingthorin** [comment] 2019-02-07 16:49
There isn't a "need", it's functionality provided out of convenience.

**Comment by pamidiaparna** [comment] 2019-02-07 16:53
oh, thanks for the support.
Also, do I need to explicitly configure ZAP settings to run active attacks?

**Comment by psiinon** [comment] 2019-02-07 16:55
Yes, ZAP will passively scan any requests that are proxied through it, but it will only perform active attacks if you tell it to.
Have a look at the getting started guide: https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAPGettingStartedGuide-2.7.pdf

**Comment by pamidiaparna** [comment] 2019-02-07 18:34
I have changed, LAN settings of IE to use ZAP as proxy.
I have started my application through IE, I did not notice any scans or happening in ZAP. 
Alternatively, in the quick start I have provided the URL to attack, once the sites shows in the Sites section I have selected to do active attack, I again to run my application to see if the ZAP performs any test.
I am not sure if I am missing any step.
How exactly will I know if ZAP is performing any tests. 
Note: I have ran my browser independently not the one through launch browser in ZAP

**Comment by kingthorin** [comment] 2019-02-07 20:17
Since this is all basic usage details and how-to and there is no outstanding bug I'm going to close this ticket. 

The discussion can resume on the ZAP User Group https://groups.google.com/group/zaproxy-users which is a much better place for questions and usage discussions.

**Closed by kingthorin** 2019-02-07 20:17 UTC
Labels: question

**Comment by pamidiaparna** [comment] 2019-02-07 20:23
Can you please grant permissions for me - aparnap2407@gmail.com

**Comment by psiinon** [comment] 2019-02-08 09:34
@pamidiaparna permissions for what?
