### ISSUE TITLE
Stuck while loading [solved]

### ISSUE THREAD

**Issue by Gamerited** [zaproxy/zaproxy#5591] opened 2019-09-24 09:10 UTC
[SOLVED]
Solution: I changed my java to the latest version ,
update-alternatives --config java
and select the latest version

THANK YOU EVERYONE :) 
![Screenshot from 2019-09-24 11-33-53](https://user-images.githubusercontent.com/55739022/65498335-6f6b0700-dedb-11e9-9496-ac05d1cf97a3.png)
When ever i try to open Zap for first time it gets stuck at
Initializing keyboard shortcuts 
need help
i opened the program for 1st time

**Comment by psiinon** [comment] 2019-09-24 09:16
What OS and version are you using?
Which ZAP installer did you use?

**Comment by thc202** [comment] 2019-09-24 10:33
This seems to be a duplicate of #5526, updating to 2.8.1 should fix the issue.

**Comment by Gamerited** [comment] 2019-09-24 13:57
> What OS and version are you using?
> Which ZAP installer did you use?

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.3
Codename:	kali-rolling

**Comment by Gamerited** [comment] 2019-09-24 13:58
> This seems to be a duplicate of #5526, updating to 2.8.1 should fix the issue.

isnt 2.8.0 the latest?

**Comment by psiinon** [comment] 2019-09-24 14:14
As per https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-280-standard the linux release is 2.8.1

**Comment by thc202** [comment] 2019-09-24 14:34
Closing since it's now solved. Thanks for letting us know!

**Closed by thc202** 2019-09-24 14:34 UTC
Labels: bug
