### ISSUE TITLE
zap stopped working after 2.12.0 update

### ISSUE THREAD

**Issue by kvipz** [zaproxy/zaproxy#7618] opened 2022-11-25 18:51 UTC
### Describe the bug

I use ZAP for daily pentesting as part of a product in my organization where it stopped working after the latest images were made available on dockerhub. I understand there is a new network add on which has new APIs to be used.

I tried installing the 2.12.0 version on my mac device to prove the same in our corporate network we use our corporate HTTP proxy as well so I configured both the proxies under Network Option.

I also installed v 2.11.0 and configured same options under Connection and Local proxies section and it works like a charm.

I get the following exception with version 2.12.0

_Remote host terminated the handshake
EOFException: SSL peer shutdown incorrectly_

### Steps to reproduce the behavior

1. Use a corporate HTTPS proxy environment e.g 127.0.0.1:9077
2. Install v 2.12.0
3. Go to _Network > Connection_, Tick _Enabled_ checkbox and set Host: 127.0.0.1 and Port:9077
4. Go to _Local Servers / Proxies_, under _Main Proxy_ section set Address: localhost and Port: 8090
5. Go to _Server Certificates_ and save provided certificate
6. Go to Mozilla, import certificate and tick on Trust CA settings
7. Also set custom proxy go 127.0.0.1: 8090
8. Browse any website

### Expected behavior

Website page should load as it does with version 2.11.0

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-11-25 18:57
Could you provide the contents in Help > Support Info?

**Comment by kvipz** [comment] 2022-11-25 19:54
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=14.0.0],
[id=ascanrules, version=49.0.0], [id=automation,
version=0.19.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.5.0], [id=commonlib,
version=1.11.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=domxss, version=14.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.3.0], [id=formhandler, version=6.1.0],
[id=fuzz, version=13.8.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.11.0], [id=help, version=15.0.0], [id=hud,
version=0.15.0], [id=invoke, version=12.0.0], [id=network,
version=0.3.0], [id=oast, version=0.13.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=29.0.0],
[id=pscanrules, version=44.0.0], [id=quickstart,
version=35.0.0], [id=replacer, version=11.0.0], [id=reports,
version=0.16.0], [id=requester, version=7.0.0], [id=retest,
version=0.4.0], [id=retire, version=0.16.0], [id=reveal,
version=5.0.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=soap, version=15.0.0], [id=spider,
version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips,
version=10.0.0], [id=webdrivermacos, version=47.0.0],
[id=websocket, version=27.0.0], [id=zest, version=37.0.0]]

Operating System: Mac OS X
Architecture: x86_64
Java Version: Eclipse Adoptium 11.0.16.1
System’s Locale: en_IN
Display Locale: en_GB
Format Locale: en_IN
Default Charset: UTF-8
ZAP Home Directory: /Users/x682738/Library/Application Support/ZAP/

ZAP Installation Directory: /Users/a695742/Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

**Comment by thc202** [comment] 2022-11-25 19:58
Update the Network add-on to latest version, this might be #7594.

**Comment by kvipz** [comment] 2022-11-25 21:29
GUI doesn't show any update for the Network AddOn. Also, same problem is occurring with Docker Image 2.12.0 as well while it works with 2.11.0 image.

**Comment by thc202** [comment] 2022-11-25 21:41
Attach the zap.log when using the GUI.

**Comment by kvipz** [comment] 2022-11-27 09:50
[zap.log](https://github.com/zaproxy/zaproxy/files/10097958/zap.log)

**Comment by thc202** [comment] 2022-11-27 15:25
Could you include the ZAP start and the check for updates?

**Comment by kvipz** [comment] 2022-11-28 08:57
I am unable to check updates. It says _"Error encountered. Please check manually for new updates. (The output tab may contain further details)_

**Comment by thc202** [comment] 2022-11-28 09:14
I'm aware but I'd like to see the log when that happens.

**Comment by kvipz** [comment] 2022-11-28 09:26
[zap.zip](https://github.com/zaproxy/zaproxy/files/10102259/zap.zip)

I have removed older logs for convenience.

**Comment by thc202** [comment] 2022-11-28 09:58
Download https://github.com/zaproxy/zap-extensions/releases/download/network-v0.5.0/network-beta-0.5.0.zap move it into `/Users/a695742/Library/Application Support/ZAP/plugin` and provide the ZAP log again.

**Comment by kvipz** [comment] 2022-11-28 10:06
[zap.zip](https://github.com/zaproxy/zaproxy/files/10102584/zap.zip)

Here you go

**Comment by thc202** [comment] 2022-11-28 20:16
Sorry, I just noticed that the proxy fix was not yet released to marketplace. Could you try with the latest weekly release instead? https://www.zaproxy.org/download/#weekly

**Comment by kvipz** [comment] 2022-11-29 08:41
Latest Weekly release is working fine as expected. Can you share when the latest docker image and marketplace software with this version might get released?

**Comment by thc202** [comment] 2022-11-29 09:09
Thanks for giving it a try! Most likely during this week.

Closing as duplicate of #7594.

**Closed by thc202** 2022-11-29 09:09 UTC
Labels: bug, add-on
