### ISSUE TITLE
can't resend request

### ISSUE THREAD

**Issue by kabezag** [zaproxy/zaproxy#6368] opened 2020-12-18 20:51 UTC
**Describe the bug**
In today's update i cannot use the "resend request" feature. If the boton exist somewhere is not easy to see..

![image](https://user-images.githubusercontent.com/73066776/102660285-8f7a8c00-4159-11eb-8fd7-2a6ddd59c4e3.png)

version 2.10.0

**Comment by kingthorin** [comment] 2020-12-18 21:48
Could you try moving the left/right divider further to the right?

**Comment by kabezag** [comment] 2020-12-19 00:21
black magic! that fix my problem haha, thanks!

**Comment by kingthorin** [comment] 2020-12-19 01:18
Great, thanks for letting us know.

I’m going to leave this open we should see if there’s something we can do for those situations.

**Comment by thc202** [comment] 2020-12-19 10:46
Closing as duplicate of #5831.

**Closed by thc202** 2020-12-19 10:46 UTC
Labels: Component-UI, Usability, bug
