### ISSUE TITLE
No style on some page

### ISSUE THREAD

**Issue by kocoten1992** [zaproxy/zaproxy#8116] opened 2023-10-11 23:29 UTC
### Describe the bug

When using Manual Explore on `fetlife.com` (I'm doing bug bounty). Chrome from ZAP do not show style

![image](https://github.com/zaproxy/zaproxy/assets/7130705/b9241986-fcf9-4e01-b556-2f80d80ff43a)

![image](https://github.com/zaproxy/zaproxy/assets/7130705/23453dd9-ffbe-4363-926e-6a30d1dfa78b)

The reason is because cloudflare do care about `--compressed`, for example:

```
curl 'https://gav2.fetlife.com/vite/assets/application_style-d8186abf.js' --compressed

function c(){import.meta.url,import("_").catch(()=>1);async function*t(){}}export{c as __vite_legacy_guard};
//# sourceMappingURL=application_style-d8186abf.js.map
```

If we do not have `--compressed`:

```
curl 'https://gav2.fetlife.com/vite/assets/application_style-d8186abf.js'             
Not Found
```

The default when open ZAP Manual Explore trigger that.

### Steps to reproduce the behavior

1. Open ZAP
2. Open Manual Explore using chrome
3. enter `fetlife.com`

### Expected behavior

It should work normally (do have compressed on - some site care about that)

### Software versions

2.13

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2023-10-12 06:53
Disable the option "Remove Accept-Encoding Request Header" https://www.zaproxy.org/docs/desktop/addons/network/options/localservers/#remove-accept-encoding-request-header

**Comment by kocoten1992** [comment] 2023-10-12 07:29
Hi @thc202 , per documentation, this option was enabled by default, but that very confusing, should this option should be disable by default? :confused:

**Comment by thc202** [comment] 2023-10-12 07:42
No, per:
> The messages encoded with unsupported encodings will not be correctly scanned (either by passive and active scanners).

**Comment by kocoten1992** [comment] 2023-10-14 03:20
I think some creative solution is needed here, a normal user when they try zaproxy for the first time, when the site don't behave as user expected, they don't investigate further and will choose another solution..

**Comment by thc202** [comment] 2023-10-14 07:32
From the default browser encodings the only encoding missing is `br`, which we can add and this options could be disabled by default I guess.

Closing as duplicate of #2198.

**Closed by thc202** 2023-10-14 07:32 UTC
