### ISSUE TITLE
Fire fox fail to launch when to launch browser.

### ISSUE THREAD

**Issue by Shafiullah-durrani** [zaproxy/zaproxy#5102] opened 2018-11-02 17:35 UTC
i am using zap 2.7.0 
my Firefox version is 63.0.1  
selenum version is 13 
when i try to launch browser selecting Fire fox fail to launch .
i checked for updates also .  
i load zap certificate in Firefox 
any help ?

**Comment by thc202** [comment] 2018-11-02 18:48
Which version of WebDrivers add-on are you using? It should work with the latest version (7), it supports that version of Firefox.

**Comment by Shafiullah-durrani** [comment] 2018-11-04 13:17
i have no idea about webDrivers add-on.  can you provide the download link ? and also a configuration method how to configure and install these add-on  ? i will be thank full to you for this kind of act

**Comment by kingthorin** [comment] 2018-11-04 17:39
You can just get it via the Marketplace, just got the 3 cubes icon in the main toolbar.

**Comment by baptx** [comment] 2018-11-17 18:03
When I started Firefox through ZAP, it failed and closed the browser automatically for me also unlike other browsers. Updating Linux WebDrivers fixed the problem but it would be nice if the bug is fixed by default when installing ZAP.

**Comment by thc202** [comment] 2018-11-19 09:16
Thanks for letting us know. Note that this is not a bug but a known incompatibility between geckodriver and Firefox. [1]
Next version of ZAP will include the latest versions of the add-ons.

Closing per previous comment.

[1] https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html

**Closed by thc202** 2018-11-19 09:16 UTC

**Comment by psiinon** [comment] 2018-11-19 11:46
> When I started Firefox through ZAP, it failed and closed the browser automatically for me also unlike other browsers. Updating Linux WebDrivers fixed the problem but it would be nice if the bug is fixed by default when installing ZAP.

How did you install ZAP? Depending on what method you used you probably should have got an option to 'check for updates' which would have been defaulted to 'on'. If that was the case then ZAP should have warned you that there were updated add-ons available. If you were not presented with that option and it didnt default to 'on' then its a bug in ZAP. If you chose not to 'check for updates' then you disabled the option yourself so theres nothing we could have done ;)

**Comment by baptx** [comment] 2018-11-19 18:07
@psiinon I used the latest version 2.7.0 of the Linux Package (without installation) from this page: https://github.com/zaproxy/zaproxy/wiki/Downloads
It is using the default configuration, the option "check for updates on startup" and "check for updates to the addons you have installed" are enabled but I did not see any notification.

**Comment by psiinon** [comment] 2018-11-20 09:09
@baptx thats weird, we'll have to look at that :/ Thanks for letting us know.
