### ISSUE TITLE
Cannot Access IPv6 site using ZAP proxy

### ISSUE THREAD

**Issue by alanlia** [zaproxy/zaproxy#6672] opened 2021-07-07 10:23 UTC
Hello Everyone,

I recently came across an issue and I am stuck there. I was trying to perform some test on company website with its IPv6 address but was not able to do so. Can someone please help me on this?
Thank you.

**Comment by kingthorin** [comment] 2021-07-07 10:36
This is a known issue. There are plans to address it but no ETA.

Closing as duplicate of zaproxy/zaproxy#3705

**Closed by kingthorin** 2021-07-07 10:36 UTC
Labels: bug
