### ISSUE TITLE
Zap API for Docker WebSwing uses all ram available (3.5+ GB) and API Web interface never starts

### ISSUE THREAD

**Issue by ryepesg** [zaproxy/zaproxy#3504] opened 2017-05-09 15:27 UTC
I am using owasp/zap2docker-stable:2.5.0 as was recomended at https://github.com/zaproxy/zaproxy/issues/3497. When I use it at localhost it works just fine, even the client API.

But when I use it in a server (DigitalOcean, Google Cloud), then ZAP starts fine at 8080, using just about 700mb. But when I connect to 8090, it consumes all ram available (3.5 GB in my case). 

Then the API interface at 8090 always shows this error:
_Failed to read http://IP:8090/ within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel._

Here is the usage:
![selection_799](https://cloud.githubusercontent.com/assets/10557463/25858468/6ed1cd1a-34a1-11e7-8218-79deec60140b.png)

Here is the output in ZAP WebSwing at 8080:
![selection_800](https://cloud.githubusercontent.com/assets/10557463/25858495/80cf560e-34a1-11e7-8435-e8b217206450.png)

Here are some of the logs:

root@eb381e102ad4:/zap# **head -20 webswing.log** 
2017-05-09 15:09:24,957 ERROR [qtp914103910-33] (ServerUtil.java:167) Icon loading failed. File icon.png or /zap//icon.png does not exist.
2017-05-09 15:09:26,815 INFO  [pool-3-thread-1] (SwingJvmConnection.java:277) Setting bootclasspath to: -Xbootclasspath/a:"/zap/tmp/release/webapp/WEB-INF/lib/webswing-app-toolkit-java7-2.3.jar":"/zap/tmp/release/webapp/WEB-INF/lib/webswing-app-toolkit-2.3.jar":"/zap/tmp/release/webapp/WEB-INF/lib/rt-win-shell.jar"
2017-05-09 15:09:26,816 INFO  [pool-3-thread-1] (Los.java:40) [anonym9318d3f6473fZAP] The jvmargs attribute is deprecated. Please use nested jvmarg elements.
2017-05-09 15:09:26,817 INFO  [pool-3-thread-1] (Los.java:40) [anonym9318d3f6473fZAP] The args attribute is deprecated. Please use nested arg elements.
2017-05-09 15:09:31,870 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] ERROR: Converting file:/zap/lang/Messages.properties to safe url failed -> java.net.MalformedURLException
2017-05-09 15:09:31,871 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.net.URL.<init>(URL.java:630)
2017-05-09 15:09:31,871 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at org.webswing.classloader.SwingClassloader$1.findResource(SwingClassloader.java:184)
2017-05-09 15:09:31,871 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.lang.ClassLoader.getResource(ClassLoader.java:1147)
2017-05-09 15:09:31,871 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:227)
2017-05-09 15:09:31,872 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at org.webswing.classloader.SwingClassloader.getResourceAsStream(SwingClassloader.java:452)
2017-05-09 15:09:31,872 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2604)
2017-05-09 15:09:31,872 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2589)
2017-05-09 15:09:31,872 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.security.AccessController.doPrivileged(Native Method)
2017-05-09 15:09:31,872 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2588)
2017-05-09 15:09:31,873 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1436)
2017-05-09 15:09:31,873 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.findBundle(ResourceBundle.java:1400)
2017-05-09 15:09:31,874 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
2017-05-09 15:09:31,874 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
2017-05-09 15:09:31,874 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1296)
2017-05-09 15:09:31,875 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] at java.util.ResourceBundle.getBundle(ResourceBundle.java:841)

root@eb381e102ad4:/zap# **tail -20 webswing.log** 
2017-05-09 15:20:23,784 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653216 [ZAP-ProxyThread-100689] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,784 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653218 [ZAP-ProxyThread-100690] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,784 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653220 [ZAP-ProxyThread-100691] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,784 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653222 [ZAP-ProxyThread-100692] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653224 [ZAP-ProxyThread-100693] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653226 [ZAP-ProxyThread-100694] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653228 [ZAP-ProxyThread-100695] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653230 [ZAP-ProxyThread-100696] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653232 [ZAP-ProxyThread-100697] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653235 [ZAP-ProxyThread-100698] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653236 [ZAP-ProxyThread-100699] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653239 [ZAP-ProxyThread-100700] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653241 [ZAP-ProxyThread-100701] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653243 [ZAP-ProxyThread-100702] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653246 [ZAP-ProxyThread-100703] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653248 [ZAP-ProxyThread-100704] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653250 [ZAP-ProxyThread-100705] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,785 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653252 [ZAP-ProxyThread-100706] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,786 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653254 [ZAP-ProxyThread-100707] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.
2017-05-09 15:20:23,786 INFO  [Thread-18] (Los.java:40) [anonym9318d3f6473fZAP] 653257 [ZAP-ProxyThread-100708] WARN org.zaproxy.zap.session.CookieBasedSessionManagementHelper  - Multiple sessions matching the cookies from response. Using first one.

**Comment by thc202** [comment] 2021-04-16 18:21
Closing as duplicate of #3594.

**Closed by thc202** 2021-04-16 18:21 UTC
Labels: duplicate
