### ISSUE TITLE
Feature Request: start/stop/remove an AJAX spider scan from API

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6061] opened 2020-07-06 12:51 UTC
**Is your feature request related to a problem? Please describe.**
Comparable to `Spider`, start/stop/remove an AJAX spider scan from API

**Comment by thc202** [comment] 2020-07-06 13:10
Closing as duplicate of #1954 (start/stop is already supported).

**Closed by thc202** 2020-07-06 13:10 UTC
Labels: Component-API, add-on, enhancement

**Comment by hazcod** [comment] 2020-07-06 13:14
@thc202 can you link to the docs mentioning that?

**Comment by thc202** [comment] 2020-07-06 13:17
https://www.zaproxy.org/docs/api/#using-ajax-spider

**Comment by hazcod** [comment] 2020-07-06 13:22
Seem they are missing from https://github.com/zaproxy/zap-api-go/tree/master/zap

**Comment by thc202** [comment] 2020-07-06 13:25
Right, there are several API clients that are not that well maintained (lack of maintainer mainly), although I guess we could automate the update of the generated APIs (at least that would not lag behind).
