### ISSUE TITLE
Drupal version 10+ core getting flagged for 'Information Disclosure - Suspicious Comments'

### ISSUE THREAD

**Issue by dmundra** [zaproxy/zaproxy#8658] opened 2024-09-30 19:17 UTC
### Describe the bug:

We are using the zaproxy/zap-stable docker image to run checks on our Drupal version 10+ site and noticed that the default Drupal behavior is being flagged for 'Information Disclosure - Suspicious Comments'. The default behavior is Drupal core add's a JavaScript code with JSON that includes a 'user' section, here is an example output from a clean Drupal site 10.3.6-dev site

```
<script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","pathPrefix":"","currentPath":"node","currentPathIsAdmin":false,"isFront":true,"currentLanguage":"en"},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"ajaxPageState":{"libraries":"eJx9UFtuhDAMvFAgZ-hJViaZLtaGGNkGyu0LaKEqUvtjex52oqE8cH24SOlI47u3rkCgP6W2lxnK1VH9t-3odpk5SQ0dPx8jj4jnEDbW8eUTlZh1Gqm0P0xTuL7sf8v7_GZSnDIl5xnHdsiYse3t9fJK2WSV-AnkC1Sa-UnOUhvD9kAmXS9xlAWK3HRr0xVJr0swkKa-qaQqy51dOCNYL-pp8vNzJw62mmOIHRnCLdk7bmGJRnzs8YbJoOexfT6StTAzFotHbQfJU8E3JOK1OA","theme":"olivero","theme_token":null},"ajaxTrustedUrl":{"\/search\/node":true},"bigPipePlaceholderIds":{"callback=Drupal%5CCore%5CRender%5CElement%5CStatusMessages%3A%3ArenderMessages\u0026args%5B0%5D\u0026token=_HAdUpwWmet0TOTe2PSiJuMntExoshbm1kh2wQzzzAA":true,"callback=announcements_feed.lazy_builders%3ArenderAnnouncements\u0026\u0026token=m--BNYDqgTao0j2QoLFf1TwfQN-Bm9xPlckw9QAC1h4":true,"callback=devel.lazy_builders%3ArenderMenu\u0026\u0026token=3SaamyNrJZMMYe_kyv4Lc7-K5z3OkYidDaYEaMx_yVs":true,"callback=user.toolbar_link_builder%3ArenderToolbarLinks\u0026\u0026token=QPmvukHqpEJJ4rYEzUUFx0ERxrtfmQ9TMOp_hvyLHEk":true,"callback=user.toolbar_link_builder%3ArenderDisplayName\u0026\u0026token=XGROnxBLjNjdNZJ_VcOhVZtenx2tDkIKPfojS_uZFXA":true,"callback=shortcut.lazy_builders%3AlazyLinks\u0026\u0026token=5-XBI-QHgyU_l7Bu0FizHR7YBqK2bTVTBFF8Z0DVTis":true},"toolbar":{"breakpoints":{"toolbar.narrow":"only screen and (min-width: 16.5em)","toolbar.standard":"only screen and (min-width: 38.125em)","toolbar.wide":"only screen and (min-width: 61em)"},"subtreesHash":"B-xbDyd2Xys9mHk0VcBq6fzQc4gPgzYX7PH75yw2Rgg"},"user":{"uid":"1","permissionsHash":"is-admin"}}</script>
```

You can find that in any public Drupal site in the page source. The flagged details generated by Zap is the following:

> Evidence | user
> Other Info | The following pattern was used: \bUSER\b and was detected in the element starting with: "<script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","pathPrefix":"","currentPath", see evidence field for the suspicious comment/snippet.

Since this is a false positive and will likely be flagged for any Drupal 10+ site I wanted to share it here.

### Steps to reproduce the behavior:

The best way I found to recreate this on a vanilla Drupal site is by setting up a Drupal site with ddev following https://ddev.readthedocs.io/en/stable/users/quickstart/#drupal-drupal-10. If you don't want to do that locally you can also use ddev with gitpod by using the extension https://www.drupal.org/project/DrupalPod.

If you are using ddev, I was able to get zap to run against the local site with this extra compose file that is added to the .ddev folder, name is `docker-compose.zap.yml`:

```
services:
  zap:
    image: zaproxy/zap-stable
    volumes:
      - /tmp:/zap/wrk
    command: zap-baseline.py -d -t http://web -r zap-report.html
    depends_on:
      - web
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
```

That runs against the site when you run `ddev start/restart` and puts the report in the `/tmp` directory.

### Expected behavior:

I believe that user block of JSON should not be reported as suspicious content. That right now gets flagged for all URLs so we have to ignore 10027 from being flagged in our pipeline.

### Software versions:

Using the latest zaproxy/zap-stable docker version

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2024-10-01 00:38
Closing as a duplicate of: zaproxy/zaproxy#6736

**Closed** 2024-10-01 00:39 UTC
Labels: duplicate, FalsePositive, add-on
