### ISSUE TITLE
Unreleased zap-api-scan script gets stuck on "Records to passive scan" seemingly indefinitely

### ISSUE THREAD

**Issue by stephendonner** [zaproxy/zaproxy#3531] opened 2017-05-13 00:19 UTC
Using the following revision of https://hub.docker.com/r/psiinon/zap2docker-api/ - which is built from https://github.com/psiinon/zaproxy/blob/418d4273716fb7f62bafc5cd5ebd6d40531eeadf/build/docker/zap-api-scan.py

Steps (for me) to Reproduce:

1. docker pull psiinon/zap2docker-api
2. docker run -t psiinon/zap2docker-api zap-api-scan.py -t http://petstore.swagger.io/v2/swagger.json -d
3. After you see "Active Scan complete", followed by "Records to Scan...", I see the following seemingly endless loop:

[timestamp] Records to passive scan: 6893
<snip>
[timestamp + 1 hour, etc.] Records to passive scan: 6893
...

I've had to CTRL-C these runs when this occurs

Attached are both a screenshot of the repeating/stuck console output, as well as the more-relevant 
<img width="1158" alt="screen shot 2017-05-12 at 10 12 41 am" src="https://cloud.githubusercontent.com/assets/387249/26020731/3108b5be-3737-11e7-8535-78f8d95fedd8.png">
zap.out log when doing a ```kill -3 [java PID]```

[zap.out.txt](https://github.com/zaproxy/zaproxy/files/998222/zap.out.txt)

**Comment by thc202** [comment] 2017-05-13 10:50
Thanks for raising the issue.

Worth noting that this is not caused by the new functionality/script. It seems ZAP is stuck passive scanning a message (probably one with a big response), relevant thread/stack trace:
```
"ZAP-PassiveScanner" #20 daemon prio=5 os_prio=0 tid=0x00007f7d50920800 nid=0x56 runnable [0x00007f7d4ed69000]
   java.lang.Thread.State: RUNNABLE
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3776)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4260)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:637)
	at org.zaproxy.zap.extension.pscan.scanner.RegexAutoTagScanner.scanHttpResponseReceive(RegexAutoTagScanner.java:226)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:148)
```

**Comment by thc202** [comment] 2017-08-23 10:29
Closing per changes done in #3787.

**Closed by thc202** 2017-08-23 10:29 UTC
Labels: Type-Task

**Comment by stephendonner** [comment] 2017-08-25 18:04
Thanks!
