### ISSUE TITLE
Docker zap.sh failed on release 2.12.0

### ISSUE THREAD

**Issue by Arvinder12** [zaproxy/zaproxy#7572] opened 2022-11-03 12:23 UTC
### Describe the bug

When we start zap.sh as docker container it fails.

Docker image: owasp/zap2docker-stable: /2.12.0

[2.12.0](https://hub.docker.com/layers/owasp/zap2docker-stable/2.12.0/images/sha256-7a669aec036cb47107463c10a722fb581da3e7200b816de3feb92f05ccbcdb03?context=explore)

Error logs: 
docker run -p 8090:8090 -i owasp/zap2docker-stable:2.12.0 zap.sh -daemon -port 8090 -host 0.0.0.0
Exiting: ZAP requires a minimum of Java 11 to run, found 
/zap/zap.sh: line 50: [: -ge: unary operator expected

### Steps to reproduce the behavior

docker run -p 8090:8090 -i owasp/zap2docker-stable:2.12.0 zap.sh -daemon -port 8090 -host 0.0.0.0

### Expected behavior

Docker container should be created.

### Software versions

owasp/zap2docker-stable:2.12.0

### Screenshots

<img width="938" alt="Screenshot 2022-11-03 at 5 51 37 PM" src="https://user-images.githubusercontent.com/11042813/199719192-b85c32f9-eee1-4fc8-ae49-4ca849629c00.png">

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-11-03 12:30
Looks like a duplicate of #7556.

**Comment by thc202** [comment] 2022-11-04 20:47
Feel free to reopen if updating Docker does not address the issue.

**Closed by thc202** 2022-11-04 20:47 UTC
Labels: Docker
