### ISSUE TITLE
Allow passing file content to api instead of local reference

### ISSUE THREAD

**Issue by Sperez96** [zaproxy/zaproxy#7995] opened 2023-08-08 10:51 UTC
### Is your feature request related to a problem? Please describe.

If I want to launch an automation process, with an api scan, and the use of scripts, the api does not allow it in case it is executed in a different client than where the server is located

### Describe the solution you'd like

Allow a new post method to execute processes via api, and pass the contents of files (openapi, script) instead of the path needed to read them

### Describe alternatives you've considered

-

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2023-08-08 10:58
Duplicate of #7943

**Closed by psiinon** 2023-08-08 10:58 UTC
Labels: enhancement
