### ISSUE TITLE
Jenkins ZAProxy plugin issue on HTML and XML report generation

### ISSUE THREAD

**Issue by ghost** [zaproxy/zaproxy#2078] opened 2015-11-24 07:09 UTC
Hi,

When I open ZAP session (.session) file that is generated after scanning a website using ZAProxy plugin on Jenkins, the number of issues (high, medium, low and info) are not same as shown in HTML and XML report generated by the plugin tool.

FYI - I am running this on Windows 7 (Jenkins + ZAP) and using custom plugin to launch ZAP and ZAProxy plugin to scan the website.

Thanks to fix this reporting issue at the earliest possible on Jenkins ZAProxy plugin.

**Comment by chviswanath** [comment] 2015-11-24 07:45
Hi,
I just noticed that the problem lies in the actual HTML and XML report generation on ZAP itself. It's NOT the Jenkins plugin problem.
For example, I notice 2 high issues, 7 medium, 8 low and 6 information issues on ZAP session, but when I generate HTML or XML report, the number of issues are not same in the reports.

**Comment by thc202** [comment] 2015-11-24 08:23
If those numbers are shown in the "Alerts" tree (instead of "Alerts" count, show in the footer of the main window), that's (most likely) caused by the option "Merge related alerts in report" (in "Alerts" options panel). [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsAlert

**Comment by thc202** [comment] 2017-07-11 13:39
Closing, insufficient evidence (but see #2132 and #2757, which could be the cause).

**Closed by thc202** 2017-07-11 13:39 UTC
