### ISSUE TITLE
ZAP not responding while Scanning or Spidering

### ISSUE THREAD

**Issue by Ibrahimtesty** [zaproxy/zaproxy#5829] opened 2020-01-27 12:25 UTC
Hi, There
I am Using ZAP 2.9.0 since 3  weeks . Since last week ZAP getting hanged and not responding while Spider or Scanning in Firefox browser.
My system having 8GB Ram.
Thanks 
Shaik Ibrahim

**Comment by psiinon** [comment] 2020-01-27 12:41
We're going to need more information than that. 
https://www.zaproxy.org/faq/somethings-not-working-what-should-i-do/
Are there any errors in the zap.log file?

**Comment by kingthorin** [comment] 2020-02-04 19:26
@Ibrahimtesty any follow-up?

**Comment by mgariepy** [comment] 2020-02-13 13:40
i'm also having issue 
i reproduced this issue with 2 of my machines, one with 16g of ram the other with 32G.
 
$ ps aux |grep java
user 13095  206 24.6 19302464 8080516 pts/9 Sl+ 08:21   6:16 java -Xmx7991m -XX:+UseG1GC -jar /usr/share/zaproxy/zap-2.9.0.jar

Ii started juice-shop 9.3.1 (nodejs 12 and 13)
and
launch zaproxy, add http:127.0.0.1:3000 for automatic scan and click attack button.
![2020-02-13-083710_958x898_scrot](https://user-images.githubusercontent.com/495141/74440620-4cb29e00-4e3c-11ea-87f1-c8a0b12efbcb.png)

the scan starts, soon after the tab switch to alert, then the ui doesn't respond anymore and the zaproxy process is using cpu and filling ram.

here is the zap.log, 
[zap.log](https://github.com/zaproxy/zaproxy/files/4198561/zap.log)

this is the output from the cli.

[zaproxy-console-logs.txt](https://github.com/zaproxy/zaproxy/files/4198568/zaproxy-console-logs.txt)

installed zaproxy form arch package: https://www.archlinux.org/packages/community/any/zaproxy/
638a43377d7efb4c6cdeb5379e1787ad0b7ca05c05bbd1d581738781493c7794  /usr/share/zaproxy/zap-2.9.0.jar

let me know if you need more info.

Thanks

Marc

**Comment by kingthorin** [comment] 2020-02-13 13:46
You could try disabling passive scan tags: https://www.zaproxy.org/docs/desktop/ui/dialogs/options/pscan/ and see if that resolves your issue.

Killing things after 2min doesn't really seem to be representative of an issue but I've also never used arch so perhaps it's misbehaving somehow.

**Comment by thc202** [comment] 2020-02-13 13:47
That looks like #5791, can be confirmed with a thread dump.

**Comment by kingthorin** [comment] 2020-02-13 15:11
Note @mgariepy did confirm via IRC that their issue did seem to be #5791.

**Comment by kingthorin** [comment] 2020-03-02 02:25
Closing. No further response for original requester.

**Closed by kingthorin** 2020-03-02 02:25 UTC
Labels: duplicate
