### ISSUE TITLE
AJAX Spider - Default Allowed Resources Missing

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#7719] opened 2023-02-03 15:39 UTC
### Is your feature request related to a problem? Please describe.

Hi ZAP. 
This is a simple html code that invokes the http request when you click a button using `$.ajax`. But... Spider and Ajax Spider does not seem to detect this.

```html
<html>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <body>
    <button onclick="btnClick()">Login</button>
    <script>
      function btnClick(){
        $.ajax({
            type: "GET",
            contentType: "application/json",
            url: '/alert.js',
            data: JSON.stringify({"id":"1234"}),
            dataType: 'json'
        })
      }
    </script>
  </body>
</html>
```
- Context Scope: `https://pocs.hahwul.com.*`
- Target URL: https://pocs.hahwul.com/logintest.html

![](https://user-images.githubusercontent.com/13212227/216634345-4d14838c-715c-4835-919a-e759b04ec2b6.png)
*Ajax Spider*
![](https://user-images.githubusercontent.com/13212227/216636600-ebe3b9fb-55e3-4cfe-8812-7e79b303dc22.png)
*Spider*

I changed the advanced option of Ajax Spider, but the results are the same 😭
I hope it's detected personally. Is there a good solution?

cc, @pyo-counting

### Describe the solution you'd like

Detects `$.ajax` requests.

### Describe alternatives you've considered

.

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment] 2023-02-03 15:44
Thanks! This is exactly the sort of info we need 😁

**Comment by psiinon** [comment] 2023-02-03 17:57
FYI I'm surprised the AJAX Spider can not cope with this.
It works by launching browsers and clicking on stuff, and it should click on all buttons.
The fact that the button is using a `$.ajax` request shouldnt matter - the browser should handle that.
You can configure it to launch non headless browsers and then you can see what its doing.
I'll try and have a play with this asap...

**Comment by psiinon** [comment] 2023-02-04 09:50
I've just tried this and confirm the AJAX Spider doesnt work with it :(
Why not?
Because for some reason https://code.jquery.com/jquery-3.6.3.min.js is treated as being out of scope :(
When I add that domain to the scope then the AJAX Spider works.
This is a bug - all GET requests for JS files should be trearted as being in scope.

**Comment by psiinon** [comment] 2023-02-04 09:57
This is the code I think _should_ allow all JS / CSS requests: https://github.com/zaproxy/zap-extensions/blob/main/addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderParam.java#L159-L164

**Comment by psiinon** [comment] 2023-02-04 10:00
Arg!
Apparently `^http.*\\.js(?:\\?.*)?$` does not match `https://code.jquery.com/jquery-3.6.3.min.js`, at least not according to the ZAP Search option or the first online RegEx checker I tried...

**Comment by thc202** [comment] 2023-02-04 11:03
I'm not able to reproduce the issue, the button is clicked and the request sent (using Firefox and local server but that shouldn't matter).
![URLs Accessed](https://user-images.githubusercontent.com/4639210/216763391-8cfcc6cb-8f17-4926-9513-0e9b2e172f5e.png)

**Comment by psiinon** [comment] 2023-02-04 11:20
Oh, interesting. 
How about on https://pocs.hahwul.com/logintest.html - that's what I reproduced it on...

**Comment by thc202** [comment] 2023-02-04 11:41
Same result:
![URLs](https://user-images.githubusercontent.com/4639210/216765248-e4d22137-9a77-49b9-b6b0-9fc80a3a4dd6.png)

**Comment by psiinon** [comment] 2023-02-04 13:04
I can reproduce this using the latest weekly and a clean config dir:

1. Start ZAP with a new dir, eg using `./zap.sh -port 9090 -dir ajaxtest`
2. Switch to the AJAX Spider tab
3. Click on "New Scan"
4. Specify a starting Point of "https://pocs.hahwul.com/logintest.html"
5. Start the scan

<img width="976" alt="Screenshot 2023-02-04 at 13 04 19" src="https://user-images.githubusercontent.com/1081115/216769245-91c03026-4396-4c84-a95e-72a38c9a4181.png">

**Comment by psiinon** [comment] 2023-02-04 13:05
Enabling and witching to the Options tab shows the Allowed Resources table is empty.

**Comment by hahwul** [comment] 2023-02-10 06:44
Hello again @psiinon @thc202 
I tested it because I think it was fixed with [23.11.0 release](https://github.com/zaproxy/zap-extensions/releases/tag/spiderAjax-v23.11.0). But it doesn't find to $.ajax endpoint using latest version of Ajax Spider. 

I wonder if this is just my env problem, so.. could you help me?

![](https://user-images.githubusercontent.com/13212227/218021313-205a2bef-238b-46ee-8c70-0c6f9b17478b.png)

**Comment by thc202** [comment] 2023-02-10 06:51
How are you starting ZAP? If you go to Options > AJAX Spider do you see the default Allowed Resources?

**Comment by hahwul** [comment] 2023-02-10 07:06
Oh, I don't see anything. I installed ZAP as a MacOS Installer(`.dmg`) and run it in Applications.

![](https://user-images.githubusercontent.com/13212227/218024058-17e4f29d-1596-4690-a5b5-7f9d504d8814.png)

**Comment by thc202** [comment] 2023-02-10 07:43
I see, your case is different, we'll have to set the defaults to existing homes as well.

**Closed** 2023-02-10 17:24 UTC
Labels: bug, add-on

**Comment by thc202** [comment] 2023-02-23 15:31
@hahwul the latest version of AJAX Spider add-on should address the case you mentioned.

**Comment by hahwul** [comment] 2023-02-24 07:00
@thc202 
I just tested it in the latest version of AjaxSpider and it detects alert.js.

![](https://user-images.githubusercontent.com/13212227/221112446-e7cfaa9e-5979-409f-bb14-a7801642bae1.png)

And now the default allowed resources also have a values.
![](https://user-images.githubusercontent.com/13212227/221112192-ff586756-958d-4e8e-b3ca-346db6bfccf0.png)

It was really nice to learn more about ZAP apart from solving issues! 
Thank you for always giving me motivation :D

**Comment by nitek29** [comment] 2023-03-21 11:05
Hello @thc202  @psiinon 

It seems that "allowed resources" parameter isn't available in the Automation Framework.

- parameters:
    context: "https://myapp.com"
    user: "toto"
    url: "https://myapp.com/"
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 2
    browserId: "firefox"
    maxCrawlStates: 0
    eventWait: 3000
    reloadWait: 3000
    clickDefaultElems: false
    clickElemsOnce: true
    randomInputs: false
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
  
Is this issue known ?

**Comment by psiinon** [comment] 2023-03-21 12:02
@nitek29 that is a known restriction, and one we'd like to have implemented.
Best to comment on https://github.com/zaproxy/zaproxy/issues/6461 rather than this closed issue.
