### ISSUE TITLE
Cannot resize the panel/tab(to more width at left side) "Sites"

### ISSUE THREAD

**Issue by mvmendes** [zaproxy/zaproxy#6198] opened 2020-09-26 00:03 UTC
**Describe the bug**
The Sites tab was not free to resize (in order to increase width of "Sites" panel/tab) 

**To Reproduce**
1. No steps need to reproduce, it's behavior is on main window, when the layout is not setted to "Full Layout" (because Full Layout don't have a panel's bar resizer).

**Expected behavior**
Panels like this was expected to be resizable. It's more confortible to use it with more width in Sites bar, in order to navigate the in the branches of treeview without scrolling every time. 

**Screenshots**
The problem are shown ahead: 
![image](https://user-images.githubusercontent.com/18039308/94324690-4effdd80-ff71-11ea-9b60-286f703f6b66.png)

**Software versions**
OWASP ZAP
Version: 2.9.0
```

Installed Add-ons: [[id=accessControl, version=5.0.0],
[id=alertFilters, version=10.0.0], [id=alertReport,
version=14.0.0], [id=allinonenotes, version=1.0.0], [id=amf,
version=2.0.0], [id=ascanrules, version=36.0.0],
[id=ascanrulesAlpha, version=29.0.0], [id=ascanrulesBeta,
version=31.0.0], [id=attacksurfacedetector, version=1.1.4],
[id=authstats, version=1.0.0], [id=beanshell,
version=6.0.0], [id=browserView, version=5.0.0],
[id=bruteforce, version=9.0.0], [id=cmss, version=2.0.0],
[id=commonlib, version=1.1.0], [id=communityScripts,
version=9.0.0], [id=coreLang, version=13.0.0],
[id=cspscanner, version=6.0.0], [id=custompayloads,
version=0.9.0], [id=customreport, version=5.0.0], [id=diff,
version=10.0.0], [id=directorylistv1, version=4.0.0],
[id=directorylistv2_3, version=3.0.0],
[id=directorylistv2_3_lc, version=3.0.0], [id=domxss,
version=9.0.0], [id=encoder, version=0.3.0],
[id=exportreport, version=6.0.0], [id=formhandler,
version=2.0.0], [id=fuzz, version=13.0.1], [id=fuzzdb,
version=7.0.0], [id=fuzzdboffensive, version=3.0.0],
[id=gettingStarted, version=11.0.0], [id=graphql,
version=0.1.0], [id=help, version=10.0.0], [id=help_pt_BR,
version=10.0.0], [id=highlighter, version=7.0.0],
[id=httpsInfo, version=12.0.0], [id=hud, version=0.11.0],
[id=imagelocationscanner, version=2.0.0], [id=importurls,
version=7.0.0], [id=invoke, version=10.0.0], [id=jruby,
version=6.0.0], [id=jsonview, version=1.0.0], [id=jwt,
version=1.0.0], [id=jxbrowser, version=13.0.0],
[id=jxbrowserwindows, version=11.0.0], [id=jython,
version=10.0.0], [id=onlineMenu, version=7.0.0],
[id=openapi, version=16.0.0], [id=plugnhack,
version=11.0.0], [id=portscan, version=8.0.0],
[id=pscanrules, version=29.0.0], [id=pscanrulesAlpha,
version=28.0.0], [id=pscanrulesBeta, version=22.0.0],
[id=quickstart, version=28.0.0], [id=reflect,
version=0.0.8], [id=regextester, version=1.0.0],
[id=replacer, version=8.0.0], [id=requester, version=4.0.0],
[id=retire, version=0.4.0], [id=reveal, version=3.0.0],
[id=revisit, version=3.0.0], [id=saml, version=8.0.0],
[id=saverawmessage, version=5.0.0], [id=savexmlmessage,
version=0.1.0], [id=scripts, version=26.0.0], [id=selenium,
version=15.2.0], [id=sequence, version=5.0.0], [id=soap,
version=3.0.0], [id=spiderAjax, version=23.1.0],
[id=sqliplugin, version=13.0.0], [id=sse, version=9.0.0],
[id=svndigger, version=3.0.0], [id=tips, version=7.0.0],
[id=tlsdebug, version=3.0.0], [id=tokengen, version=13.0.0],
[id=treetools, version=7.0.0], [id=viewstate,
version=2.0.0], [id=vulncheck, version=1.0.0],
[id=webdriverwindows, version=20.0.0], [id=websocket,
version=22.0.0], [id=zest, version=32.0.0]]

Operating System: Windows 10
Java Version: Oracle Corporation 11.0.8
System''s Locale: pt_BR
Display Locale: pt_BR
Format Locale: pt_BR
ZAP Home Directory: C:\Users\[USER NAME]\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
Look and Feel: Nimbus (javax.swing.plaf.nimbus.NimbusLookAndFeel)
 
```
**Errors from the zap.log file**
Not applicable

**Additional context**
Not applicable

**Would you like to help fix this issue?**
Unfortunately, I don't have Desktop Java Skills to do it in a reasonable time.

**Comment by thc202** [comment] 2020-09-26 10:49
Could you close the Requester tab and try resize again? Might be the same as #3961.

**Comment by mvmendes** [comment] 2020-09-26 16:11
Ow, it's really weird but worked. I see it like a workaround, but when I close the Requester tab, the constraint was released.

Thank you for this!

**Comment by thc202** [comment] 2020-09-29 10:06
Thanks for letting us know. Closing as duplicate of #3961.

**Closed by thc202** 2020-09-29 10:06 UTC
Labels: bug
