### ISSUE TITLE
Illegal reflective access by org.hsqldb.persist.RAFileNIO

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#5442] opened 2019-06-25 13:46 UTC
after update due to https://github.com/zaproxy/zaproxy/issues/5440 , I started seeing the followign in the Jenkins console:

**Describe the bug**
16:39:50 710365 [ZAP-Shutdown] INFO hsqldb.db..ENGINE  - dataFileCache commit start
16:39:51 711402 [ZAP-Shutdown] INFO hsqldb.db..ENGINE  - dataFileCache commit end
16:39:51 WARNING: An illegal reflective access operation has occurred
16:39:51 WARNING: Illegal reflective access by org.hsqldb.persist.RAFileNIO (file:/C:/Program%20Files/OWASP/Zed%20Attack%20Proxy/lib/hsqldb-2.3.4.jar) to method java.nio.DirectByteBuffer.cleaner()
16:39:51 WARNING: Please consider reporting this to the maintainers of org.hsqldb.persist.RAFileNIO
16:39:51 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
16:39:51 WARNING: All illegal access operations will be denied in a future release

**Software versions**
Official OWASP ZAP Jenkins Plugin - 1.1.0
ZAP D-2019-05-28

**Comment by kingthorin** [comment] 2019-06-25 13:51
What version of Java?

Seems related to or duplicate of: https://github.com/zaproxy/zaproxy/issues/5359

**Comment by thc202** [comment] 2019-06-25 14:06
Most likely Java 11.

Note that's just a warning, ZAP will work fine. We'll have to update the library to newer version.

**Comment by hnestorova** [comment] 2019-06-25 14:08
its open jdk-11.0.2

**Comment by kingthorin** [comment] 2019-06-25 14:27
According to: https://sourceforge.net/p/hsqldb/bugs/1526/ this is fixed in hsqldb 2.5.0

**Closed** 2019-10-22 20:04 UTC
Labels: Type-Task, third-party
