### ISSUE TITLE
EXP/AVI.Agent.oqcog found by nordvpn malware scanner

### ISSUE THREAD

**Issue by hedgehogdrfrink** [zaproxy/zaproxy#8703] opened 2024-11-12 02:42 UTC
### Describe the bug:

downloaded the zapproxy dmg image for intel from the website and nordvpn auto deleted it saying it contains EXP/AVI.Agent.oqcog, Wanted to understand if this is expected behavior as well as what EXP/AVI.Agent.oqcog is?

I didn't see any previous or open issues with EXP/AVI.Agent.oqcog when I ran a search.

### Steps to reproduce the behavior:

use nordvpn for mac,
download the zapproxy dmg for intel installer.

### Expected behavior:

Be able to download the zapproxy dmg without any malware triggers.

### Software versions:

2.15.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment] 2024-11-12 02:47
There's a FAQ for that: https://www.zaproxy.org/faq/why-does-my-antivirus-tool-flag-zap/

**Comment by psiinon** [comment] 2024-11-12 09:29
@hedgehogdrfrink do you have a contact at nordvpn? It will probably be much easier for you to talk to them than for us, as we dont have a contract with them..

**Comment by hedgehogdrfrink** [comment] 2024-11-13 01:01
Thanks for the heads up, I emailed support about this, will keep this updated with progress.

**Comment by Deilis** [comment] 2024-11-18 09:35
Hey guys, Threat Intelligence Research team representative here.

We will remove FPs shortly, given that ZAP itself performs security testing and can simulate attacks, our ML model predicted it was a potential threat, and we saw it being used in TA / APT campaigns recently. No worries, everything is fine, update will be done today, or tomorrow!

**Comment by kingthorin** [comment] 2024-11-18 09:38
@Deilis is there anything we should be doing to ensure new releases aren't the source of false positives?

**Comment by psiinon** [comment] 2024-11-18 09:42
@Deilis thanks for joining and for the update - great news!

**Comment by Deilis** [comment] 2024-11-18 10:04
**Quick update:**
The issue was initially directed to our support team, so it may take some time to reach us directly. Ideally, if you encounter any additional false positives, please send them directly to me at _deividas.lis@nordsec.com_. I’ll make it a priority to address them swiftly, especially since this tool is widely used.

**Regarding the cause of false positives:**
The detection was triggered due to the resemblance to MITRE ATT&CK techniques, including T1059, T1064, TA0003, T1546, T1497, TA0011, T1071, T1573, TA0007, T1082, and T1518.
In summary, it was flagged because of similarities with typical TTPs (Tactics, Techniques, and Procedures) seen in both legitimate security tools performing scans, configuration changes, and sandbox detections, as well as in scenarios where threat actors or advanced persistent threats obfuscate files or engage in malicious activities within the system.

**Comment by psiinon** [comment] 2024-11-18 10:10
@Deilis thank you for the direct contact details - we'll use that going forwards!

**Comment by thc202** [comment] 2024-11-26 15:50
Closing as this seems to have been handled already.

**Closed by thc202** 2024-11-26 15:50 UTC
Labels: question
