### ISSUE TITLE
Timestamp Disclosure shouldn't flag the current useragent

### ISSUE THREAD

**Issue by jsoref** [zaproxy/zaproxy#7422] opened 2022-08-15 22:15 UTC
### Describe the bug

A web server responds w/ the current user's user agent.

Passive (10096 - Timestamp Disclosure)

Complains that `20100101` from:

```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
```

Which the user-agent sent to the web server in the first place is "information disclosure"

### Steps to reproduce the behavior

1. Run https://github.com/GarnerCorp/nginx-debugging-backend/blob/main/debug.py (you can build a docker image if you like
2. Point the information disclosure test at the service

### Expected behavior

The information disclosure tool should exclude values from fields that are *sent* when it considers whether something is being "disclosed"

### Software versions

2.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/2119212/184727494-42b6c1e1-6c02-4bbc-b2d9-3b357be71668.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2022-08-15 23:45
If you're only concerned with Timestamps +/- 1 year then you can set it to High threshold.
https://www.zaproxy.org/docs/desktop/addons/passive-scan-rules/#timestamp-disclosure

We could (perhaps should) identify a set of headers to be ignored.

**Comment by thc202** [comment] 2022-08-16 05:54
Closing as duplicate of #6741.

**Closed by thc202** 2022-08-16 05:54 UTC
Labels: duplicate, add-on

**Comment by jsoref** [comment] 2022-08-16 18:31
No, the web server actively returns request headers in the response body. But the user-agent that's provided by the user is not confidential and it isn't disclosure of any internals of the application.

**Comment by kingthorin** [comment] 2022-08-16 18:33
Okay, that makes sense.
