### ISSUE TITLE
Breakpoints: Only break on messages in scope not working

### ISSUE THREAD

**Issue by cybernova** [zaproxy/zaproxy#6717] opened 2021-07-31 07:35 UTC
**Describe the bug**

I've a list with URLs in scope, going to Options -> Breakpoints -> selecting "Only break on messages in scope" and then clicking OK, when I set a breakpoint, ZAP break on requests not in scope.

Opening again Options -> Breakpoints, "Only break on messages in scope" is not selected.

**To Reproduce**
See above.

**Expected behavior**
ZAP should break requests/response only URLs in scope when "Only break messages in scope" option is selected.

**Screenshots**
![Screenshot_2021-07-31_09-24-25](https://user-images.githubusercontent.com/5947674/127732564-de27d561-280d-4fb2-bcca-eea91f9a3cd8.png)

**Software versions**
 - ZAP: 2.10.0
 - OS: Kali Linux

**Errors from the zap.log file**
No error is shown in the log file.

**Would you like to help fix this issue?**
Yes

**Comment by thc202** [comment] 2021-07-31 08:50
Closing as duplicate of #6437. This should be fixed in the weekly releases.

**Closed by thc202** 2021-07-31 08:50 UTC
Labels: bug
