### ISSUE TITLE
Zaproxy not intercepting traffic from anbox

### ISSUE THREAD

**Issue by njmulsqb** [zaproxy/zaproxy#7373] opened 2022-06-29 14:49 UTC
### Describe the bug

I am trying to listen to apk installed in anbox using zaproxy, but its not intercepting the traffic. Same thing tried with burp works, burp intercepts the request successfuly and zap isn't

### Steps to reproduce the behavior

1. Install anbox and add any apk in it
2. Configure global proxy for adb
3. Go to zap and add 0.0.0.0 in local proxies
4. enable the breakpoint to fetch the request

### Expected behavior

ZAP should intercept the traffic

### Software versions

2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2022-06-29 15:47
Are there errors or is ZAP just not seeing the traffic?

If it's just not seeing traffic then the problem is how your routing/sending the traffic to ZAP.

**Comment by kingthorin** [comment] 2022-06-29 15:48
> Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch

**Comment by njmulsqb** [comment] 2022-06-29 16:33
Hi @kingthorin 

There are apparently no errors on ZAP GUI.
With same configuration, burp is catching the traffic so I dont think so there is any issue with sending traffic

Here's the version information
```
OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=46.0.0], [id=automation,
version=0.16.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.3.0], [id=commonlib, version=1.9.0],
[id=diff, version=11.0.0], [id=directorylistv1,
version=5.0.0], [id=domxss, version=12.0.0], [id=encoder,
version=0.6.0], [id=exim, version=0.1.0], [id=formhandler,
version=4.0.0], [id=fuzz, version=13.6.0],
[id=gettingStarted, version=13.0.0], [id=graaljs,
version=0.2.0], [id=graphql, version=0.9.0], [id=help,
version=14.0.0], [id=hud, version=0.13.0], [id=importurls,
version=9.0.0], [id=invoke, version=11.0.0], [id=network,
version=0.2.0], [id=oast, version=0.10.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=27.0.0],
[id=pscanrules, version=41.0.0], [id=quickstart,
version=33.0.0], [id=replacer, version=9.0.0], [id=reports,
version=0.14.0], [id=retest, version=0.2.0], [id=retire,
version=0.12.0], [id=reveal, version=4.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=30.0.0], [id=selenium,
version=15.9.0], [id=soap, version=13.0.0], [id=spiderAjax,
version=23.7.0], [id=tips, version=9.0.0],
[id=webdriverwindows, version=40.0.0], [id=websocket,
version=26.0.0], [id=zest, version=35.0.0]]
---
Operating System: Windows 10
Java Version: Oracle Corporation 11.0.14
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
ZAP Home Directory: C:\Users\Ain\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

```

**Comment by kingthorin** [comment] 2022-06-29 17:06
Fire up Wireshark and see if the traffic is arriving.

**Comment by njmulsqb** [comment] 2022-06-29 17:10
![image](https://user-images.githubusercontent.com/47940898/176496025-08d73b0a-8aef-41f3-ad0c-4e1feb3a5192.png)
Yes, it is

**Comment by kingthorin** [comment] 2022-06-29 17:14
If you manually connect to 192.168.250.1:8081 from another system on the network same what do you get? (Or even better the device/emulator you're using. [Or both])

Anything interesting in zap.log? https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by njmulsqb** [comment] 2022-06-29 17:44
I think, its already added. Isn't it?
![image](https://user-images.githubusercontent.com/47940898/176501878-94e63df7-7265-4ec8-88f5-076b44f7ab57.png)

**Comment by njmulsqb** [comment] 2022-06-29 17:51
![image](https://user-images.githubusercontent.com/47940898/176503032-6d861f0d-b546-483a-a8d2-e6428b852c94.png)
No, it didnt help

**Comment by kingthorin** [comment] 2022-06-29 18:04
Are you sure you got the right IP, etc because your log seems to suggest you're listening on 8080 and the client is .45:
`2022-06-28 22:38:50,122 [ZAP-ProxyThread-12] WARN  API - Request to API URL http://192.168.18.45:8080/ from 192.168.18.45 not permitted`

**Comment by njmulsqb** [comment] 2022-06-29 18:06
> Are you sure you got the right IP, etc because your log seems to suggest you're listening on 8080 and the client is .45: `2022-06-28 22:38:50,122 [ZAP-ProxyThread-12] WARN API - Request to API URL http://192.168.18.45:8080/ from 192.168.18.45 not permitted`

Thats from yesterday, 8080 was by default then I tried changing it to 8081 to see if it works but it didnt

**Comment by kingthorin** [comment] 2022-06-29 18:07
Another idea, when you specified 0.0.0.0 are you sure it bound to whatever LAN interface you were expecting? 0.0.0.0 should be 'all interfaces' however if there was already something listening on the particular port then it may have quietly failed (since loopback would likely still work). Or is there a FW or something else in the way.

**Comment by njmulsqb** [comment] 2022-06-29 18:08
> Another idea, when you specified 0.0.0.0 are you sure it bound to whatever LAN interface you were expecting? 0.0.0.0 should be 'all interfaces' however if there was already something listening on the particular port then it may have quietly failed (since loopback would likely still work). Or is there a local software FW or something else in the way?

Now, I am not listening on 0.0.0.0, I have specified the exact IP. Also, burp is listening quite well on the same interface.

**Comment by njmulsqb** [comment] 2022-06-29 18:16
What else can I help you with now?

**Comment by kingthorin** [comment] 2022-06-29 18:48
Fire up another normal VM on the same network and configure a browser to proxy through ZAP (on the original system).

If that works the issue is your emulator or routing. If it doesn't then it still leaves a ton of questions:
- Host FW
- ZAP blocking due to a config we've missed
- etc

🤷‍♂️

**Comment by njmulsqb** [comment] 2022-06-30 17:41
> [#7373 (comment)](https://github.com/zaproxy/zaproxy/issues/7373#issuecomment-1170301188) The 3 dots in the 3rd address look suspicious.

![image](https://user-images.githubusercontent.com/47940898/176742518-7e3aefa8-c5d4-4c0d-aac5-69cf26fd787e.png)
Ok now?

**Comment by kingthorin** [comment] 2022-06-30 18:18
It should just be an address (or regex): that of the allowed client(s). [Not the proxy server.]

**Comment by thc202** [comment] 2022-07-10 06:26
Closing, no further info.

**Closed by thc202** 2022-07-10 06:26 UTC
