### ISSUE TITLE
HTTPS: using incorrect handshake protocol on cached connections

### ISSUE THREAD

**Issue by pmccabe1** [zaproxy/zaproxy#2250] opened 2016-02-19 11:52 UTC
ZAP 2.4.3 on Win7
**Situation**
Request file over https from an apache webserver using Firefox, firefox proxy points to ZAP on the localhost.
First https request succeeds, second fails with Bad Gateway.

Tracing the requests with wireshark the first request is properly processed (TLSv1 is the protocol).
The second request is then sent with protocol type of SSL (which is being refused or ignored by the server).

![wireshark trace](https://cloud.githubusercontent.com/assets/17335676/13174915/184225ba-d707-11e5-8ff1-958139edc268.png)
![wireshark trace-2](https://cloud.githubusercontent.com/assets/17335676/13174919/1e6043d2-d707-11e5-92a9-177e717615f0.png)

Here is the last entry from the SSL Debug log from ZAP

```
%% Client cached [Session-3, TLS_RSA_WITH_AES_128_CBC_SHA]
%% Try resuming [Session-3, TLS_RSA_WITH_AES_128_CBC_SHA] from port 59128
*** ClientHello, TLSv1
RandomCookie:  GMT: 1439037917 bytes = { 205, 192, 95, 229, 254, 30, 249, 3, 220, 9, 167, 201, 42, 134, 249, 100, 59, 111, 139, 36, 29, 173, 233, 207, 34, 197, 108, 38 }
Session ID:  {194, 151, 59, 28, 11, 210, 253, 110, 27, 70, 114, 55, 83, 15, 37, 201, 114, 248, 62, 68, 157, 49, 100, 160, 219, 58, 51, 227, 203, 84, 56, 136}
Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_SHA, TLS_ECDH_ECDSA_WITH_RC4_128_SHA, TLS_ECDH_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_ECDH_anon_WITH_AES_128_CBC_SHA, TLS_DH_anon_WITH_AES_128_CBC_SHA, TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA, SSL_DH_anon_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_anon_WITH_RC4_128_SHA, SSL_DH_anon_WITH_RC4_128_MD5, SSL_RSA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, SSL_DH_anon_WITH_DES_CBC_SHA, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA, SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_DH_anon_EXPORT_WITH_RC4_40_MD5, TLS_ECDHE_ECDSA_WITH_NULL_SHA, TLS_ECDHE_RSA_WITH_NULL_SHA, SSL_RSA_WITH_NULL_SHA, TLS_ECDH_ECDSA_WITH_NULL_SHA, TLS_ECDH_RSA_WITH_NULL_SHA, TLS_ECDH_anon_WITH_NULL_SHA, SSL_RSA_WITH_NULL_MD5, TLS_KRB5_WITH_3DES_EDE_CBC_SHA, TLS_KRB5_WITH_3DES_EDE_CBC_MD5, TLS_KRB5_WITH_RC4_128_SHA, TLS_KRB5_WITH_RC4_128_MD5, TLS_KRB5_WITH_DES_CBC_SHA, TLS_KRB5_WITH_DES_CBC_MD5, TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA, TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5, TLS_KRB5_EXPORT_WITH_RC4_40_SHA, TLS_KRB5_EXPORT_WITH_RC4_40_MD5]
Compression Methods:  { 0 }
Extension elliptic_curves, curve names: {secp256r1, sect163k1, sect163r2, secp192r1, secp224r1, sect233k1, sect233r1, sect283k1, sect283r1, secp384r1, sect409k1, sect409r1, secp521r1, sect571k1, sect571r1, secp160k1, secp160r1, secp160r2, sect163r1, secp192k1, sect193r1, sect193r2, secp224k1, sect239k1, secp256k1}
Extension ec_point_formats, formats: [uncompressed]
Extension server_name, server_name: [type=host_name (0), value=XXXXXXXXXXX]
***
ZAP-ProxyThread-3, WRITE: TLSv1 Handshake, length = 276
60288 [Thread-12] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
60681 [Thread-12] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Database closed
60799 [Thread-12] INFO org.parosproxy.paros.control.Control  - OWASP ZAP 2.4.3 terminated.
```

**Comment by pmccabe1** [comment] 2016-02-19 15:34
With a quick debug session I have narrowed the problem to SSLConnector.createSocket

With the following nasty hack it seemingly solves the problem - 

`			try {
//				SSLSocket sslSocket = (SSLSocket) clientSSLSockFactory.createSocket(host, port, localAddress, localPort);
//				sslSocket.startHandshake();
				Socket socket = clientSSLSockFactory.createSocket();
				SocketAddress localAddr = new InetSocketAddress(localAddress, localPort);
				socket.bind(localAddr);
				SocketAddress remoteAddr = new InetSocketAddress(host, port);
				socket.connect(remoteAddr);

				return socket;
			} catch (SSLException e) {
				if (!e.getMessage().contains(CONTENTS_UNRECOGNIZED_NAME_EXCEPTION)) {
					throw e;
`

**Comment by thc202** [comment] 2016-02-19 16:34
What Java version are you using?

Any info/log on server side on why the connection is rejected/dropped?

**Comment by pmccabe1** [comment] 2016-02-19 18:10
Java 1.8.45

The server side is actually a bit more complex - there is an F5 load
balancer in front of the webserver which kills the connection before it
gets further.  The admin for that won't be around until Monday, I will try
see if the log dumps from that have anything useful

What Java version are you using?

Any info/log on server side on why the connection is rejected/dropped?

—
Reply to this email directly or view it on GitHub
<https://github.com/zaproxy/zaproxy/issues/2250#issuecomment-186290183>.

**Comment by kingthorin** [comment] 2016-03-02 02:38
@pmccabe1 any update?

**Comment by kingthorin** [comment] 2016-03-20 23:50
This issue will be closed on or just after 20160407 if nothing further is received.

**Comment by pmccabe1** [comment] 2016-03-31 12:42
No updates - LoadBalancer admin looked at logs but mentioned that F5 will just throw away any abnormal packet - the effort to adjust the logs would take too much of his time.  But it is clear that the handshake is not correct.

But as I am possibly the only one being affected the issue can be closed/stalled - as I have built my work around as mentioned above.

**Comment by kingthorin** [comment] 2016-03-31 14:40
I've just tried this against a F5 device (granted there are a bunch of config differences that could be in play), but do not see this behavior.

Initially I had SSLv3, TLS1, TLS1.1, and TLS1.2 enabled in ZAP and saw only TLS1.2 traffic. I think disabled everything but SSLv3 and TLS1 and saw only TLS1 traffic.

Without the ability to recreate this I don't think there's anything we can do to troubleshoot further.

**Comment by thc202** [comment] 2016-04-01 08:49
It might well be caused by a bug in JRE's SSL/TLS implementation...

**Comment by kingthorin** [comment] 2016-05-03 22:12
Closing - InsufficientEvidence

**Closed** 2016-06-27 10:15 UTC
Labels: InsufficientEvidence
