### ISSUE TITLE
Upstream proxy seems to automatically assume https

### ISSUE THREAD

**Issue by GunoH** [zaproxy/zaproxy#7891] opened 2023-06-05 05:57 UTC
### Describe the bug

I'm trying to run ZAP behind a corporate proxy that is accessible over http only (not over https). After configuring said proxy without scheme (so I only supplied its IP and port number) in Network | Connection | HTTP Proxy and checking for updates,  the debug logging shows that ZAP is trying to use the proxy over https:
<pre>
2023-06-04 21:12:22,573 [ZAP-cfu] DEBUG ConnectExec - ex-0000000006 acquiring connection with route {tls}->https://&lt;proxy-host>:3128->https://cfu.zaproxy.org:443
</pre>

As a result, I'm presented with the stacktrace pasted in this issue and the update check fails.

It looks like ZAP automatically assumes that the proxy is accessible over https, which it is not in my case.
Please allow me to specify the proxy's scheme as well.

Thanks!

### Steps to reproduce the behavior

1. Configure ip and port of the proxy in Network | Connection | HTTP Proxy.
2. Help | Check for Updates...

### Expected behavior

I am able to use an upstream proxy over http.

### Software versions

OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=14.0.0],
[id=ascanrules, version=49.0.0], [id=automation,
version=0.19.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.5.0], [id=commonlib,
version=1.11.0], [id=coreLang, version=15.0.0],
[id=custompayloads, version=0.11.0], [id=database,
version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=14.0.0], [id=encoder, version=0.7.0], [id=exim,
version=0.3.0], [id=formhandler, version=6.1.0], [id=fuzz,
version=13.8.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.11.0],
[id=help, version=15.0.0], [id=hud, version=0.15.0],
[id=importurls, version=9.0.0], [id=invoke, version=12.0.0],
[id=jxbrowser, version=13.0.0], [id=jxbrowserlinux64,
version=11.0.0], [id=network, version=0.3.0], [id=oast,
version=0.13.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=29.0.0], [id=plugnhack,
version=12.0.0], [id=pscanrules, version=44.0.0],
[id=quickstart, version=35.0.0], [id=replacer,
version=11.0.0], [id=reports, version=0.16.0],
[id=requester, version=7.0.0], [id=retest, version=0.4.0],
[id=retire, version=0.16.0], [id=reveal, version=5.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=soap, version=15.0.0], [id=spider,
version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips,
version=10.0.0], [id=webdriverlinux, version=46.0.0],
[id=websocket, version=27.0.0], [id=zest, version=37.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 17.0.6
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/&lt;username>/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Errors from the zap.log file

<pre>
2023-06-04 21:12:22,783 [ZAP-cfu] ERROR ExtensionCallHome - Unsupported or unrecognized SSL message
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:303) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275) ~[?:?]
        at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:251) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.SslConnectionSocketFactory.connectSocket(SslConnectionSocketFactory.java:195) ~[?:?]
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181) ~[?:?]
        at org.apache.hc.client5.http.impl.io.ZapHttpClientConnectionOperator.connect(ZapHttpClientConnectionOperator.java:95) ~[?:?]
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:433) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:159) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:169) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:146) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:158) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245) ~[?:?]
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:394) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:297) ~[?:?]
        at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:103) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:298) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:266) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:222) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:193) ~[?:?]
        at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:57) ~[?:?]
        at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:478) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:211) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.getServiceData(ExtensionCallHome.java:230) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.getCheckForUpdatesData(ExtensionCallHome.java:239) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.get(ExtensionCallHome.java:249) ~[?:?]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getRemoteConfiguration(ExtensionAutoUpdate.java:991) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$4.run(ExtensionAutoUpdate.java:1119) ~[zap-2.12.0.jar:2.12.0]
</pre>

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2023-06-05 06:04
Duplicate of #7594, fix released in version 0.6.0 of Network add-on.

**Closed by thc202** 2023-06-05 06:04 UTC
Labels: bug, duplicate, add-on, in:network
