### ISSUE TITLE
OpenAPI definitions with warnings not importing from file since v20

### ISSUE THREAD

**Issue by MilyMilo** [zaproxy/zaproxy#6758] opened 2021-08-17 08:47 UTC
**Describe the bug**
Starting with version 20.0 of the OpenAPI add-on my definitions fail to load. The definitions are mostly correct and can be validated using [Swagger Editor](https://editor.swagger.io). This only happens when loading from file - URL import appears to be working as expected.

Example file that fails to load: https://gist.github.com/MilyMilo/ecbc9deec68c72a1e7462d575102453f

**To Reproduce**
Steps to reproduce the behaviour:
1. Update OpenAPI extension to version v20
2. Try to load attached OpenAPI from file using the API
3. See multiple errors, no urls are loaded to zap
4. Try to load the same OpenAPI from raw url (https://gist.githubusercontent.com/MilyMilo/ecbc9deec68c72a1e7462d575102453f/raw/36118b6a07de6bf03e0ee0a6d0741c95c1f8a693/cinder-v3.openapi.json)
5. Some errors appear, but there are not nearly as many and URLs are loaded.

**Expected behavior**
I expect the OpenAPI file to load correctly from file as it does from the url.

**Screenshots**
Definitions loaded from file:
![image](https://user-images.githubusercontent.com/24303006/129693031-18bf1882-6899-4e59-aecb-422f7d6c8bf8.png)
(and goes on)

Definitions loaded from URL:
![image](https://user-images.githubusercontent.com/24303006/129692895-6c7a8176-25c1-4f35-aeb5-7b00a7927fe0.png)

**Software versions**
 - ZAP: 2.10.0
 - Add-on: OpenAPI v20
 - OS: OS X Big Sur + Alpine Linux (Docker)
 - Java: openjdk 14.0.2 + openjdk version 1.8.0_282
 - Browser: Chromium: 92.0.4515.131

**Errors from the zap.log file**
OpenAPI errors (as txt because github won't accept json)
[import.txt](https://github.com/zaproxy/zaproxy/files/6998434/import.txt)

**Additional context**
Most actions were performed using the api via python wrapper.

**Would you like to help fix this issue?**
I can't really help with java.

**Comment by kingthorin** [comment] 2021-08-17 10:44
>  The definitions are mostly correct

That’s encouraging 🤪

**Comment by MilyMilo** [comment] 2021-08-17 11:31
Well, having worked with openapi for some time now I don't recall many definitions without any schema warnings 😄 .

**Comment by davewichers** [comment] 2021-08-20 22:16
I am able to load openapi definitions just fine with the same version of the openapi plugin. As such, I suspect there is either a problem with your openapi file OR there is something in it that the openapi plugin doesn't like, and that's the problem. Not that NO openapi specs can be loaded at all. I'd just you figure out WHAT in the file is causing the problem, add that info to this ticket, and change the name to reflect the cause.

**Comment by kingthorin** [comment] 2021-08-20 23:35
💯

**Comment by Gumili** [comment] 2021-08-23 06:25
Hi,

It seems I have a similar issue with files generated using quarkus.
Everything was working fine, until the plugin update on 5th of August.

I'll look into my openapi files trying to find the cause, but I am just letting you know that there might be more people affected by it 😄

**Comment by thc202** [comment] 2021-08-23 07:58
The cause is known (the title of the issue was updated accordingly). If your definition causes warnings it will not be imported.

**Comment by MilyMilo** [comment] 2021-08-23 08:30
I disagree, that's not the *cause* - definitions are loaded correctly from URL. 

This week I'll be looking into what in the OpenAPI file might be causing this, however patching specific openapi files is not the long term solution. Definitions will have warnings, especially given the fact that ZAP seems to find many more than Swagger Editor itself. Completely failing the loading for the entire openapi is undesirable in my opinion, if we could instead load 99 of 100 definitions (like I believe it works in v19).

**Comment by Gumili** [comment] 2021-08-23 09:11
@thc202 Yeah, but what changed between v19 and v20 that changed this behavior? And if there is such change I think it would be nice to give users a heads-up 😉 

@MilyMilo Are you sure providing remote URL works? In my case, it just finds two URLs: base_url and base_url/openapi_filename, so the file is not parsed/rejected.

**Comment by MilyMilo** [comment] 2021-08-23 09:22
@Gumili In my case, remote URL is working correctly.

**Comment by Gumili** [comment] 2021-08-23 09:31
It looks like in my case, there is a problem with`license.info.url` field -- it's not a proper URL starting with `http://`.
But I still don't understand why it wasn't a problem in v19.

**Comment by thc202** [comment] 2021-08-23 09:48
This is a bug, it will be fixed shortly.

**Closed** 2021-08-23 15:33 UTC
Labels: bug, add-on
