### ISSUE TITLE
Jenkins + ZAProxy Report not generated in daemon mode

### ISSUE THREAD

**Issue by qaDream77** [zaproxy/zaproxy#1859] opened 2015-08-28 17:46 UTC
I read that this is a bug, is it isolated to 2.4.1 or is there a stable build that does not have this issue?

Cheers.

**Comment by kingthorin** [comment] 2015-08-28 19:51
Closing as duplicate of #1792 

Fixed in latest weekly: https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Closed by kingthorin** 2015-08-28 19:51 UTC

**Comment by qaDream77** [comment] 2015-08-28 20:00
Not to be rude but i updated Zap today and have this issue currently, unless this was something that got updated within the last couple hours. :(

**Comment by kingthorin** [comment] 2015-08-28 23:18
You need a weekly build to get the fix, or to wait for 2.4.2
