### ISSUE TITLE
unable to load zap on latest ubuntu

### ISSUE THREAD

**Issue by wifiuk** [zaproxy/zaproxy#3761] opened 2017-07-17 18:10 UTC
Get the error
Exiting: ZAP requires a minimum of Java 7 to run, found 9-Ubuntu.

I see no option to install java 7.

Tried to install openjdk-8 and still get the same error.

openjdk-8-jre is already the newest version (8u131-b11-0ubuntu1.17.04.1).
xxx@Ubuntu:~/Downloads$ sudo apt-get install openjdk-8-jdk
openjdk-8-jdk is already the newest version (8u131-b11-0ubuntu1.17.04.1).

Any thoughts?

**Comment by thc202** [comment] 2017-07-17 18:23
Replace `zap.sh` script with this one:
https://github.com/zaproxy/zaproxy/blob/33383028196d5fc45edab764e394e47935e3aa6d/src/zap.sh

Or, change default Java version to 8.

Closing as duplicate of #2602.

**Closed by thc202** 2017-07-17 18:23 UTC

**Comment by wifiuk** [comment] 2017-07-17 18:27
when running the new zap.sh i get the following error


Found Java version 9-Ubuntu
Available memory: 3624 MB
Setting jvm heap size: -Xmx906m
Error: Unable to access jarfile /usr/local/bin/zap-dev.jar

**Comment by thc202** [comment] 2017-07-17 18:30
Sorry, I forgot that, you need to update the JAR name (line 111) to match the name of the version that you are using (`zap-2.6.0.jar`?).

btw, depending on the Java 9 version being used you might end up with #3757. If so, the only workaround is to use Java 8.

**Comment by venkatsubrahmanyam6119** [comment] 2019-12-24 06:57
> Sorry, I forgot that, you need to update the JAR name (line 111) to match the name of the version that you are using (`zap-2.6.0.jar`?).
> 
> btw, depending on the Java 9 version being used you might end up with #3757. If so, the only workaround is to use Java 8.


I have changed the 111 line code as mentioned but my file is running elsewhere and not at the 'pwd' I gave in the file.

**Comment by thc202** [comment] 2019-12-30 16:46
That's most likely unrelated to this issue, could you post the question/details in https://groups.google.com/group/zaproxy-users ?
