### ISSUE TITLE
Why does zaproxy load an existing session take a very long time?

### ISSUE THREAD

**Issue by dm116** [zaproxy/zaproxy#6964] opened 2021-12-10 10:34 UTC
**Describe the bug**
Why does zaproxy load an existing session take a very long time?

**To Reproduce**
1. Runing zaproxy on the terminal
2. Open a exist session.

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP:  zap-2.11.0
 - OS: FreeBSD 13.0
 - Java: openjdk version "1.8.0_302"

**Comment by thc202** [comment] 2022-01-18 08:15
Closing, duplicate of #1364.

**Closed by thc202** 2022-01-18 08:15 UTC
Labels: bug, duplicate
