### ISSUE TITLE
Does active scanning take time to start?

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1943] opened 2015-09-30 05:56 UTC
I am performing spidering and active scanning on a url. Before starting the active scan, once spidering reaches 100 i am stopping the spidering and then initiating the active scan. But whenever I do a fresh session of zap active scanning fails. But when i retry again , it goes on fine. So is there some lag for active scanning. If yes how to overcome it.
Below is my code

``
#Function 1 -> starts spidering
spider = @zap.spider			
 spider.start			
#Continue spidering until status = 100
while spider.status != 100
    #do nothing
end
if spider.status == 100
    #Stop spidering 
     spider.stop
      message = "Completed Spidering #{@target} - PASS"
else
     message = 'Spidering not Completed - FAIL'
end
p spider.status
p spider.running?

Function2 -> starting active scan
ascan = @zap.ascan
p '1'
  ascan.start
p '2'
sleep (10)
p ascan.running?
p ascan.status
#Continue active scanning until status=100
while ascan.running?
	#continue running	
end
if ascan.status == 100
   #Stop active scanning
   stop_active_scanning()
  message = 'Completed Active Scanning - PASS'
else
  message = 'Active Scan not Completed - FAIL'
end
=========================================
```
The output is as below
|
|    d) Depth Set for Spidering : 1 - PASS
100  #this is the output for p spider.status
false #this is the output for p spider.running?
|
|    e) Completed Spidering http://http://www.startlogic.com - PASS
|
| B) Initiating Active Scan
"1"
"2"
/usr/lib/ruby/vendor_ruby/json/common.rb:148:in `parse': 751: unexpected token at 'Does Not Exist' (JSON::ParserError)
        from /usr/lib/ruby/vendor_ruby/json/common.rb:148:in `parse'
        from /var/lib/gems/1.9.1/gems/owasp_zap-0.0.95/lib/owasp_zap/attack.rb:17:in `status'
        from /var/lib/gems/1.9.1/gems/owasp_zap-0.0.95/lib/owasp_zap/attack.rb:26:in `running?'
        from /home/logins/diya-ashetty/stash/ruby/lib/owasp/ci_owasp_zap.rb:148:in `active_scan_site'
        from owasp_active_scanning.rb:79:in `<main>'

**Comment by kingthorin** [comment] 2015-09-30 09:58
What version of ZAP?

**Comment by ambikashri** [comment] 2015-09-30 10:07
2.4.1

**Comment by kingthorin** [comment] 2015-09-30 11:36
I can't say 100% sure it'll address your issue but I do note that 2.4.2 addressed a number of API issues that could be the culprit here. Are you able to upgrade?

https://github.com/zaproxy/zap-core-help/wiki/HelpReleases2_4_2

* Issue 1770 : Exceptions when calling (some) context API actions in daemon mode
* Issue 1784 : NullPointerException when active scanning through the API with a target without scheme
*  Issue 1805 : ZAP API might not return the response in requested format on errors

**Comment by psiinon** [comment] 2015-10-02 13:19
The error implies theres a problem with the client API.
Can you try with the latest version and let us know if you still get it.

**Comment by thc202** [comment] 2015-10-02 13:47
Yes, that's caused by Issue 1805 (i.e. the response is not JSON), although the actual API error means that no active scan was started.

**Comment by kingthorin** [comment] 2016-02-05 02:28
@ambikashri any news?

**Comment by kingthorin** [comment] 2016-03-20 23:26
Will close on or after 20160407, if nothing further recieved.

**Comment by kingthorin** [comment] 2016-05-03 22:15
Closing - InsufficientEvidence

**Closed by kingthorin** 2016-05-03 22:15 UTC
Labels: FOLLOWUP-20160407
