### ISSUE TITLE
ZAP automated scan support http2

### ISSUE THREAD

**Issue by daniejstriata** [zaproxy/zaproxy#6694] opened 2021-07-16 13:37 UTC
I'm unable to scan sites only served by http2 protocol.

Please allow sites only served by h2 to be scanned. This is the error I get:
![image](https://user-images.githubusercontent.com/13314239/125956389-3053a16c-7ace-4bd3-9f42-3e5514bc36b6.png)

The site I have issues with is behind an AWS Application loadbalancer with only HTTP2 selected.

**Comment by kingthorin** [comment] 2021-07-16 13:40
Closing as duplicate of https://github.com/zaproxy/zaproxy/issues/1765

**Closed** 2021-07-16 13:40 UTC
Labels: duplicate
