### ISSUE TITLE
ZAP doesn't generate report

### ISSUE THREAD

**Issue by aleksandr-kk** [zaproxy/zaproxy#6891] opened 2021-10-26 19:57 UTC
**Describe the bug**
When executing Azure Devops pipeline with Zaproxy very often report doesn't generate.
i'm using following guide:
https://www.zaproxy.org/docs/docker/full-scan/

My task in pipeline
_chmod -R 777  ./
docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
 -t ${{parameters.url}} -g gen.conf -x OWASP-ZAP-Report.xml -x OWASP-ZAP-Report.xml -r api-scan-report.html_

**To Reproduce**
1. Execute pipeline with task
          - bash: |
             chmod -R 777  ./
             docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
                 -t ${{parameters.url}} -g gen.conf -x OWASP-ZAP-Report.xml -x OWASP-ZAP-Report.xml -r api-scan-report.html
             echo "==========="
             ls -la
            displayName: 'Bash Script'

**Expected behavior**
XML report OWASP-ZAP-Report.xml should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/61759452/138950673-06fcd6d0-460f-441e-a578-dbb92c04f520.png)
![image](https://user-images.githubusercontent.com/61759452/138950738-fb87b1a0-5231-4c15-8da5-8520afbab507.png)

**Software versions**
 - ZAP: Latest docker image

**Additional context**
Usually i see 2 following exceptions

2021-10-22 15:26:08,047 Could not find custom hooks file at /home/zap/.zap_hooks.py 
ERROR HTTPConnectionPool(host='localhost', port=59834): Max retries exceeded with url: http://zap/JSON/spider/view/status/?scanId=0 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))
2021-10-22 15:38:20,171 I/O error: HTTPConnectionPool(host='localhost', port=59834): Max retries exceeded with url: http://zap/JSON/spider/view/status/?scanId=0 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))

_java.lang.OutOfMemoryError: Java heap space_

**Would you like to help fix this issue?**
Yes

**Comment by aleksandr-kk** [comment] 2022-01-17 07:53
Hi. No, i don't scan huge site. tried for example this sites:
https://www.itineris.net/

**Comment by psiinon** [comment] 2022-01-17 13:40
Also, do you need to allocate more memory to the docker container on Azure? I know I had to do that on Mac OS ...

**Comment by kingthorin** [comment] 2022-04-12 04:06
Can this be closed as a duplicate of 1288?

**Closed** 2022-04-20 12:26 UTC
Labels: bug, duplicate
