### ISSUE TITLE
Ability to limit the maximum size of the response body

### ISSUE THREAD

**Issue by winzj** [zaproxy/zaproxy#6991] opened 2021-12-23 08:56 UTC
**Is your feature request related to a problem? Please describe.**
I discovered a problem while scanning a website where the response body of some alerts was a very large javascript file. Which had a lot of findings like `Timestamp Disclosure` in it. I had to use the GUI because something was not working on on my automated scripting. When I used the the GUI of the OWASP ZAP, there were problems visualizing the resulting alerts and the associated response bodies. The GUI really slowed down.

**Describe the solution you'd like**
I think it would be a good idea to add the ability to limit the size of the response body inside an alert, because generally I do not want to disable a rule since I want to see if the results change over time. This limit can be set from the user to cover edge cases like the one I discovered. The default should always use the full response body, because this will only happen if there are large javascript files like in the website I had to test.
If the repsonse body's length is bigger than the limit only a part of the reponse body (some kind of shrink should be applied) or only the limit of bytes/characters will are saved for the response body.

**Additional context**
After I noticed my problem I tried to generate reports which works fine, but reporting formats that use the response body of an alert, can result in very large report files. I noticed this when testing the SARIF reporting #6875 my colleague is currently implementing. Right now the resulting SARIF report for my example would be more than 1GB of JSON. I think the session exporting would be affected as well.

**Describe alternatives you've considered**
If the Zaproxy is only used in daemon mode, there would not be any problems loading large repsonse bodies inside the gui and the limitation could be done by the reporting and exporting logic. (In this case I do not know what happens if there are even more/bigger results to save). But since really large response bodies can cause issues in other cases as well, I would prefer some kind of limitation option.

Maybe there are better options or I missed something and you can point me in the right direction.

**Comment by thc202** [comment] 2021-12-23 10:15
This seems to be a duplicate of #5791.

**Comment by winzj** [comment] 2021-12-28 13:40
You are right, I must have missed the issue you mentioned. It is a duplicate.

**Comment by kingthorin** [comment] 2021-12-28 13:42
Thanks for confirming.

**Closed by kingthorin** 2021-12-28 13:42 UTC
Labels: duplicate
