### ISSUE TITLE
Python3 encoding issue in docker image

### ISSUE THREAD

**Issue by thesp0nge** [zaproxy/zaproxy#5905] opened 2020-03-19 12:04 UTC
**Describe the bug**
I was trying to use zap-cli utilities from the stable docker image, as mentioned in the documentation here in repository wiki. 

Here is the error:

docker run -u zap -i owasp/zap2docker-stable zap-cli --debug --summary https://target/
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 621, in main
    raise RuntimeError('Click will abort further execution '
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Either switch to Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

**Software versions**
 - ZAP: stable docker image
 - OS: Linux Ubunto 19.10

**Would you like to help fix this issue?**
Yes please! :)

**Comment by thc202** [comment] 2020-03-19 12:08
Closing as duplicate of #5818. We still need to release the stable image though.

**Closed by thc202** 2020-03-19 12:08 UTC
Labels: bug
