### ISSUE TITLE
Docker full scan fails with ApiException: illegal_parameter

### ISSUE THREAD

**Issue by barbeque-squared** [zaproxy/zaproxy#7220] opened 2022-04-20 06:18 UTC
### Describe the bug

This is probably a near-duplicate of #7218, but we are using `zap-full-scan.py` and the exception is slightly different.

The final exception is this one:
```200716 [Thread-9] INFO  org.parosproxy.paros.core.scanner.Scanner - scanner completed in 173.087s
205544 [ZAP-IO-EventExecutor-3-9] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/ascan/view/scanners/] from [127.0.0.1]:
org.zaproxy.zap.extension.api.ApiException: illegal_parameter
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.verifyCategoryId(ActiveScanAPI.java:807) ~[zap-D-2022-04-19.jar:D-2022-04-19]
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiView(ActiveScanAPI.java:1064) ~[zap-D-2022-04-19.jar:D-2022-04-19]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:535) ~[zap-D-2022-04-19.jar:D-2022-04-19]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:93) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpRequestHandler.handleMessage0(HttpRequestHandler.java:32) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpIncludedMessageHandler.handleMessage(HttpIncludedMessageHandler.java:32) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:118) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:100) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:63) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:83) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:72) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:37) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) ~[?:?]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

and the Python traceback is:
```ERROR <class 'AttributeError'>
2022-04-20 01:20:04,106 Unexpected error: <class 'AttributeError'>
Traceback (most recent call last):
  File "/zap/zap-full-scan.py", line 396, in main
    plugin_id = rule.get('id')
AttributeError: 'str' object has no attribute 'get'
```

### Steps to reproduce the behavior

We run it like this in CI: `zap-full-scan.py -j -a -t <APPLICATION_URL> -c config.tsv -r report.html`

The `config.tsv` is generated from this:
```
zap-full-scan.py -j -a -t <APPLICATION_URL> -g current-config.tsv
cat current-config.tsv outofscope.tsv > config.tsv
```
It's basically the default (with everything on WARN) and then some of those are placed out of scope because they fail for various reasons.

### Expected behavior

Unknown. From #7218 I gather that it's currently doing something that it shouldn't do.

However, from #7206 it also seems deliberate to start throwing errors for unknown scan rule ID's, which is going to cause issues in our CI setup. See #7219 for that.

### Software versions

`:latest` weekly

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2022-04-20 07:07
Closing as duplicate of zaproxy/zaproxy#7218

**Closed by kingthorin** 2022-04-20 07:07 UTC
Labels: bug, duplicate, weekly, Docker
