### ISSUE TITLE
Active Scan API - Scan whole context as user incorrectly requires a URL

### ISSUE THREAD

**Issue by kawowski** [zaproxy/zaproxy#5021] opened 2018-10-01 13:07 UTC
As explained in #2722 and #1853, it was not possible to start an active scan in a context via the API without specifying an URL. This issue clearly seems to be fixed, since the following API call starts an active scan in my preferred context:
http://localhost:8080/JSON/ascan/action/scan?apikey=****&recurse=true&contextId=1

Using the equivalent API call for scanAsUser (with HTTP/NTLM authentication)
http://localhost:8080/JSON/ascan/action/scanAsUser?apikey=****&recurse=true&contextId=1&userId=11
results in the API output `{"code":"internal_error","message":"Internal Error"}` and zap.log file with the following content:
```
net.sf.json.JSONException: JSONObject["url"] not found.
	at net.sf.json.JSONObject.getString(JSONObject.java:2092)
	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiAction(ActiveScanAPI.java:249)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:748)
```

However adding the parameter "url" with a valid URL as value works as expected - starting an active scan in my preferred context using my specified HTTP authentication user credentials.

I guess the problem (#2722) has only been fixed for non-authenticated scans.

I would like the scan to behave exactly as when starting it via the GUI and selecting a context as "starting point". When using no authentication (or using the spider) this can be done by not specifying the "url" parameter.

**Comment by thc202** [comment] 2018-10-01 13:16
That's caused by an incorrect validation, fixed in #4371.

**Closed by thc202** 2018-10-01 13:16 UTC
Labels: Component-API, bug
