### ISSUE TITLE
Session file takes forever to load

### ISSUE THREAD

**Issue by najum98** [zaproxy/zaproxy#6330] opened 2020-11-30 02:00 UTC
**Describe the bug**
I am considering ZAP over Burp, because it allows persistent sessions but I am having problem with it, first interestingly my session file has got 10GB in size and the ZAP literally takes around half an hour at least to load this session file, it really wastes some time which has been utilized in working on the file. Also the "shutting down server" when I close ZAP also takes almost same amount of time, so its very disturbing. I've tried both on Kali and Win10 but the issue is same on both OS

**Expected behavior**
It should not take more than 5 minutes at most.

**Software versions**
 - ZAP: 2.9.0
 - OS: Both, Kali and Win10
 - Java: build 1.8.0_261-b12

**Additional context**
Shutting down server is also taking a lot of time, this issue is clearly with ZAP so just dont mark this issue as "closed" without a solution

**Comment by najum98** [comment] 2020-11-30 06:46
Just ran ZAP again, this time it took ~45 mins. Also when the ZAP is in the process of loading the file, the PC starts to lag indicating that ZAP is using lots of CPU
My system is i5 8GB RAM, 1GB SWAP, I dont think that there is any issue with hardware. OS is Kali

**Comment by thc202** [comment] 2020-11-30 07:59
Closing as duplicate of #1364 .

**Closed by thc202** 2020-11-30 07:59 UTC
Labels: bug
