### ISSUE TITLE
Automated authentication detection and configuration

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#2251] opened 2016-02-19 12:51 UTC
ZAP has extensive support for supporting application authentication, but configuring this is a manual process which can be tricky to get right.

The enhancement would allow ZAP to detect as many forms of authentication as possible and automatically configure them using the existing ZAP functionality.

**Comment by thc202** [comment] 2018-04-11 14:26
Closing, duplicate of #4105.

**Closed by thc202** 2018-04-11 14:26 UTC
Labels: enhancement
