### ISSUE TITLE
"The provided browser was not found" However installed and running

### ISSUE THREAD

**Issue by BukolaO** [zaproxy/zaproxy#7133] opened 2022-03-10 09:23 UTC
On my Windows OS, running ZAP, I try to do a manual explore but each time I choose firefox, it brings out an error "The provided browser was not found" When I try to run chrome, it opens and closes immediately. 

Software versions

Java version 8
Windows OS:  10 Education
ZAP: 2.11.1

Errors from log file for both chrome and Firefox;

**Chrome**;

2022-03-10 09:29:32,433 [ZAP-BrowserLauncher] ERROR ExtensionQuickStartLaunch - invalid argument
  (Session info: chrome=99.0.4844.51)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '***redacted***', ip: '***redacted***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 99.0.4844.51, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: C:\***redacted***\***redacted***\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:32884}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(manual, http=localhos..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c5f49db878f7270ba4cfcdfe05c33fa9
org.openqa.selenium.InvalidArgumentException: invalid argument
  (Session info: chrome=99.0.4844.51)
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '***redacted***', ip: '***redacted***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 99.0.4844.51, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: C:\'***redacted***\'***redacted***\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:32884}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(manual, http=localhos..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: c5f49db878f7270ba4cfcdfe05c33fa9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_321]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_321]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_321]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187) ~[?:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122) ~[?:?]
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:216) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]

**FIREFOX**

2022-03-10 09:29:54,548 [ZAP-BrowserLauncher] ERROR ExtensionQuickStartLaunch - Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: ''***redacted***, ip: ''***redacted***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: ''***redacted***', ip: ''***redacted***', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100) ~[?:?]
	at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_321]
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1007) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:855) ~[?:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:740) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:552) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:701) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:642) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:618) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:602) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:592) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:209) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]

**Comment by kingthorin** [comment] 2022-03-10 09:38
Closing as duplicate of zaproxy/zaproxy#7095

Next time you open a ticket please use one of the proper templates.

**Closed by kingthorin** 2022-03-10 09:38 UTC
