### ISSUE TITLE
I am unable to generate a report through OWASP

### ISSUE THREAD

**Issue by CSharmaCovalience** [zaproxy/zaproxy#7070] opened 2022-02-04 11:14 UTC
**Describe the bug**
Unable to generate a report

**To Reproduce**
1. Select manual testing
2. Enter the website address
3. From Reports drop-down click on generate report button
4. A pop up will open and click on generate report button.
5. A pop up modal will open that unable to generate report due to OGNL expression

**Expected behavior**
able to generate a report

**Screenshots**
![owasp](https://user-images.githubusercontent.com/86605030/152519747-08a7febc-b3ef-4423-8de9-587ff565df70.png)

**Software versions**
 - ZAP: 2.11.1
 - Add-on: None
 - OS: Windows 11
 - Java: JDK - 16.0.1
 - Browser: Crome Version 97.0.4692.99

**Errors from the zap.log file**
no logs

**Additional context**
no

**Would you like to help fix this issue?**
yes

**Comment by thc202** [comment] 2022-02-04 11:48
Closing as duplicate of #7026. For the time being the workaround is to use an older Java version (e.g. 11).

**Closed by thc202** 2022-02-04 11:48 UTC
Labels: bug
