### ISSUE TITLE
VariantURLQuery throwing exceptions on active scan

### ISSUE THREAD

**Issue by thilina27** [zaproxy/zaproxy#1848] opened 2015-08-24 10:56 UTC
When scanning this error occurs. 

Error like this occurs for different scan rules 

769590 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrules.TestServerSideInclude  - Error occurred while scanning with variant org.parosproxy.paros.core.scanner.VariantURLQuery
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "{p"
	at java.net.URLDecoder.decode(URLDecoder.java:192)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.getURLDecode(Unknown Source)
	at org.parosproxy.paros.core.scanner.VariantURLQuery.getUnescapedValue(Unknown Source)
	at org.parosproxy.paros.core.scanner.VariantAbstractQuery.setParams(Unknown Source)
	at org.parosproxy.paros.core.scanner.VariantURLQuery.setMessage(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by psiinon** [comment] 2015-08-24 11:05
Does the scan carry on anyway?
I was fairly sure that these were benign...

**Comment by thilina27** [comment] 2015-08-24 11:07
yes scan is carry on. But dose it skip some scans ?

**Comment by thc202** [comment] 2015-08-26 15:38
Yes, some query parameters are not tested because of the exception(s).
The issue is related to #1801 (the class ```VariantURLQuery``` expects the query parameters escaped but they are not).
Most likely fixing the other issue will fix this one.

**Comment by thc202** [comment] 2015-11-09 09:26
Would you mind if the issue is reopened? The issue was not yet fixed and closing it might give that impression.

**Closed** 2016-05-09 08:56 UTC
Labels: bug
