### ISSUE TITLE
ZAP connects through HTTP proxy force httpS

### ISSUE THREAD

**Issue by highchoice** [zaproxy/zaproxy#7648] opened 2022-12-10 19:27 UTC
Hi all,
I enabled HTTP proxy settings to local privoxy server, listening on 127.0.0.1:8118. All works fine until update ZAP to version 2.12.0.
Now I'm unable to establish connection, getting this error 
`ZAP Error [org.apache.hc.client5.http.HttpHostConnectException]: Connect to https://127.0.0.1:8118 [/127.0.0.1] failed: Connection refused: no further information
`
Connection is forced to httpS

**Comment by thc202** [comment] 2022-12-10 20:25
Closing as duplicate of #7594.

**Closed by thc202** 2022-12-10 20:25 UTC
