### ISSUE TITLE
wrong comparison of HTTP Messages in queryEquals() method of HttpMessage class

### ISSUE THREAD

**Issue by raghuveerbathini** [zaproxy/zaproxy#3350] opened 2017-03-31 20:13 UTC
The method queryEquals(HttpMessage), of org.parosproxy.paros.network.HttpMessage class, compares url and body parameter names of two HTTP Messages. 

The comparison is happening in wrong way, that it is comparing the first HTTP Message to itself, hence returns 'true' always.

        **set1 = getParamNameSet(HtmlParameter.Type.url);
	set2 = getParamNameSet(HtmlParameter.Type.url);**
	if (!set1.equals(set2)) {
	        return false;
	}
	if (getRequestHeader().getMethod().equalsIgnoreCase(HttpRequestHeader.POST)) {
	        
	        **set1 = getParamNameSet(HtmlParameter.Type.form);
		set2 = getParamNameSet(HtmlParameter.Type.form);**	        

		if (!set1.equals(set2)) {
		        return false;
		}
	    }

The following is the correct way to compare the two Messages:

        **set1 = getParamNameSet(HtmlParameter.Type.url);
	set2 = msg.getParamNameSet(HtmlParameter.Type.url);**
	if (!set1.equals(set2)) {
	        return false;
	}
	if (getRequestHeader().getMethod().equalsIgnoreCase(HttpRequestHeader.POST)) {
	        
	        **set1 = getParamNameSet(HtmlParameter.Type.form);
		set2 = msg.getParamNameSet(HtmlParameter.Type.form);**	        

		if (!set1.equals(set2)) {
		        return false;
		}
	    }

**Comment by thc202** [comment] 2017-03-31 20:37
Indeed, I'm wondering if it does worth maintaining those methods, that's not working properly since 2.3.0 and ZAP nor the (zap-extensions) add-ons are using it.

**Comment by kingthorin** [comment] 2017-04-03 00:10
I'd it is un-used let's drop it.

**Comment by psiinon** [comment] 2017-04-03 07:51
+1

**Comment by kingthorin** [comment] 2017-08-22 23:30
So do we want to drop the `queryEquals` function and it's use altogether? Since `queryEquals` is used within `equalType` which does not appear to be used anywhere do we want to drop both?

https://github.com/zaproxy/zaproxy/blob/a1097f98f327d89966777e471c73bcc55d56fb91/src/org/parosproxy/paros/network/HttpMessage.java#L482

https://github.com/zaproxy/zaproxy/blob/a1097f98f327d89966777e471c73bcc55d56fb91/src/org/parosproxy/paros/network/HttpMessage.java#L431

[ZAP queryEquals search](https://github.com/zaproxy/zaproxy/search?utf8=%E2%9C%93&q=queryequals&type=)
[ZAP equalsType search](https://github.com/zaproxy/zaproxy/search?utf8=%E2%9C%93&q=equalstype&type=)
[ZAP Extensions equalsType search](https://github.com/zaproxy/zap-extensions/search?utf8=%E2%9C%93&q=equalstype&type=)

**Comment by thc202** [comment] 2017-08-22 23:53
Yes, the conditions are still the same. If we want to keep binary compatibility we could deprecate it instead (but I doubt anyone is using it).

**Comment by raghuveerbathini** [comment] 2017-08-23 06:29
We had a requirement to compare the two HTTP Requests, so we used the **queryEquals** method.

**Comment by thc202** [comment] 2017-08-23 08:53
Ok, why not `equals`? Did you change the visibility of `queryEquals`, or were using `equalType`?

**Comment by raghuveerbathini** [comment] 2017-08-23 10:31
We are using equalType(). The reason of using it over equals() is, the way of comparison in the former. It uses Set to hold the url/body parameters.

**Comment by kingthorin** [comment] 2017-08-23 11:54
Ok if there's a use case we can leave it in and fix it.

**Comment by thc202** [comment] 2017-08-23 12:48
Agreed, although we need to document the method a lot better (i.e. it's also checking the body, but not always just the parameter names, sometimes it might include the "values").

**Comment by kingthorin** [comment] 2017-08-23 13:00
Ok I'll try to update the PR at lunchtime, failing that I'll tackle it later tonight.

**Comment by kingthorin** [comment] 2017-08-24 00:30
When would it include values? It uses `getParamNameSet(Type)` which builds the name set from the key of a name value pair map.

**Comment by thc202** [comment] 2017-08-24 09:27
Basically anything that's not `x-www-form-urlencoded`, that can be reproduced easily with a JSON payload.

**Comment by kingthorin** [comment] 2017-08-24 09:46
Ok the PR now includes some javadoc content which attempts to address such situations.

**Comment by thc202** [comment] 2017-08-24 11:06
Fixed in #3843.

**Closed by thc202** 2017-08-24 11:06 UTC
Labels: bug
