### ISSUE TITLE
Scripts Flagged as Changed when Disabling/Enabling and prompts saving.

### ISSUE THREAD

**Issue by egerod** [zaproxy/zaproxy#4241] opened 2018-01-09 09:11 UTC
I recently updated the way I loaded scripts into ZAP from using the API to using the script directory and then enabling the needed scripts. But this have caused all the scripts to be flagged as changed, and warns about unsaved scripts on shutdown.

**Steps to Reproduce**
Enable/Disable a script through either the API or UI.

**Outcome**
Script is  flagged as changed, allows for saving and warns about unsaved on shutdown.

**Expected Outcome**
The script isn't flagged as changed.

**Remarks**
From testing it doesn't appear that the script enabled/disabled state is saved in either the session or the ZAP configuration. If the enabled state is not saved, changing the state shouldn't prompt saving the script or cause warnings on shutdown.

**Comment by kingthorin** [comment] 2018-01-09 10:01
This is a duplicate of https://github.com/zaproxy/zaproxy/issues/2189

**Closed** 2018-01-09 10:01 UTC
Labels: duplicate

**Comment by thc202** [comment] 2018-01-09 10:03
The enabled state is saved in the configuration file (along with the other data, name, type...).
