### ISSUE TITLE
add colors for request editor

### ISSUE THREAD

**Issue by knassar702** [zaproxy/zaproxy#6467] opened 2021-02-26 01:15 UTC
hi team , can you add some colors theme for request/response header .?

**Comment by kingthorin** [comment] 2021-02-26 02:33
Could you please be more specific.

**Comment by knassar702** [comment] 2021-02-26 05:46
sure
i mean add colors in zap request header (especially : cookies) , This will be better for seeing :smile:
 
![test](https://user-images.githubusercontent.com/45688522/109260263-7f8cc180-7806-11eb-9c00-f50d96cb11d2.png)
![test1](https://user-images.githubusercontent.com/45688522/109260265-80255800-7806-11eb-8916-eae7de2b3492.png)

**Comment by psiinon** [comment] 2021-02-26 09:42
We use suitable syntax colours on HTTP bodies (eg HTML, JavaScript etc) but I have a feeling those didnt work with HTTP headers so we stuck with 'plain'.
I wonder if any of the other options would work, or if not whether we could add our own colours. HTTP headers are pretty simple so hopefully it shouldnt be too hard and I agree it would help...

**Comment by thc202** [comment] 2021-02-26 11:01
Closing as duplicate of #1907.

**Closed by thc202** 2021-02-26 11:01 UTC
Labels: Component-UI, Usability, duplicate, enhancement
