### ISSUE TITLE
ZAP 2.9.0 complains about missing Java

### ISSUE THREAD

**Issue by testautomation** [zaproxy/zaproxy#5891] opened 2020-03-10 15:28 UTC
**Describe the bug**
After installation on Windows 10 with Java 11 (OpenJDK 18.9) starting ZAP fails with message

![image](https://user-images.githubusercontent.com/38438046/76328339-78b22980-62eb-11ea-8e0b-d034834cf85a.png)

**To Reproduce**
1. Start ZAP by double clicking it's icon on the desktop

**Expected behavior**
ZAP starts using installed Java 11 runtime

**Software versions**
 - ZAP: 2.9.0
 - OS: Windows 10 64bit
 - Java: openjdk 11.0.2 2019-01-15

**Comment by kingthorin** [comment] 2020-03-10 15:50
This is a known issue.

Duplicate of zaproxy/zaproxy#5368

If you just navigate to the install location you should be able to launch just fine with zap.bat
https://mobile.twitter.com/kingthorin_rm/status/1229956991554084864

**Closed by kingthorin** 2020-03-10 15:50 UTC
Labels: duplicate
