### ISSUE TITLE
Make it faster to get the default config file

### ISSUE THREAD

**Issue by barbeque-squared** [zaproxy/zaproxy#7219] opened 2022-04-20 06:13 UTC
### Is your feature request related to a problem? Please describe.

In our CI, we need to place certain items out of scope. Currently, the only way (that I've found) to use this functionality is to first generate the default config with `-g default-config.tsv`, then `cat default-config.tsv outofscope.tsv > actual-config.tsv`, and then do the actual scan with `-c actual-config.tsv`

The full command to generate the default config is: `zap-full-scan.py -j -a -t <APPLICATION_URL> -g default-config.tsv || true`
(the `-j -a` seems to be necessary to actually include _all_ rules; the `|| true` is to make our CI not exit on inevitable false positives)

The issue is that this commands takes a long time.

### Describe the solution you'd like

I'd like either of these solutions:

1. Some way of getting the resulting `default-config.tsv` really fast/without doing an actual scan
2. Some way (a command line option?) to internally do that `cat` operation, so we only need to supply (and maintain) our out of scope overrides.
3. Be able to use `* WARN .*` or something like it in the custom config file (see the last section of https://www.zaproxy.org/docs/docker/baseline-scan/#configuration-file, this appears to be a thing for OUTOFSCOPE, but not sure if it also works for others).

### Describe alternatives you've considered

- Do the `-g` step in the same CI job as the actual scan. This makes the actual scan job basically twice as long.
- Do the `-g` step in a parallel CI job that starts immediately at the start of a pipeline, but only blocks the actual scan job. Doable, but will still introduce (some) delays, plus it would be a waste of resources. The default config doesn't change that often anyway.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2022-04-20 11:19
I'm actually surprised its taken someone so long to ask for this ;)

**Comment by thc202** [comment] 2022-04-24 13:12
Closing as duplicate of #6409.

**Closed by thc202** 2022-04-24 13:12 UTC
Labels: enhancement, Docker
