### ISSUE TITLE
Error creating a JSON report

### ISSUE THREAD

**Issue by franciscoccos** [zaproxy/zaproxy#8000] opened 2023-08-10 12:24 UTC
### Describe the bug

Hi, I was trying to generate a JSON report for my application and all the time I get the same error which is the following:

![image](https://github.com/zaproxy/zaproxy/assets/127829472/03ed8eb9-f912-48c0-a0ee-207dc99767cb)

This happens in the latest version 2.13.0 but when I pre-upgrade to 2.12.0 the error did not appear and I formed correctly the JSON.

Here I attach an image of the JSON that is created in version 2.13.0

![image](https://github.com/zaproxy/zaproxy/assets/127829472/1c58f8cd-0d39-44d1-bc39-cc8d50e651c1)

### Steps to reproduce the behavior

1. Install version 2.13.0
2. Scanning automatically or manually does not maind any URLs
3. try to generate a json report

### Expected behavior

It has to create a normal report whitout give any error 

### Software versions

Error happend in 2.13.0

Error did not occur in 2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-08-10 12:28
This is a duplicate of #7993.

**Closed** 2023-08-10 12:31 UTC
Labels: bug, duplicate
