### ISSUE TITLE
Zap Scan Freezes on marking Alert as false Positive

### ISSUE THREAD

**Issue by DarshanAwachat** [zaproxy/zaproxy#7411] opened 2022-08-10 10:13 UTC
### Describe the bug

Zap Scan freezes on marking alert as false positive after the automated scan is completed.

### Steps to reproduce the behavior

1. Run Automated Scan with both traditional and Ajax Spider
2. After Active Scan is compeleted
3. Zap Scan Freezes when Trying to mark error as false positive via left click. (Especially Marking an entire Alert with high instances as false positive)

### Expected behavior

Should be able to mark as false positive and Zap should not freeze.

### Software versions

ZAP tool version : 2.11.1
JDK : 18.0.1.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2022-08-10 10:16
What's the size of the HTTP response?

**Comment by DarshanAwachat** [comment] 2022-08-10 10:22
Is there a limit as such? I used to do it earlier on the same domain but didn't face this issue.

**Comment by thc202** [comment] 2022-08-10 10:28
There's no limit but with big messages the UI sometimes freezes (that was fixed in the weeklies).

**Comment by DarshanAwachat** [comment] 2022-08-10 10:38
Okay, what is the expected release timeline for that bug fix.

**Comment by psiinon** [comment] 2022-08-10 10:39
Its been fixed, in the weeklies :)
We do not have a date for the next full release yet.

**Comment by thc202** [comment] 2022-08-12 08:43
Closing as duplicate of #5791. If you still have problems with the weekly release, please, leave a comment.

**Closed by thc202** 2022-08-12 08:43 UTC
