### ISSUE TITLE
LDAP Injection

### ISSUE THREAD

**Issue by jitendra-90** [zaproxy/zaproxy#8563] opened 2024-07-17 08:30 UTC
### Describe the bug

I am getting LDAP Injection in High alert while I am trying to send request from ZAP tool then getting "404 Not Found".

**Request:**
 GET https://localhost/_content/Blazor.Bootstrap HTTP/1.1
host: localhost
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
pragma: no-cache
cache-control: no-cache
referer: https://localhost/
Cookie: ARRAffinity=1e09d237d3999964ca6819ef06a4e51aa4b33e834c790026650a41fa8d3b3617; ARRAffinitySameSite=1e09d237d3999964ca6819ef06a4e51aa4b33e834c790026650a41fa8d3b3617

**Response:** 
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Thu, 11 Jul 2024 15:03:57 GMT
Server: Microsoft-IIS/10.0
Request-Context: appId=cid-v1:e5f98d7e-a47b-4c7c-a046-4acc83e03676
X-Powered-By: ASP.NET

### Steps to reproduce the behavior

Not reproduced

### Expected behavior

Not should come

### Software versions

2.15.0

### Screenshots

![image](https://github.com/user-attachments/assets/34badd1d-e09b-49c5-b97a-a6463bcdb81b)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment] 2024-07-17 08:47
This seems to be a duplicate of https://github.com/zaproxy/zaproxy/issues/8519

**Closed** 2024-07-17 08:48 UTC
Labels: duplicate

**Comment by jitendra-90** [comment] 2024-07-17 08:51
I want confirm that is it FalsePositive?

**Comment by kingthorin** [comment] 2024-07-17 09:00
Seems likely. Part of the inbound fix will exclude messages that are client or server errors to start with.
