### ISSUE TITLE
ZAP Error [java.net.SocketTimeoutException]: Read timed out

### ISSUE THREAD

**Issue by p3r1c0** [zaproxy/zaproxy#4378] opened 2018-02-12 14:43 UTC
Hi, 
I'm developing a project for my company that consists in improve the SDLC to adding a new step in the development procedure that consists in use spider and scan in the testing proces. I have the following error when try to connect to docker through an external IP address:

933119 [ZAP-ProxyThread-168] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read http://b6b7c537.ngrok.io/ within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.

In this case I try to expose docker with ngrok (how to first step) for later use in Azure.
Beftore to ask, I have been researching and I can see a related issue:
https://github.com/zaproxy/zaproxy/issues/2318 , but I can't see any clear solution to this problem. 

I tried with the following command: docker run --name zap_docker -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true , following this recomendations: https://github.com/zaproxy/zaproxy/wiki/Docker#accessing-the-api-from-outside-of-the-docker-container. 

In fact, in localhost I can see the API interface perfectly. I don't know how to solve this problem. 
I need to access to the zap docker with external IP's because I want to intercept all the traffic. 

Thank you very much for your attention and help.

Best regards.

**Comment by thc202** [comment] 2018-02-12 14:50
Closing, duplicate of #3594. In the meantime If you need to access the ZAP API with external IP you can do so by proxying through ZAP and issue the requests with `zap` domain.

**Closed by thc202** 2018-02-12 14:50 UTC
