### ISSUE TITLE
Add Support for Accept-Encoding: br (Brotli)

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2198] opened 2016-01-22 17:30 UTC
Per:
https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/JufzX024oy0/WEOGbN43AwAJ

It seems there are Chrome plans to support this encoding type, the post also outlines that Firefox M44 has the support. If client are going to start accepting this encoding type then ZAP probably should as well.

Other references which may be of use or interest:
https://github.com/meteogroup/jbrotli
https://groups.google.com/forum/#!topic/brotli/gGkedK9yHuE

Should maybe be considered in conjunction with: https://github.com/zaproxy/zaproxy/issues/1765

**Comment by kingthorin** [comment] 2016-01-22 23:27
In the news http://www.computerworld.com/article/3025456/web-browsers/google-to-boost-compression-performance-in-chrome-49.html

**Comment by kingthorin** [comment] 2016-01-27 18:31
FF44 has been released:
https://www.mozilla.org/en-US/firefox/44.0/releasenotes/
> Support the brotli compression format via HTTPS content-encoding

**Comment by kingthorin** [comment] 2020-06-05 15:43
I don't think this can be tackled as a one-off and I believe that the networking core change swill probably handle this anyway. Also brotli seems to be more applicable for binary data (fonts etc) so probably not as key for ZAP. 

@psiinon @thc202 do you think it makes sense to just close this?

**Comment by thc202** [comment] 2020-06-05 16:20
It can, the problem is lack of (maintained) encoder.

I'm fine either way.

**Comment by thc202** [comment] 2023-10-14 07:30
Reopening, would be good to support this one to avoid the need to remove the default browser header.

**Comment by double16** [comment] 2023-10-15 14:14
You can assign to me if you like.

**Comment by thc202** [comment] 2023-10-15 14:20
It's already assigned.

**Comment by thc202** [comment] 2023-11-17 10:10
Closing as done in zaproxy/zap-extensions#5100. For the behaviour of the option "Remove Accept-Encoding Request Heade" see #8124.

**Closed by thc202** 2023-11-17 10:10 UTC
Labels: enhancement, add-on, in:network
