### ISSUE TITLE
Regression: Host Labels in Context Scan Progress Dialog missing

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#7398] opened 2022-08-02 11:26 UTC
### Describe the bug

When viewing the Context Scan Dialog window to see the progress of the scan. Some of the labels for the scan types are missing. This was fixed in a previous release but has now shown up again.

### Steps to reproduce the behavior

* Start an Active Scan
* Click on 
![image](https://user-images.githubusercontent.com/10052587/182362553-6641d3ef-004e-46b8-8b8d-3e610c58cd98.png)
* In the Progress Tab, Observe the missing labels for the scan types in the left column

### Expected behavior

All the labels of the scan items should be visible.

### Software versions

OWASP ZAP
Version: D-2022-08-01

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=14.0.0], [id=ascanrules,
version=47.0.0], [id=ascanrulesAlpha, version=38.0.0],
[id=ascanrulesBeta, version=42.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authstats,
version=2.0.0], [id=automation, version=0.17.0],
[id=bruteforce, version=12.0.0], [id=callhome,
version=0.5.0], [id=commonlib, version=1.10.0],
[id=coreLang, version=16.0.0], [id=custompayloads,
version=0.11.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=6.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=13.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.3.0], [id=fileupload, version=1.1.0],
[id=formhandler, version=6.0.0], [id=fuzz, version=13.7.0],
[id=gettingStarted, version=14.0.0], [id=graaljs,
version=0.3.0], [id=graphql, version=0.10.0], [id=help,
version=15.0.0], [id=hud, version=0.14.0],
[id=imagelocationscanner, version=3.0.0], [id=invoke,
version=12.0.0], [id=jsonview, version=2.0.0], [id=network,
version=0.3.0], [id=oast, version=0.11.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=28.0.0],
[id=plugnhack, version=13.0.0], [id=portscan,
version=10.0.0], [id=pscanrules, version=43.0.0],
[id=pscanrulesAlpha, version=35.0.0], [id=pscanrulesBeta,
version=30.0.0], [id=quickstart, version=34.0.0],
[id=reflect, version=0.0.11], [id=regextester,
version=2.0.0], [id=replacer, version=10.0.0], [id=reports,
version=0.16.0], [id=requester, version=7.0.0], [id=retest,
version=0.3.0], [id=retire, version=0.13.0], [id=reveal,
version=5.0.0], [id=revisit, version=4.0.0], [id=scripts,
version=31.0.0], [id=selenium, version=15.10.0],
[id=sequence, version=7.0.0], [id=soap, version=14.0.0],
[id=spiderAjax, version=23.8.0], [id=sqliplugin,
version=15.0.0], [id=tips, version=10.0.0], [id=tokengen,
version=15.0.0], [id=treetools, version=8.0.0],
[id=wappalyzer, version=21.11.0], [id=webdriverlinux,
version=42.0.0], [id=webdrivermacos, version=43.0.0],
[id=webdriverwindows, version=42.0.0], [id=websocket,
version=27.0.0], [id=zest, version=36.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 17.0.3
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: windows-1252
ZAP Home Directory: C:\Users\$USER\OWASP ZAP_D\
ZAP Installation Directory: C:\Users\$USER\LocalPrograms\ZAPWeekly\ZAP_D-2022-08-01\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![image](https://user-images.githubusercontent.com/10052587/182363169-b41b1bdd-55ea-4cbb-889c-4efe53299649.png)

…

![image](https://user-images.githubusercontent.com/10052587/182363289-fb96161f-b05b-48e1-85ed-74583a6e3571.png)

### Errors from the zap.log file

It's only cosmetic so, no errors in the zap.log

### Additional context

This was fixed about a year ago before, but I don't remember and couldn't find the previous ticket. 
The solution in the previous ticket was to share the class as a label when no label is present.

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2022-08-02 11:39
Closing as duplicate of #7228.

**Comment by kingthorin** [comment] 2022-08-02 11:40
This is due to an issue with some third party add-ins which have been fixed but not re-released by their maintainer.

**Closed by thc202** 2022-08-02 11:39 UTC
Labels: bug, duplicate
