### ISSUE TITLE
Dump websocket data to file

### ISSUE THREAD

**Issue by famedoro** [zaproxy/zaproxy#2214] opened 2016-01-31 16:05 UTC
Is it possible to get the data coming from a web socket on port nnnn on a file.

**Comment by kingthorin** [comment] 2016-01-31 16:07
Closing as duplicate of user group discussion.
https://groups.google.com/forum/m/#!topic/zaproxy-users/H6ylmooeOYQ

**Closed by kingthorin** 2016-01-31 16:07 UTC
Labels: duplicate
