### ISSUE TITLE
Exception "connection pool shut down" appears when starting autoscan again after stop

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8258] opened 2023-12-19 16:11 UTC
### Describe the bug

 Ezxception "connection pool shut down" appears when starting autoscan again after stop

### Steps to reproduce the behavior

Run ZAP 2.14 on Windows 10 x64 and start autoscan for http://data.gov.ua.
Wait some time and click Stop button.
Click Attack button when it become enabled.

### Expected behavior

ZAP should continue autoscan

### Software versions

ZAP Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrulesBeta, version=48.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.34.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.10.0], [id=commonlib, version=1.18.0],
[id=coreLang, version=15.0.0], [id=custompayloads,
version=0.13.0], [id=database, version=0.3.0], [id=diff,
version=14.0.0], [id=directorylistv1, version=7.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0],
[id=formhandler, version=6.5.0], [id=fuzz, version=13.12.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=16.0.0], [id=graaljs, version=0.5.0], [id=graphql,
version=0.21.0], [id=help, version=17.0.0], [id=hud,
version=0.18.0], [id=invoke, version=14.0.0], [id=network,
version=0.12.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=38.0.0], [id=portscan,
version=10.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=53.0.0], [id=pscanrulesBeta,
version=35.0.0], [id=quickstart, version=43.0.0],
[id=replacer, version=16.0.0], [id=reports, version=0.26.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.26.0], [id=reveal, version=7.0.0],
[id=scripts, version=44.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.18.0],
[id=sqliplugin, version=15.0.0], [id=svndigger,
version=4.0.0], [id=tips, version=12.0.0], [id=tokengen,
version=15.0.0], [id=wappalyzer, version=21.28.0],
[id=webdriverlinux, version=66.0.0], [id=webdrivermacos,
version=67.0.0], [id=webdriverwindows, version=67.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Eclipse Adoptium 21.0.1
System's Locale: uk_UA
Display Locale: uk_UA
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: C:\Users\Admin\ZAP\
ZAP Installation Directory: C:\Program Files\ZAP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

https://prnt.sc/Mri1vhJTs6RU

### Errors from the zap.log file

see attached logs
[untitled3.zip](https://github.com/zaproxy/zaproxy/files/13717863/untitled3.zip)
[java-trace-connect-down.txt](https://github.com/zaproxy/zaproxy/files/13717868/java-trace-connect-down.txt)

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-12-19 16:52
The log is incomplete but this seems to be a duplicate of #8255.

**Comment by thc202** [comment] 2024-01-11 10:43
Closing as duplicate of #8255.

**Closed by thc202** 2024-01-11 10:43 UTC
Labels: bug
