### ISSUE TITLE
ZAP not relinquishing top window position sometimes after intercept being on

### ISSUE THREAD

**Issue by misfir3** [zaproxy/zaproxy#3075] opened 2016-12-16 15:25 UTC
Sometimes when intercepting requests (and completing/clearing all intercepted requests/responses), ZAP does not want to relinquish it's position 'on top'. This happens at times even after completing and turning the intercept off.

I looked around to see if it was a config option maybe, but have yet to find anything obvious and it does not always do it this way. It seems to happen when requests are queue'ing up (e.g. I'm tampering one manually and 3 more coming ... e.g. apps that poll or refresh .. like SPA's)

**Environment**
* Mac OS X (10.11.6)
* Java is:
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
* ZAP 2.5.0

Anyone else experience this?

**Comment by psiinon** [comment] 2016-12-16 15:33
You can turn off the 'always on top' option via https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsBreakpoints#zap-always-on-top-when-breakpoint-hit
But it should still work correctly when the option is on, so it sounds like a bug.

**Comment by misfir3** [comment] 2016-12-16 15:37
That was on (assume so by default), which makes sense.  Will watch it a bit more with it on and off and see what additional insight I can provide.

**Comment by psiinon** [comment] 2016-12-16 15:40
Thanks :)

**Comment by thc202** [comment] 2016-12-16 17:34
I've seen this behaviour too. I'll try to debug it...

**Comment by thc202** [comment] 2017-01-18 10:34
I was not able to reproduce it again but I'll keep an eye on it...

**Comment by thc202** [comment] 2017-11-23 23:41
Happened again and can reproduce it but only when using WebSockets, not sure if it's the same issue.

**Comment by thc202** [comment] 2018-09-28 08:47
Closing with the changes done for #4623.

**Closed by thc202** 2018-09-28 08:47 UTC
Labels: Component-UI, bug
