### ISSUE TITLE
Import Root CA certificate via API

### ISSUE THREAD

**Issue by Lux0r87** [zaproxy/zaproxy#2280] opened 2016-02-29 09:34 UTC
Allow to import an existing Root CA certificate via the API.

**Comment by davewichers** [comment] 2017-01-23 16:14
Is this a duplicate of: #2023?

**Comment by thc202** [comment] 2017-01-23 16:27
No, this one is to allow to import ZAP's Root CA cert (equivalent to import option in Options > Dynamic SSL Certificates).

**Comment by thc202** [comment] 2021-11-24 20:46
This will be provided with an add-on (included by default).

**Closed** 2021-11-25 09:24 UTC
Labels: enhancement, Component-API, add-on

**Comment by thc202** [comment] 2021-12-06 03:05
This is already available in 2.11 by installing the Network add-on: https://www.zaproxy.org/docs/desktop/addons/network/api/
