### ISSUE TITLE
Zest plugin fails to install

### ISSUE THREAD

**Issue by Pamplemousse** [zaproxy/zaproxy#4561] opened 2018-04-01 14:03 UTC
Got into trouble trying to install the Zest plugin from the add-on Marketplace in Zap.

```
46643 [ZAP-DownloadInstaller] INFO org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Installing new addon zest v27.0.0
46793 [ZAP-DownloadInstaller] ERROR org.parosproxy.paros.extension.ExtensionLoader  - java.lang.NullPointerException
        at org.zaproxy.zap.extension.zest.dialogs.ZestDialogManager.initialize(ZestDialogManager.java:241)
        at org.zaproxy.zap.extension.zest.dialogs.ZestDialogManager.<init>(ZestDialogManager.java:115)
        at org.zaproxy.zap.extension.zest.ExtensionZest.hook(ExtensionZest.java:180)
        at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:695)
        at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(AddOnInstaller.java:235)
        at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(AddOnInstaller.java:216)
        at org.zaproxy.zap.control.AddOnInstaller.install(AddOnInstaller.java:87)
        at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(AddOnLoader.java:432)
        at org.zaproxy.zap.control.AddOnLoader.addAddon(AddOnLoader.java:405)
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1043)
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(ExtensionAutoUpdate.java:499)
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(ExtensionAutoUpdate.java:442)
```

**Comment by thc202** [comment] 2018-04-01 14:28
Closing, duplicate of #2656.

**Closed by thc202** 2018-04-01 14:28 UTC
