### ISSUE TITLE
Proxy: Upstream HTTP Proxy: Connection to proxy via HTTPS, Handshake interrupted

### ISSUE THREAD

**Issue by w-wagner** [zaproxy/zaproxy#7711] opened 2023-01-30 17:57 UTC
### Describe the bug

Here we have a proxy, that listens to only one port and tunnels https via http. 
Browsers connect via TCP to the proxy, Issue CONNECT <targetsite>. Finally the handshake is done with the target site (tls extension servername => targetsite)

If I set the proxy within ZAP (options - network - connection - http proxy) I see ZAP connecting to the proxy and trying to send a ClientHello with the proxy name in the servername extension. The proxy closes the connection unanswered (ACK, then FIN). 

I conclude, ZAP tries to access the proxy via https, but it seems to listen to http only.

My suspicion was, that ZAP sets Javas http and https proxy at the same time. So I modified the ZAP.bat.
I defined the http.proxyHost and http.proxyPort BUT DID NOT define the httpS variants of these variables.

Then disabled the PROXY in the interface, restarted ZAP and it worked as expected.

### Steps to reproduce the behavior

1. Have a proxy that supports requests via http only
2. Maintain this proxy in Options - Network - Connections
3. Access an https site => ERROR

4. Remove proxy definition
5. Edit ZAP.bat to include -Dhttp.proxyHost=proxy -Dhttp.proxyPort=8080
6. Restart ZAP
7. Access the https site again => Works

### Expected behavior

Please allow separate definitions for http and https proxies. Behave like the browsers.

I will add/support a separate feature request to add "automatic" pac file search and usage. Our proxies are going to be phased out. Using the system settings is also a very useful option (ZScaler modifies the proxy system settings). Also add the possibility to add upstream proxy certificates to the castore of the current Java version. Had to do that manually.

### Software versions

OWASP ZAP 2.12

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-01-30 18:04
Are the add-ons up-to-date? What's the version of the Network add-on? Seems to be a duplicate of #7594.

**Comment by thc202** [comment] 2023-01-30 18:06
> I will add/support a separate feature request to add "automatic" pac file search and usage. 

#265

**Comment by w-wagner** [comment] 2023-01-30 18:59
Yes sounds similar to 7594. I hope I could add additional info. Sorry not finding it. I did not search hard enough...
I installed ZAP in the last two / three weeks but could not update the plugins, as described in 7594. Will check if new network plugin is available.
I come back. Thanks !

**Comment by w-wagner** [comment] 2023-01-31 12:04
The problem is gone. Following my computer log, I installed ZAP on this computer on 10.01.2023.
After updating all modules, using to the proxy works as expected.
Sorry for the noise.
Please close this issue.
Many thanks for your quick reaction!
Wolfram

**Comment by thc202** [comment] 2023-01-31 12:26
Thank you for checking and letting us know!

**Closed by thc202** 2023-01-31 12:26 UTC
Labels: bug, add-on
