### ISSUE TITLE
Sorting in websockets tab leads to UI glitches and high cpu consumption

### ISSUE THREAD

**Issue by alex1704** [zaproxy/zaproxy#5711] opened 2019-11-27 03:55 UTC
When there are many web sockets requests in history (i had few thousands of them), sorting by any field is not working.
[Screen Recording 2019-11-27 at 05.30.20.mov.zip](https://github.com/zaproxy/zaproxy/files/3894974/Screen.Recording.2019-11-27.at.05.30.20.mov.zip)

**Comment by thc202** [comment] 2019-11-27 11:59
Closing as duplicate of #1661.

**Closed by thc202** 2019-11-27 11:59 UTC
Labels: bug
