### ISSUE TITLE
Invalid JSON request generated from OpenAPI schema which uses "format: email"

### ISSUE THREAD

**Issue by unarist** [zaproxy/zaproxy#7128] opened 2022-03-08 12:15 UTC
### Describe the bug

ZAP automatically generates example values for each `type` and `format` specified in the OpenAPI definition.

However, ZAP generates invalid JSON for `format: email` property in the JSON request body:

```
{"string":"John Doe","email":foo-bar@example.com,"datetime":"1970-01-01T00:00:00.001Z","duration":"John Doe","uri":"John Doe"}
```

In this example, `foo-bar@example.com` should be quoted as well as other string properties.

### Steps to reproduce the behavior

1. Click `Import > Import an OpenAPI definition from the local file system`
2. Import below openapi.yaml
3. Open `http://example.com` > `POST:test()...` in the site tree
4. Check request body

openapi.yaml:
```yaml
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Sample API"
servers:
- url: http://example.com
paths:
  /test:
    post:
      summary: "Add a new pet to the store"
      description: "hoge"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                string:
                  type: string
                email:
                  type: string
                  format: email
                datetime:
                  type: string
                  format: date-time
                duration:
                  type: string
                  format: duration
                uri:
                  type: string
                  format: uri
      responses:
        200:
          description: "hoge"
          content:
            application/json: {}
```

### Expected behavior

ZAP generates correctly formatted JSON request body, even if `format: email` is specified.

### Software versions

```
OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=44.0.0], [id=automation,
version=0.13.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.3.0], [id=commonlib, version=1.8.0],
[id=diff, version=11.0.0], [id=directorylistv1,
version=5.0.0], [id=domxss, version=12.0.0], [id=encoder,
version=0.6.0], [id=exim, version=0.1.0], [id=formhandler,
version=4.0.0], [id=fuzz, version=13.6.0],
[id=gettingStarted, version=13.0.0], [id=graaljs,
version=0.2.0], [id=graphql, version=0.8.0], [id=help,
version=14.0.0], [id=hud, version=0.13.0], [id=importurls,
version=9.0.0], [id=invoke, version=11.0.0], [id=network,
version=0.1.0], [id=oast, version=0.10.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=26.0.0],
[id=pscanrules, version=39.0.0], [id=quickstart,
version=33.0.0], [id=replacer, version=9.0.0], [id=reports,
version=0.12.0], [id=retest, version=0.2.0], [id=retire,
version=0.10.0], [id=reveal, version=4.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=30.0.0], [id=selenium,
version=15.7.0], [id=soap, version=13.0.0], [id=spiderAjax,
version=23.7.0], [id=tips, version=9.0.0],
[id=webdriverwindows, version=36.0.0], [id=websocket,
version=24.0.0], [id=zest, version=35.0.0]]
---
Operating System: Windows 10
Java Version: Oracle Corporation 11.0.1
System''s Locale: ja_JP
Display Locale: ja_JP
Format Locale: ja_JP
ZAP Home Directory: C:\Users\andou_yuuta\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
見た目: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
```

### Screenshots

![image](https://user-images.githubusercontent.com/705555/157234574-0660f0a7-9f57-41a5-9c2e-cd1667c2a596.png)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment] 2022-03-08 12:19
This seems to be related to (if not a duplicate of): zaproxy/zaproxy#7115

**Closed** 2022-03-08 15:11 UTC
Labels: bug, add-on
