### ISSUE TITLE
API set default scan policy with GUI initiated active scans

### ISSUE THREAD

**Issue by jhowlett96** [zaproxy/zaproxy#6606] opened 2021-05-18 08:43 UTC
Hi,

I am using he API to prepare a scan using OWASP ZAP and have found that when I set my default scan policy using "ascan/action/setOptionDefaultPolicy/?String=policyName&apikey=123" then using the GUI I start a scan. In the scan pop up window my chosen default policy is selected in the policy tab however the rules are not correct (all set to default) and the scan will uses these incorrect values. I must open the drop down menu and when I reselect my policy the rules update to the correct ones.

Also if I have a policy called "Default Policy" in my policy list, the Default Policy is the selected policy in the scan pop up window, not the default policy I set using the API.

If I instead start a scan using the API "ascan/action/scan/?apikey=123&url=&recurse=&inScopeOnly=&scanPolicyName=&method=&postData=&contextId=2"
where I haven't given the API my policy, the policy set as my default policy is used and the rules are correct. Also if I have a policy called "Default Policy" it is not used. 

Regards,
Jake

**Comment by thc202** [comment] 2021-05-18 08:49
Closing as duplicate of #3538.

**Closed by thc202** 2021-05-18 08:49 UTC
Labels: bug
