### ISSUE TITLE
Alert Filter Addon: HTML report reports the filtered false positives as true results

### ISSUE THREAD

**Issue by hackthem** [zaproxy/zaproxy#2311] opened 2016-03-09 15:50 UTC
Hello guys,

I made several tests and realised that the tagged issues as false positives (through the api call or through the GUI) are reported as true positives.

Can you please deal with this bug ?

Best regards,

Abdellah AZOUGARH

**Comment by hackthem** [comment] 2016-03-09 15:51
This is a reference to the opened thread : https://groups.google.com/forum/#!topic/zaproxy-develop/PvsBdMvY0-Q

**Comment by thc202** [comment] 2016-03-09 15:54
How are you asserting that the alerts are tagged as false positive? Through the "Alerts" tab (i.e. shown with green flag)?

**Comment by psiinon** [comment] 2016-03-09 16:00
All bugs will be dealt with in time .. the question is when ;)
At the moment I'm (probably) the only person paid to work on ZAP (and I'm ridiculously busy) and so much of the work on ZAP is done by volunteers.
Individual bugs typically get addressed because a contributor thinks they are serious (or interesting) enough and are prepared to spend the time looking into them. So its probably better to try to justify why the bug is serious and needs fixing that just telling us it must be fixed. Or you could jump in and have a look at solving it yourself;)
It so happens that I'm planning on using the Context Alert Filters in the near future, in which case I'll have a strong incentive to make sure this does get fixed.
The fact that you also want to put this in the Jenkins plugin is also a good 'selling' point :)

**Comment by hackthem** [comment] 2016-03-09 16:20
I'm sure that dealing with this one will help by using ZAP Proxy through jenkins plugin. Most of companies will use ZAP Proxy through automated tools as jenkins plugin.
So this is my selling points ;)  : 
 -All the developers to home i presented ZAP Proxy and how to use with jenkins told me that they have to obtain a delta between two or three jobs and need to tag false positives.

-As you know the managers need also the information to see how the issues are dealt with and the only thing we can get when using ZAP as daemon is the report.

I hope you understand the importance of the fix ;).

thc202 : the alerts are shown with green flag .

Thank you all for your help.

Best regards,

Abdellah AZOUGARH

**Comment by kingthorin** [comment] 2016-03-09 16:52
I'm confused what the issue is here. If I edit alerts and set Confidence as "False Positive" I do not see them in the HTML report. [2.4.3]

What version of ZAP are you using and how are you generating the report?

**Comment by hackthem** [comment] 2016-03-09 18:08
Okay this is my scenario : 
-I create a context and specify all necessary parameters
-I create a set of false positives (via alert filters) before launching the scan as i identified them before 
-I launch the spidering and the scan 
-I remark that the false positives are shown with a green flag 
-I try to generate the report and then i remark that the false positives are shown as true positives


This issue is identifier via the scenario above or by using the GUI or the api call

Thank you for your help.

Regards,

Abdellah AZOUGARH

**Comment by hackthem** [comment] 2016-03-09 18:08
I am using the version : 2.4.3

**Comment by psiinon** [comment] 2016-03-09 18:17
I can confirm this happens.
Alerts converted to False Positives in the UI still appear in the HTML report with the original level.
Interestingly they are not returned via the API core/alerts view.
Looks like the problem is that they are also in the Sites tree and those ones have NOT been converted, and I think the report uses the Sites tree.

**Comment by thc202** [comment] 2016-03-09 18:22
Seems to be a duplicate of #2132.

**Comment by thc202** [comment] 2016-03-09 18:24
(The source of the problem is the same.)

**Comment by psiinon** [comment] 2016-03-09 18:35
Note that if you change an alert in the alert tab to be a False Positive it _does_ get correctly updated in the Sites tab.

**Comment by psiinon** [comment] 2016-03-09 18:35
I'll look into this soon unless someone else beats me to it ;)

**Comment by hackthem** [comment] 2016-03-09 18:48
Thank you guys ;)

**Comment by kingthorin** [comment] 2016-03-10 14:54
It should also be noted here (and likely in the help docs) that the alert filter only applies the filter rules on a go forward basis (not retro actively). So if you have alerts when you setup the rules the GUI (alert tab) doesn't update, but if you then browse or test further and encounter items that do match the filter rules those items will have the new settings/config applied.

**Comment by thc202** [comment] 2016-03-15 12:31
Fixed in zaproxy/zap-extensions#278.

**Closed by thc202** 2016-03-15 12:31 UTC
Labels: add-on, bug
