### ISSUE TITLE
Reports not being generated by ZAProxy Plugin in jenkins

### ISSUE THREAD

**Issue by iamanupmenon** [zaproxy/zaproxy#1878] opened 2015-09-09 05:19 UTC
Hello 

I created a new job and used ZAProxy plugin in jenkins. The plugin properly worked and it was scanning the site and took around 3 hours for complete scan. The console output showed 

Status scan = 85%
Alerts number = 		ApiResponseElement numberOfAlerts = 819

Messages number = 		ApiResponseElement numberOfMessages = 13999

But the report generted was empty.

![image](https://cloud.githubusercontent.com/assets/6698132/9753886/4573793c-56e0-11e5-9d9b-5ddbe46bf727.png)

**Comment by thilina27** [comment] 2015-09-09 05:39
Im not a dev of the plugin but as i know there was a problem in ZAP early version . 

What ZAP version are you using? not the plugin version .

**Comment by iamanupmenon** [comment] 2015-09-09 05:44
@thilina27 i used custoom tool plugin to install zap during build. And the version is ZAP_2.4.0

**Comment by thilina27** [comment] 2015-09-09 06:29
ZAP 2.4.2 is now release ans it has fixed most o the issue [1]

I have also modify the zaproxy-plugin for authentication and ajax spider [2] 

[1] - https://github.com/zaproxy/zaproxy/wiki/Downloads
[2] - https://github.com/thilina27/zapauthentication

**Comment by iamanupmenon** [comment] 2015-09-09 07:19
No @thilina27 now the job failed 
It says 

5278 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
URL Not Found in the Scan Tree (url_not_found)

I have added a command line option
![image](https://cloud.githubusercontent.com/assets/6698132/9755622/0ad78b18-56f1-11e5-82f2-917c079d85c5.png)

**Comment by thilina27** [comment] 2015-09-09 07:21
Try to download zap and set up zap home and try .

**Comment by thc202** [comment] 2015-09-09 08:28
Is that happening while active scanning? If so, that means that you tried to active scan a target without accessing it first (proxied/spidered or by other means).

**Comment by logancarmody** [comment] 2015-09-10 20:06
just a thought... my reports weren't being generated in 2.4.1 either... but I could get the JSON reports. So I just made my own html wrapper for the JSON alerts

**Comment by kingthorin** [comment] 2015-09-10 22:08
See https://github.com/zaproxy/zaproxy/issues/1792 and https://github.com/zaproxy/zap-core-help/wiki/HelpReleases2_4_2

**Comment by iamanupmenon** [comment] 2015-09-12 05:16
Hello all ,

As per ur suggestion @thc202 i started spider first and then scan test and now the reports are being generated, But now the problem i am facing is, The reports generated while i run in my machine through ZAP is different than the report being generated here in jenkins. I cannot see HIGH and INFORMATIONAL risk in Jenkins whereas i can see some HIGH priority risks generated while is run it in my machine from ZAP GUI

**Comment by thilina27** [comment] 2015-09-12 05:42
Have you check the URLs that has those issue. i have use firefox to proxy the site and i got some Mozilla links in my report also. other than my reports are identical to each other.

**Comment by iamanupmenon** [comment] 2015-09-12 06:13
yes i have checked 
its valid URL 
URLs are from my site only

**Comment by thilina27** [comment] 2015-09-12 13:41
same version of ZAP?

**Comment by thc202** [comment] 2015-09-13 23:50
And same add-ons?

**Comment by iamanupmenon** [comment] 2015-10-16 05:48
Sorry for the late reply 
and yes the version is 2.4.2
and the reports i run locally and from jenkins are different 

apart from that 
i also have another website which has http authentication 
how to pass this from zapProxy plugin

**Comment by thilina27** [comment] 2015-10-16 06:09
Hi 
the new plugin version of zapprxy jenkins plugin [1] is available and it has authentication feature for form based authentication. 
You can find the configuration also in the jenkins wiki page. 

[1] - https://wiki.jenkins-ci.org/display/JENKINS/ZAProxy+Plugin

**Comment by thc202** [comment] 2015-11-13 14:11
Closing as duplicate of #1792.

@iamanupmenon if you still have issues with the alerts being different let us known in a new issue or in the users mailing list. [1]

[1] https://groups.google.com/group/zaproxy-users

**Closed by thc202** 2015-11-13 14:11 UTC
Labels: bug, duplicate
