### ISSUE TITLE
OpenAPI warns/errors while spidering

### ISSUE THREAD

**Issue by a108a108** [zaproxy/zaproxy#5857] opened 2020-02-12 06:19 UTC
Hello,
i am using python with owasp-zap-v2.4 module to automate scans, since started to use docker with 2.9.0 i am seeing errors like this:
```
[ZAP-SpiderThreadPool-0-thread-2] WARN io.swagger.parser.util.DeserializationUtils  - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
        at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
        at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
        at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
        at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:156)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:139)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:133)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:195)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: unacceptable code point '?' (0x95) special characters are not allowed
in "'string'", position 480
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1861)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1841)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1027)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1009)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:394)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:640)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
        ... 18 more
70369 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit end
70507 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
70507 [HSQLDB Timer @10d59286] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end - txts: 55606
38% spider
75369 [ZAP-SpiderThreadPool-0-thread-2] WARN io.swagger.parser.util.DeserializationUtils  - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
        at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
        at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
        at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
        at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:156)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:139)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:133)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:195)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: unacceptable code point '?' (0x95) special characters are not allowed
in "'string'", position 480
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1861)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1841)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1027)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1009)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:394)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:640)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
        ... 18 more
66% spider
82500 [ZAP-SpiderThreadPool-0-thread-1] WARN io.swagger.parser.util.DeserializationUtils  - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
        at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
        at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
        at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
        at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:156)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:139)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:133)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:195)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: while scanning a tag
 in 'string', line 1, column 1:
    !function(e){var i={};function o ...
    ^
expected ' ', but found '{' (123)
 in 'string', line 1, column 13:
    !function(e){var i={};function o(n){if(i[n]) ...
                ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.scanTag(ScannerImpl.java:1556)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchTag(ScannerImpl.java:954)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:372)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
        ... 18 more
82507 [ZAP-SpiderThreadPool-0-thread-1] ERROR io.swagger.parser.SwaggerCompatConverter  - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('!' (code 33)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"!function(e){var i={};function o(n){if(i[n])return i[n].exports;var t=i[n]={i:n,l:!1,exports:{}};return e[n].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=e,o.c=i,o.d=function(n,t,e){o.o(n,t)||Object.defineProperty(n,t,{configurable:!1,enumerable:!0,get:e})},o.r=function(n){Object.defineProperty(n,"__esModule",{value:!0})},o.n=function(n){var t=n&&n.__esModule?function(){return n.default}:function(){return n};return o.d(t,"a",t),t},o.o=function(n,t){return Object.prototype.hasOwnProperty.ca"[truncated 820 chars]; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:114)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertV1ToV2(SwaggerConverter.java:216)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:197)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
84152 [ZAP-SpiderThreadPool-0-thread-1] WARN io.swagger.parser.util.DeserializationUtils  - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:300)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
        at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:137)
        at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:83)
        at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:125)
        at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:156)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:139)
        at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:133)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:195)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: mapping values are not allowed here
 in 'string', line 17, column 15158:
     ... endesk.com with your account key: "+u.ACCOUNT_KEY)},getAuthLogin ...
                                         ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:869)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
        at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:87)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
        at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:279)
        ... 18 more
84161 [ZAP-SpiderThreadPool-0-thread-1] ERROR io.swagger.parser.SwaggerCompatConverter  - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('(' (code 40)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:114)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertV1ToV2(SwaggerConverter.java:216)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:197)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:170)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:157)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:55)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
        at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
These errors was not present in 2.8.0, everything seems to work tho,  scans and reporting are working and i don't see something that is not okay besides the log.

**Comment by thc202** [comment] 2020-02-12 07:14
Those warns/errors are expected and cause no harm other than polluting the log.

Closing as duplicate of #5725.

**Closed by thc202** 2020-02-12 07:14 UTC
Labels: add-on, duplicate
