### ISSUE TITLE
Conflicting Selenium and Chromedriver versions when using Chrome with Docker image

### ISSUE THREAD

**Issue by acardnell-intruder** [zaproxy/zaproxy#8309] opened 2024-01-17 17:28 UTC
### Describe the bug

I'm trying to configure a Docker image to use Chrome following the steps outlined here:

https://www.zaproxy.org/faq/how-do-i-use-chrome-with-zap-in-docker/

However I'm running into issues, because Selenium v4.15 expects Chrome version v117, v118, and v119, but the Chromedriver installed expects v120.

### Steps to reproduce the behavior

I created my own Dockerfile using the following:

```
ARG ZAP_VERSION=2.14.0

FROM --platform=linux/amd64 softwaresecurityproject/zap-stable:${ZAP_VERSION}

ARG CHROME_VERSION=120.0.6099.216-1

USER root

RUN apt-get update && \
    wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
    apt-get install -y ./google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

USER zap
```

When I try to run the AJAX spider via the API, I get the following error:

```
[ZAP-AjaxSpiderApi] WARN  org.openqa.selenium.devtools.CdpVersionFinder - Unable to find an exact match for CDP version 120, returning the closest version; found: 119; Please update to a Selenium version that supports CDP version 120
```

If I try updating the Dockerfile to downgrade the Chrome version to `119.0.6045.199-1` then I get a different error, this time from the Chromedriver:

```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 120
```

Finally I also tried installing a compatible Chromedriver version `119.0.6045.199`, and although this gets past the other hurdles it only runs briefly before eventually crashing with another error:

```
[pool-2-thread-3] WARN  com.crawljax.browser.WebDriverBackedEmbeddedBrowser - Could not get the dom
org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools
```

### Expected behavior

I would like to be able to launch both the AJAX spider, and the CSS DOM-based check, with a Chrome browser. 

The reason I need to do this is I have a custom Selenium script that needs to make use of the Selenium `executeCdpCommand` function, which is only available with Chrome, because I need to insert tokens into the local storage for a domain before the page loads, otherwise it gets redirected to a login page on a different domain (and thus too late to add the tokens).

### Software versions

I tried this using the versions shown in the Dockerfile, and for reference I was interacting with the API using version `0.1.0` of the `zaproxy` Python library.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2024-01-17 17:56
Did you try the weekly? That one has a newer Selenium version.

**Comment by acardnell-intruder** [comment] 2024-01-17 19:43
@thc202 I hadn't - I've just tried it now. I'm no longer receiving any errors, but it also doesn't seem to the spidering correctly either. Polling for AJAX results returns `0`, and when it eventually completes and I try to run an Active scan (after running the Traditional + AJAX spider) I get the following crash error:

```
2024-01-17 19:38:29 59953 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Running Crawljax (with chrome-headless): API - Context: default
2024-01-17 19:38:29 59969 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Starting proxy...
2024-01-17 19:38:29 59984 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Proxy started, listening at port [35473].
2024-01-17 19:38:30 60283 [ZAP-AjaxSpiderApi] INFO  com.crawljax.core.plugin.Plugins - Loaded org.zaproxy.zap.extension.spiderAjax.SpiderThread$DummyPlugin@6fd3216e as a OnBrowserCreatedPlugin
2024-01-17 19:39:46 136260 [ZAP-AjaxSpiderApi] INFO  com.crawljax.core.CrawlController - Received shutdown notice. Reason is Exausted
2024-01-17 19:39:46 136382 [ZAP-AjaxSpiderApi] INFO  com.crawljax.core.CrawlController - Shutdown process complete
2024-01-17 19:39:46 136382 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Stopping proxy...
2024-01-17 19:39:46 136399 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Proxy stopped.
2024-01-17 19:39:46 136408 [ZAP-AjaxSpiderApi] INFO  org.zaproxy.zap.extension.spiderAjax.SpiderThread - Finished Crawljax: API - Context: default
2024-01-17 19:39:51 141656 [ZAP-IO-Server-1-2] INFO  org.parosproxy.paros.core.scanner.Scanner - scanner started
2024-01-17 19:39:51 141789 [ZAP-IO-Server-1-2] ERROR org.zaproxy.zap.extension.api.API - Exception while handling API request:
2024-01-17 19:39:51 java.util.ConcurrentModificationException: null
2024-01-17 19:39:51 at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
2024-01-17 19:39:51 at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiView(ActiveScanAPI.java:1035) ~[zap-D-2024-01-16.jar:D-2024-01-16]
2024-01-17 19:39:51 at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:557) ~[zap-D-2024-01-16.jar:D-2024-01-16]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
2024-01-17 19:39:51 at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
2024-01-17 19:39:51 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2024-01-17 19:39:51 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2024-01-17 19:39:51 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.14.0.zap:?]
2024-01-17 19:39:51 at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by thc202** [comment] 2024-01-18 08:37
Which API call are you using for the AJAX Spider results?

For the Active Scan call that's a bug but calling the endpoint again it would work.

**Comment by acardnell-intruder** [comment] 2024-01-18 09:14
@thc202 - I'm polling the `ajaxSpider.number_of_results` endpoint, which always returns `0`. I just double-checked in the Python console as well and got the following for a ZAP instance after running the AJAX spider with Chrome:

```python
scanner.zap.ajaxSpider.number_of_results
Out[5]: '0'
scanner.zap.ajaxSpider.results()
Out[6]: []
```

The Active Scan seems to work this morning 🤷

**Comment by acardnell-intruder** [comment] 2024-01-31 12:54
And here's the Firefox recording:


https://github.com/zaproxy/zaproxy/assets/103442492/71e904c8-1ec0-41ae-9ee9-bc4276f21887

(It jumps a bit in a few places because I had to cut it a bit to get it under 10MB).

**Comment by acardnell-intruder** [comment] 2024-02-01 15:53
Right I think I finally have this working more or less. I thought I'd detail the issues I hit and how I fixed them incase it is of use to anyone in the future.

### Chrome + HTTP redirect

This is the one I faced above. It seems like Chrome automatically redirects HTTP to HTTPS, which was out-of-scope for the ZAP context configuration I had, and thus ended the session. Firefox doesn't do this. By updating the front of the inclusion regex to `http[s]?` and making `https` accepted but optional, everything seems to work.

I still think this is a bug because it forces me to allow a scheme I didn't want / need, but happy to continue with the workaround for now.

### Multiple Chrome instances failing to start

The GUI and Automation Framework test both set `Number of Browsers` to `1`, however, the API via Docker defaults to `16`. When trying to run the AJAX spider with Chrome, I found I kept getting this error:

```org.openqa.selenium.NoSuchSessionException: invalid session id```

I fixed this by following [this advice](https://github.com/markhobson/docker-maven-chrome?tab=readme-ov-file#chrome-crashes) and adding `-config selenium.chromeArgs.arg.argument=--disable-dev-shm-usage` to my startup command.

### Sandbox issue

Finally, I also had an issue with Chrome and Docker permissions, it looked a little like this:

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

This is an issue with Chrome trying to create a sandbox in Docker and not having the necessary permissions. You can fix this by adding `-config selenium.chromeArgs.arg.argument=--no-sandbox`; however, this isn't advised for security reasons and instead I added my own security policy configuration (something akin to `--security-opt seccomp=$(pwd)/chrome.json`) as [advised here](https://github.com/Zenika/alpine-chrome?tab=readme-ov-file#-the-best-with-seccomp).

**Comment by kingthorin** [comment] 2024-02-01 16:09
Thanks for following up and providing such great detail!!! Wonderful!

Re: The context regex, you can drop the square brackets the question mark will only apply to the preceding token (the s).
https://www.regexplanet.com/share/index.html?share=yyyyfpma03r
(Click 'Java')

**Comment by acardnell-intruder** [comment] 2024-02-01 16:45
> Thanks for following up and providing such great detail!!! Wonderful!
> 
> Re: The context regex, you can drop the square brackets the question mark will only apply to the preceding token (the s). https://www.regexplanet.com/share/index.html?share=yyyyfpma03r (Click 'Java')

Ah yes - nice idea, thanks!

**Comment by thc202** [comment] 2024-02-19 20:04
Closing, the original issue was caused by the use of outdated add-on versions.

**Closed by thc202** 2024-02-19 20:04 UTC

**Comment by thc202** [comment] 2024-02-19 20:11
For the record, there's a FAQ entry related to Docker usage: https://www.zaproxy.org/faq/how-do-i-use-chrome-with-zap-in-docker/ (Not sure if worth updating with any of the observations?)

**Comment by acardnell-intruder** [comment] 2024-02-20 13:03
> For the record, there's a FAQ entry related to Docker usage: https://www.zaproxy.org/faq/how-do-i-use-chrome-with-zap-in-docker/ (Not sure if worth updating with any of the observations?)

Not sure if that was a question to me @thc202 but yes, feel free to include my findings in the FAQ 👍 

For the record, although `-config selenium.chromeArgs.arg.argument=--disable-dev-shm-usage` did work, I actually opted to increase the shared memory for the container with `shm_size` in the end (I went with 4GB based on [this recommendation](https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#--shm-size2g)), since disabling shared memory usage forces the container to use the `/tmp` directory, which is slower.
