### ISSUE TITLE
Delay When Scanning has no effect

### ISSUE THREAD

**Issue by W0lfbane** [zaproxy/zaproxy#7929] opened 2023-06-30 21:53 UTC
### Describe the bug

No matter what value I set in the active scanner option "delay when scanning", there is no change in the time between requests. I have set this value to ridiculous times such as 999999999 ms but the scan always performs as if the value were 0. 

### Steps to reproduce the behavior

1. Set delay when scanning to a large time in ms
2. Run the scan

### Expected behavior

I expected some sort of rate limiting to occur

### Software versions

OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=16.0.0],
[id=ascanrules, version=55.0.0], [id=authhelper,
version=0.8.0], [id=automation, version=0.29.0],
[id=bruteforce, version=13.0.0], [id=callhome,
version=0.6.0], [id=commonlib, version=1.14.0],
[id=communityScripts, version=17.0.0], [id=custompayloads,
version=0.12.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=directorylistv2_3, version=4.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0], [id=exim,
version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz,
version=13.9.0], [id=fuzzdb, version=9.0.0],
[id=fuzzdboffensive, version=4.0.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.17.0], [id=help, version=15.0.0], [id=hud,
version=0.16.0], [id=importurls, version=9.0.0], [id=invoke,
version=12.0.0], [id=jython, version=12.0.0], [id=network,
version=0.9.0], [id=oast, version=0.15.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=34.0.0],
[id=pscanrules, version=49.0.0], [id=quickstart,
version=37.0.0], [id=replacer, version=12.0.0], [id=reports,
version=0.22.0], [id=requester, version=7.2.0], [id=retest,
version=0.5.0], [id=retire, version=0.23.0], [id=reveal,
version=5.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=38.0.0], [id=selenium, version=15.12.1], [id=soap,
version=17.0.0], [id=spider, version=0.4.0], [id=spiderAjax,
version=23.14.1], [id=tips, version=10.0.0],
[id=webdriverlinux, version=56.0.0], [id=websocket,
version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 17.0.6
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/kali/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![Screenshot from 2023-06-30 14-52-20](https://github.com/zaproxy/zaproxy/assets/3799912/ab360e9b-155c-43f1-9fef-95ce4a5d310a)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2023-06-30 21:59
I believe there's already an issue open for this. I believe it has to do with a timing issue. Of when the Global options are applied vs. the scan specific options.

When you start a scan try going to the advanced options and setting the value(s) there.

**Comment by W0lfbane** [comment] 2023-06-30 22:09
@kingthorin Thanks for your reply. I can try that though when I do Attack > Active Scan > Show Advanced Options I'm not seeing anything regarding a delay. Is there a different window I should be trying? (Or maybe I'm blind?)

**Comment by kingthorin** [comment] 2023-06-30 22:23
No that’s where I was thinking. You might have to set it, close zap, and then use it.

**Comment by W0lfbane** [comment] 2023-06-30 22:31
Unfortunately that doesn't seem to work either. If there's a config file or some code I can edit to achieve this I'm willing to do that as well. I'm not very familiar with the source code on here so I'd need a pointer if so.

**Comment by kingthorin** [comment] 2023-06-30 22:44
I’ll have to play with it over the weekend. I’ve definitely had it working in the past.

Code wise there is a more generic throttling solution coming as Active Scan is currently the only component that has such settings.

**Comment by thc202** [comment] 2023-07-01 12:06
Closing as duplicate of #4550.

**Closed by thc202** 2023-07-01 12:06 UTC
Labels: bug, duplicate, Component-UI

**Comment by thc202** [comment] 2023-07-01 12:08
Ensure you reset the Active Scan dialogue after doing changes in the Options dialogue.

**Comment by W0lfbane** [comment] 2023-07-10 16:47
@thc202 That does not seem to have any effect I'm afraid. I did find a workaround however, in case anyone else needs to achieve this before the next patch. You can simply create an HTTP Sender script (I chose python) and use a sleep function there which will enforce the delay for each request.

**Comment by thc202** [comment] 2023-07-10 17:19
It does, I verified it. Either way the upcoming main release will have this option deprecated.
