### ISSUE TITLE
Allow to active scan a Context through ZAP API

### ISSUE THREAD

**Issue by dap** [zaproxy/zaproxy#1853] opened 2015-08-27 04:34 UTC
There appears to be no way to specify a list of technologies when invoking an active scan via the REST API. I think it would be beneficial if there was greater parity with the graphical UI in this respect, to allow for more specific scan targeting.

**Comment by psiinon** [comment] 2015-08-27 07:59
You can configure the technologies associated with a context via the 'context' component, and then specify that context when starting the active scan.
Hopefully that will meet your requirements?

**Comment by dap** [comment] 2015-08-27 08:27
I looked through the code base to determine where the technologies are pulled from the Context and passed to the ActiveScanController. It appears that this only happens when a user is specified. See https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/ascan/ActiveScanAPI.java#L542

**Comment by psiinon** [comment] 2015-08-27 08:43
We need to fix that then - you should definitely be able to scan a context without specifying a user.

**Comment by dap** [comment] 2015-08-27 08:45
I put together a patch that merges contexts then sets them manually. It's referenced from this ticket and I'll send a pull request.

**Comment by thc202** [comment] 2015-09-08 08:05
I've to disagree with assessment of the issue, the problem is not that the technologies are not set, the problem is that it's not possible to specify a context (which has its technologies).
I think the API should be changed to specify a context not to set the technologies of the contexts, it will be more consistent with the functionalities provided in GUI.
Not saying that the API should not allow to specify the technologies used in the scan (it should be possible like it is in GUI with "Technology" tab in "Active Scan" dialogue).

**Comment by dap** [comment] 2015-09-10 17:54
The API already allows for the specification of a context -- multiple contexts, in fact -- via the combination of importContext and setContextInScope. Were the API to be modified in the way that you indicate, there would still need to be code changes to respect the context-selected technologies at scan time. This is the reason for the referenced patch merging TechSet's. A given target may appear in scope in multiple contexts.

And I concur that it would be reasonable and intuitive to have the API function similarly to the active scan GUI. In such case, I think that the API should respect the technology selections in both the context and active scan configuration.

**Comment by thc202** [comment] 2015-09-10 18:21
Sorry for not being clear, I was talking about the active scan API, not the ZAP API as whole.
The active scanner already uses the technologies of the specified context, no other changes would be required other than change active scan API to allow to specify the context.

Regarding the target appearing in multiple contexts, well it's possible but I wonder how would that work in practice (i.e. authentication, authorisation, structural parameters). As said in the review of the pull request, in other cases where a context is selected for a given target it's just used the first one.

**Comment by dap** [comment] 2015-09-10 18:45
My read of the code indicates that the active scanner does not already use the technologies specified in the context. That is the reason for this bug and accompanying patch. I observed that selected technologies are only respected when scanning as a specific user. When not scanning as a specific user, no technologies are used. This was corroborated by code review as well as observation of generated traffic at runtime. Are you saying that this observation is incorrect?

**Comment by thc202** [comment] 2015-09-11 15:28
What I'm saying is that it's not possible (and should be) to specify a context (therefore it's technologies) through the active scan API.
The active scanner does use the technologies of the specified context. [1]

[1] https://github.com/zaproxy/zaproxy/blob/8e7a8ed4ad897ba481379e6c283ef87bc2a5ee08/src/org/zaproxy/zap/extension/ascan/ActiveScanController.java#L153

**Comment by thc202** [comment] 2016-11-24 15:09
Updated the issue to allow to specify a context when starting the active scan through the ZAP API (per comments in #1855).

**Comment by thc202** [comment] 2016-11-24 15:13
Merged #2722 into this issue, as pointed out, the URL should not be required when a context is specified (as proposed in this issue and when active scanning as a user).

**Closed** 2016-12-04 19:50 UTC
Labels: Component-API, enhancement
