### ISSUE TITLE
File Upload addon - Java error

### ISSUE THREAD

**Issue by RADarkflow** [zaproxy/zaproxy#6952] opened 2021-11-27 19:18 UTC
**Describe the bug**
I get Java errors when i try to replicate the video mentioned in:  https://www.zaproxy.org/blog/2021-08-20-zap-fileupload-addon/ 

**To Reproduce**
1. Go to 'Tools -> Options -> File Upload'
2. Click on 'File Upload'
3. fill up the fields "Start Identifier" and "End Identifier" with {"fileNameWithPath":" and "} 
4. Click OK button.  
5. then I get the following error "Internal Error" 

Internal Error
 

Message:
    java.lang.NullPointerException
Level:
    SEVERE
Stack Trace:
null
    org.zaproxy.zap.extension.selenium.SeleniumOptions.setBrowserExtensions(SeleniumOptions.java:391)
    org.zaproxy.zap.extension.selenium.SeleniumOptionsPanel.saveParam(SeleniumOptionsPanel.java:422)
    org.parosproxy.paros.view.AbstractParamContainerPanel.saveParam(AbstractParamContainerPanel.java:681)
    org.parosproxy.paros.view.AbstractParamDialog.saveParam(AbstractParamDialog.java:387)
    org.parosproxy.paros.view.AbstractParamDialog$1.actionPerformed(AbstractParamDialog.java:218)
    java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
    java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
    java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    java.desktop/java.awt.Component.processEvent(Component.java:6400)
    java.desktop/java.awt.Container.processEvent(Container.java:2263)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
    java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
    java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
    java.desktop/java.awt.Dialog.show(Dialog.java:1070)
    java.desktop/java.awt.Component.show(Component.java:1716)
    java.desktop/java.awt.Component.setVisible(Component.java:1663)
    java.desktop/java.awt.Window.setVisible(Window.java:1031)
    java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
    org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:136)
    org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:445)
    org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:73)
    org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:64)
    org.parosproxy.paros.view.MainMenuBar$3.actionPerformed(MainMenuBar.java:238)
    java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
    java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
    java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
    java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
    java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
    java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
    java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
    java.desktop/java.awt.Component.processEvent(Component.java:6400)
    java.desktop/java.awt.Container.processEvent(Container.java:2263)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    java.base/java.security.AccessController.doPrivileged(Native Method)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Expected behavior**
Saving the detection setting correctly 

**Screenshots**

**Software versions**
 - ZAP: 2.11.0
 - Add-on: FileUpload 1.1.0 
 - OS: 
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"

 - Java: openjdk version "11.0.12" 2021-07-20 LTS

 - Browser: 

**Errors from the zap.log file**
 9638 2021-11-27 20:57:26,848 [AWT-EventQueue-0] ERROR AbstractParamContainerPanel - Failed to save the panel:

**Additional context**

**Would you like to help fix this issue?**
yes

**Comment by thc202** [comment] 2021-11-27 19:29
Closing as duplicate of #6951.

**Closed by thc202** 2021-11-27 19:29 UTC
Labels: duplicate, add-on
