### ISSUE TITLE
progress stuck afer complete one process

### ISSUE THREAD

**Issue by L-Shier** [zaproxy/zaproxy#7651] opened 2022-12-14 03:19 UTC
### Describe the bug

if one process is complete, the progress will be stuck, the 'pause' and 'stop' button will disabled, and this issue always happen

### Steps to reproduce the behavior

1.just start a default active scan

### Expected behavior

the scan complete successfully

### Software versions

2.12.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment] 2023-03-24 16:44
Closing as duplicate of #7579.

**Closed by thc202** 2023-03-24 16:44 UTC
Labels: bug
