### ISSUE TITLE
First time running

### ISSUE THREAD

**Issue by SnXe** [zaproxy/zaproxy#5735] opened 2019-12-04 02:51 UTC
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.zaproxy.zap.GuiBootstrap (file:/snap/zaproxy/4/zap-2.8.0.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of org.zaproxy.zap.GuiBootstrap
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This is printed out to stdout on the terminal before zap is launched.
Ubuntu 18.04
5.0.0-36-generic
x86

**Comment by kingthorin** [comment] 2019-12-04 02:59
Thanks for letting us know @SnXe 

It is a known [issue](https://github.com/zaproxy/zaproxy/issues/5359), that we will be working to fix in a future release.

Closing as duplicate of zaproxy/zaproxy#5359

**Closed by kingthorin** 2019-12-04 02:59 UTC
Labels: duplicate
