### ISSUE TITLE
Document "riskdesc" in reports

### ISSUE THREAD

**Issue by agardnerIT** [zaproxy/zaproxy#7445] opened 2022-09-06 00:47 UTC
As [per discussion here](https://groups.google.com/g/zaproxy-users/c/jZSDq8rGAc0), the risk description is given as `Low (Medium)` but what this means isn't documented yet.

What this means is a `Low` risk issue has been detected with `Medium` confidence.

This issue is to document this somewhere that makes sense. It should be a fairly easy update so please mark as a `good first issue`.

**Comment by thc202** [comment] 2022-09-06 00:58
Is there any (new) report still using that?

**Comment by agardnerIT** [comment] 2022-09-06 01:27
I am printing hte JSON output from teh docker report and that contains it.

**Comment by thc202** [comment] 2022-09-06 02:31
Thank you, those are the traditional reports. We should just remove that field…

**Comment by agardnerIT** [comment] 2022-09-07 21:19
Thanks @thc202. When you say "they are traditional reports", I want to build a new integration that uses the docker output. Is there a better / newer / more suitable report to use and if so, how would "configure that" to be given as output?

My current use case is that I need the detection summary and I'm going to use those numbers to push somewhere.

For example:
```
High: 2
Medium: 3
Low: 0
Informational: 10
```

**Comment by psiinon** [comment] 2022-09-08 07:51
The latest reports are detailed on https://www.zaproxy.org/docs/desktop/addons/report-generation/templates/

**Comment by thc202** [comment] 2022-09-08 08:10
The API endpoint `/JSON/alert/view/alertCountsByRisk/` will give you that summary.

**Comment by devyloper** [comment] 2022-10-01 04:48
I would like to work on this issue. May I get this assigned to me? Thanks.

**Comment by psiinon** [comment] 2022-10-04 12:42
The report add-on help is available online at https://www.zaproxy.org/docs/desktop/addons/report-generation/
Each report is documented in links off https://www.zaproxy.org/docs/desktop/addons/report-generation/templates/
Have a look at the report samples and see which ones report alerts like `Low (Medium)`
Those are the ones which will need the documenting.
I think you can document that on the relevant help page for each report, they live under https://github.com/zaproxy/zap-extensions/tree/main/addOns/reports/src/main/javahelp/org/zaproxy/addon/reports/resources/help/contents

**Comment by sidejackthenativity** [comment] 2022-12-19 13:49
Devyloper, Are you still working on this issue? If so, would you like some help?

**Comment by kingthorin** [comment] 2022-12-19 13:56
This isn't a huge change, at this point since the issue isn't closed I'd suggest you just go ahead and do it @sidejackthenativity

**Comment by sidejackthenativity** [comment] 2022-12-20 13:26
Hi there. I found the report templates where this ambiguity is occurring. The thread seems to suggest we add clarity to the template samples themselves. Would it be better to put it in the https://www.zaproxy.org/docs/desktop/addons/report-generation/#filter-fields page with a new header and explanation?

**Comment by kingthorin** [comment] 2022-12-20 16:53
Sure open a PR, once we agree on the wording you can add it to all of the pages it applies to.

**Closed** 2023-01-17 05:42 UTC
Labels: Component-Docs, IdealFirstBug, good first issue
