### ISSUE TITLE
Feature Request: add scanID support to StopAjaxSpider

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6063] opened 2020-07-07 09:02 UTC
**Is your feature request related to a problem? Please describe.**
Currently the API call to stop the AJAX spider does not support a scanID parameter.
I am not sure whether this is by design.

https://github.com/zaproxy/zap-extensions/blob/ec25f80911d8173b11b6cf250b8f8d7b2bd57895/addOns/spiderAjax/src/main/java/org/zaproxy/zap/extension/spiderAjax/AjaxSpiderAPI.java#L171

**Comment by thc202** [comment] 2020-07-07 09:32
The AJAX Spider does not currently support multiple scans, so no ID is needed/used (yet). Closing as duplicate of #1954.

**Closed by thc202** 2020-07-07 09:32 UTC
Labels: enhancement
