### ISSUE TITLE
Support throttling in Spider

### ISSUE THREAD

**Issue by slicedpan** [zaproxy/zaproxy#7309] opened 2022-05-30 10:54 UTC
### Is your feature request related to a problem? Please describe.

The Spider does not support throttling, so is always set to make requests as fast as it can. In some cases this is undesirable, as this can cause availability issues with brittle targets.

### Describe the solution you'd like

The spider should support a *delayInMs* parameter (like the active scanner), which will delay requests by the given value to reduce the load on target web applications.

### Describe alternatives you've considered

It's possible to replicate this behaviour by running ZAP through another proxy that supports throttling, but this is clunky.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment] 2022-05-30 10:57
Sounds good to me :) Would you like to be assigned this issue?

**Comment by slicedpan** [comment] 2022-05-30 10:59
Sure.

**Comment by thc202** [comment] 2022-05-30 11:03
Duplicate of #1314 but I guess we can keep this one.

**Comment by thc202** [comment] 2022-07-05 14:13
This should be done in the add-on now, located in `zap-extensions` repo.

**Comment by task4233** [comment] 2022-10-01 07:45
Hello, @slicedpan 

Thank you for your making this issue!
Actually, I have wanted to use this feature, too.

Then, how is it going on this task?
If it's hard for you to try this task, I would like to try this task :)

I apologize for this suggestion if you are mid-way through this task.

**Comment by thc202** [comment] 2022-10-01 08:06
fwiw, there's an add-on in progress providing this more generally: zaproxy/zap-extensions#4011.

**Comment by thc202** [comment] 2023-08-16 08:02
Closing as done with the global rate limiting, while adding per scan/tool seems useful it does not actually allow to enforce the limits (as the user can easily/accidentally exceed them, e.g. active scan, manual).

Feel free to leave a comment explaining the use case if you still think having per scan is useful.

**Closed by thc202** 2023-08-16 08:02 UTC
Labels: enhancement, add-on, in:spider
