### ISSUE TITLE
ZAP API Scan not working as intended

### ISSUE THREAD

**Issue by palok86** [zaproxy/zaproxy#5866] opened 2020-02-18 16:01 UTC
**Describe the bug**
When i am trying to import context through the API , always get the error that {"code":"does_not_exist","message":"Does Not Exist"}
I tried this through gui as well but same result.
https://localhost:8090/JSON/context/action/importContext/

**To Reproduce**
1. Go to 'localhost:8090/UI/context'

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: [note that we typically only support the latest version of ZAP]
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

**Additional context**

**Comment by kingthorin** [comment] 2020-02-18 16:38
Screenshots?
Version details?
Log file info?

**Comment by palok86** [comment] 2020-02-19 02:40
Steps to reproduce?
- Run zap as a docker container
docker run -u zap -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=xxxxxxxxx
- Using curl to set my application context. Context file attached.
[bodgeit.context.txt](https://github.com/zaproxy/zaproxy/files/4222833/bodgeit.context.txt)

 
curl -k -X GET https://localhost:8090/JSON/context/action/importContext/?contextFile="bodgeit.context" \
  -H 'Accept: application/json' \
  -H 'X-ZAP-API-Key: xxxxxxxxxx'
Screenshots?
![image](https://user-images.githubusercontent.com/18442604/74796587-0198ff00-5304-11ea-96d2-ba426ce93bb9.png)

Version details?ZAp 2.9
Log file info?
36754656 [ZAP-ProxyThread-46] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/JSON/context/action/importContext/] from [172.17.0.1]:
Does Not Exist (does_not_exist) : /home/zap/.ZAP/contexts/home/alok/Desktop/ZAP/bodgeit.context
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:201)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:506)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kingthorin** [comment] 2020-02-19 02:48
You need to specify a context file that actually exists and you can read:
` Does Not Exist (does_not_exist) : /home/zap/.ZAP/contexts/home/alok/Desktop/ZAP/bodgeit.context`

I think the problem might be the quotes you're including on the path/filename. As dicussed here: https://groups.google.com/forum/#!searchin/zaproxy-users/relative%7Csort:date/zaproxy-users/rLWqXLKMYsM/FCXV7VX5FQAJ

> OK, took me a while to notice, the path should not be quoted otherwise it will be interpreted as a relative path not absolute. If you remove the quotes it should load correctly.

Also probably related to or duplicate of:

- https://github.com/zaproxy/zaproxy/issues/5772
- https://groups.google.com/forum/#!searchin/zaproxy-users/relative%7Csort:date/zaproxy-users/i2azWjBftaY/A00d0L_2FQAJ

**Comment by palok86** [comment] 2020-02-19 04:53
still same. Attaching screenshot

![image](https://user-images.githubusercontent.com/18442604/74803093-afada480-5316-11ea-8f0d-a5f086ebef8d.png)

**Comment by ricekot** [comment] 2020-02-19 05:59
I was able to reproduce this behaviour, but it seems that the quotes are not the problem here. A quick look at the docker daemon logs tells us that the bodgeit.context file must be copied to the container first.

![Screenshot from 2020-02-19 11-06-43](https://user-images.githubusercontent.com/16446369/74805020-ff38a400-5307-11ea-9992-521c10cc1535.png)

The curl command works after copying the bodgeit.context file to the container.

![Screenshot from 2020-02-19 11-09-39](https://user-images.githubusercontent.com/16446369/74805179-622a3b00-5308-11ea-9434-69476a889573.png)

However, we get a parsing error this time [the context file must be valid XML, not JSON].

![Screenshot from 2020-02-19 11-22-56](https://user-images.githubusercontent.com/16446369/74805975-b7674c00-530a-11ea-8454-9b63359eaa37.png)

Converting the JSON context file to XML and then running curl (after copying the file to the container) should work.

**Comment by thc202** [comment] 2020-02-19 10:26
Closing, as the above comment says, this is working as expected. By default Docker containers don't have access to the host's file system you need to allow it, you also need to use the corresponding path in the container not the one in the host's file system, more information in:
https://docs.docker.com/storage/bind-mounts/
https://docs.docker.com/storage/volumes/

**Closed by thc202** 2020-02-19 10:26 UTC

**Comment by palok86** [comment] 2020-02-19 12:50
worked thanks!!
Cheers
