### ISSUE TITLE
Generate report for a specific scan using ZAP API

### ISSUE THREAD

**Issue by raghuveerbathini** [zaproxy/zaproxy#3071] opened 2016-12-15 11:48 UTC
The API for html/xml report generation, is not accepting the ScanId paramter.

**Comment by psiinon** [comment] 2016-12-15 11:51
Duplicate of #2920

**Comment by thc202** [comment] 2016-12-15 11:51
Please, don't open duplicated issues. Merging into #2920.

**Closed** 2016-12-15 11:50 UTC

**Comment by thc202** [comment] 2016-12-15 11:52
(Missed your comment.)
