### ISSUE TITLE
Deleting a category of Alerts, or multiple individual Alerts, only deletes 1 Alert

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#8001] opened 2023-08-10 19:09 UTC
### Describe the bug

On the Alerts tab, if you click on a folder (which is a category of alerts of the same type), and then right click and say delete, it only deletes ONE of the alerts in that category, instead of all of them. I.e., if the count was 10, then count drops to 9 and one of them goes away. It should delete ALL the alerts in that category. The same thing happens if you multiselect two or more Alerts, it only deletes one of them.

And if you multiselect two or more alerts, or two or more categories of alerts, it should delete ALL of them, not just one.

You should probably have logic for ALL the right click features to detect if multiple alerts are multiselected, or a category, or multiple categories are selected, and have the proper logic particular to that function to handle these situations appropriately.

### Steps to reproduce the behavior

1. Go to the Alerts tab
2. Select a category folder with 2 or more alerts.
3. Right click then agree to delete.

You'll then see that only 1 Alert gets deleted.

When I do a similar thing in the Sites tree, by multiselecting a bunch of URLs and deleting them, that seems to work fine.

### Expected behavior

Everything selected should be deleted.

### Software versions

2.13.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment] 2023-08-10 19:13
I believe this is a duplicate of: https://github.com/zaproxy/zaproxy/issues/2593

**Comment by davewichers** [comment] 2023-08-10 19:19
I don't think it is. It's not like they disappear and reappear. It simply only deletes 1, rather than all of those selected.

**Comment by kingthorin** [comment] 2023-08-10 19:27
Please add version information from ZAP’s menu Help > Support Info, or from the CLI using the -suppinfo switch.

**Comment by thc202** [comment] 2023-08-10 19:33
The expected behaviour is already what's implemented, knowing the exacts steps to reproduce the issue would be greatly appreciated (2593 is not just about disappear/reappear, I also suspect it's that issue).

**Comment by davewichers** [comment] 2023-08-10 19:35
I put the exact steps on how to replicate this in the description above. Just multiselect two or more Alerts, right click, delete, and only 1 gets deleted.

**Comment by thc202** [comment] 2023-08-10 19:39
That's not really enough to replicate the issue, if I do that the alerts get deleted (as expected). It's not just about selecting the alerts but which alerts are selected.

**Comment by kingthorin** [comment] 2023-08-10 20:22
It could also be some sort of ui or platform issue so having the full requested support info would really help.

**Comment by davewichers** [comment] 2023-08-10 22:48
I just tried this on my Apple Silicon Mac and it didn't behave like this. The machine I originally reported this on was running Windows. Can someone test on Windows to see if that could be the difference?

**Comment by kingthorin** [comment] 2023-08-11 00:38
This is why the support info is important (and asked for in the issue template). It tells us things like which jre, gui and look & feel details, locale settings, etc.

I can probably try on Windows at some point tomorrow but still won't know if that's apples to apples.

**Comment by kingthorin** [comment] 2023-10-03 17:42
Tested on a fresh Win 11 VM. Unable to reproduce.

**Closed by kingthorin** 2023-10-03 17:42 UTC
Labels: bug
