### ISSUE TITLE
ZAP Docker api scan does not override endpoint URL

### ISSUE THREAD

**Issue by Sticcia** [zaproxy/zaproxy#6673] opened 2021-07-07 11:56 UTC
**Describe the bug**
Running in a Docker container with mounted specification file.
Execution `zap-api-scan.py -t <path-to-local-file>` with `-O <host-name>` parameter does not override URL.
Changing parameter to `-t <url-to-remote-file>` overrides URL correctly.

**To Reproduce**
1. Run `zap-api-scan.py -t <file> -O <host-name>`
  a. Where `<file>` is an url to a remote specification file
  b. Where `<file>` is a path to a local specification file
2. Compare results

**Expected behavior**
Override of target URL in both cases (url to remote file and path to local file)

**Software versions**
 - ZAP Docker container: `owasp/zap2docker-stable`

**Errors from the zap.log file**
```
21312 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter - Failed to build/normalise the API URL using Server URL: /
java.lang.IllegalArgumentException: The scheme must not be null.
	at org.zaproxy.zap.extension.openapi.converter.swagger.UriBuilder.validateNotNull(UriBuilder.java:279) ~[openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.UriBuilder.build(UriBuilder.java:252) ~[openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.createApiUrls(SwaggerConverter.java:259) [openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:182) [openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:159) [openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:289) [openapi-beta-19.zap:?]
21312 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Unable to obtain any server URL from the definition.
org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Unable to obtain any server URL from the definition.
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.createApiUrls(SwaggerConverter.java:272) ~[openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:182) ~[openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:159) ~[openapi-beta-19.zap:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:289) [openapi-beta-19.zap:?]
```

**Additional context**
Running ZAP in a local deployment of [RAFT](https://github.com/microsoft/rest-api-fuzz-testing)

**Comment by thc202** [comment] 2021-07-07 12:07
Closing as duplicate of #5510.

**Closed by thc202** 2021-07-07 12:07 UTC
Labels: Docker, bug
