### ISSUE TITLE
Failure to Launch Browser

### ISSUE THREAD

**Issue by JewelsC** [zaproxy/zaproxy#6905] opened 2021-11-03 16:33 UTC
Chrome will not launch.  Firefox is failing to load.  Worked with my company's help desk.  This is a known issue with others in my company.

**To Reproduce**
1. Go to Manual Explore
2. Type in any URL
3. Click Launch Browser with Chrome selected in dropdown
4. Chrome will attempt to open and then will fail to fully load.

**Expected behavior**
Chrome should open to the indicated URL

**Software versions**
 - ZAP2.11.0

**Additional context**
This is tied to a deliverable and could cause a delay in the release.  

**Would you like to help fix this issue?**
Any help provided would be amazing.

**Comment by kingthorin** [comment] 2021-11-03 16:37
OS?
Java version?
Add-on versions?

Those are part of the template for a reason.

**Comment by JewelsC** [comment] 2021-11-03 16:43
Operating System: Windows 10
Java Version: Amazon.com Inc. 1.8.0_282
Add-ons version=13.0.0

**Comment by thc202** [comment] 2021-11-03 16:48
You should check the version of the WebDrivers add-on, and most likely update it.

**Comment by kingthorin** [comment] 2021-11-03 16:54
>  Add-ons version=13.0.0

Not all add-ons have a single version.
https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/

**Comment by JewelsC** [comment] 2021-11-03 16:57
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=41.0.0], [id=automation,
version=0.8.0], [id=bruteforce, version=11.0.0],
[id=commonlib, version=1.5.0], [id=diff, version=11.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=11.0.0], [id=encoder, version=0.6.0],
[id=formhandler, version=4.0.0], [id=fuzz, version=13.4.0],
[id=gettingStarted, version=13.0.0], [id=graaljs,
version=0.2.0], [id=graphql, version=0.7.0], [id=help,
version=12.0.0], [id=hud, version=0.13.0], [id=importurls,
version=8.0.0], [id=invoke, version=11.0.0], [id=oast,
version=0.5.0], [id=onlineMenu, version=9.0.0], [id=openapi,
version=23.0.0], [id=pscanrules, version=36.0.0],
[id=quickstart, version=30.0.0], [id=replacer,
version=9.0.0], [id=reports, version=0.9.1], [id=retest,
version=0.2.0], [id=retire, version=0.9.0], [id=reveal,
version=4.0.0], [id=saverawmessage, version=6.0.0],
[id=savexmlmessage, version=0.2.0], [id=scripts,
version=29.0.0], [id=selenium, version=15.4.0], [id=soap,
version=11.0.0], [id=spiderAjax, version=23.7.0], [id=tips,
version=9.0.0], [id=webdriverwindows, version=33.0.0],
[id=websocket, version=24.0.0], [id=zest, version=35.0.0]]

**Comment by thc202** [comment] 2021-11-03 17:27
Since you are already using the latest version ensure that Chrome is supported with the bundled ChromeDriver: https://www.zaproxy.org/docs/desktop/addons/windows-webdrivers/ (if it is you might need to remove the old ChromeDriver in the ZAP home dir).

**Comment by kingthorin** [comment] 2021-11-05 09:59
@JewelsC any update based on previous advice?

**Comment by davewichers** [comment] 2021-12-09 20:56
@JewelsC - I have a related comment (going to open a separate ticket on that). If you run ZAP at the command line, browser launch failure errors get reported to the console. For example, in my case, I'm seeing the following error. But this is NOT a ZAP Bug, rather I don't have FireFox installed properly in a way ZAP can find/launch it. You might want to try from the command line to see if it provides any helpful details on what the problem is.

178356 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DYLPMR2', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DYLPMR2', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:100) ~[?:?]
        at java.util.Optional.orElseGet(Optional.java:267) ~[?:1.8.0_251]
        at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:216) ~[?:?]
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187) ~[?:?]
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1009) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:868) ~[?:?]
        at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:754) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:561) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:710) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:651) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:627) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:611) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:601) ~[?:?]
        at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:209) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by thc202** [comment] 2021-12-10 07:59
Closing, no further details provided.

**Closed by thc202** 2021-12-10 07:59 UTC
Labels: InsufficientEvidence, add-on
