### ISSUE TITLE
The Manual Explore option does not work ?

### ISSUE THREAD

**Issue by Anthonymcqueen21** [zaproxy/zaproxy#6170] opened 2020-09-13 03:23 UTC
Hello my problem is the manual explore option on ZAP on my Kali-Linx does not work no matter what i do. I imported all the certificates and so on and nothing but the automatic scan works fine. But why does my Manual Explore does not that is weird to me. I tried to send you a vid but its not supported.

- Thank you.

**Comment by kingthorin** [comment] 2020-09-13 09:48
This is a duplicate of: https://github.com/zaproxy/zaproxy/issues/6115

For now the workaround is:
```
1. Launch ZAP.
2. Goto Tools > Options.
3. Go down to the Selenium section.
4. In the Binaries > Firefox: field enter /usr/bin/firefox-esr
5. Click "Ok"  in the Options dialog to accept the changes.
5. Try launching Firefox from within ZAP.
```

**Closed by kingthorin** 2020-09-13 09:48 UTC

**Comment by Anthonymcqueen21** [comment] 2020-09-15 03:07
Thank you so much it works fine within my Kali-Linux Machine.
