### ISSUE TITLE
Last session opening on startup

### ISSUE THREAD

**Issue by sadranasiri** [zaproxy/zaproxy#7755] opened 2023-02-24 12:32 UTC
### Describe the bug

We have created a session and saved it in the session folder which is including several scans. the issue is that when we close the ZAP application and open it again then open the saved session from the file menu, the previous scans will be loaded but when scanning a new website, the scan ID will be created from Zero (0). it doesn't count the last scan IDs.

May we know how to get the last Scan  IDs first and then new IDs when opening the ZAP app again? or how can we load the last session automatically on the app startup and count the last Scan IDs

### Steps to reproduce the behavior

1. Open the zap app
2. Click on the file menu
3. click on the open session
4. choose the saved session we want to load

### Expected behavior

to keep the previous Scan IDs and continue from the last scans while opening the ZAP app again

### Software versions

2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment] 2023-02-24 12:42
This seems to be a duplicate of #4270.

**Comment by sadranasiri** [comment] 2023-02-24 15:36
Actually, it seems that the other issue is different from mine, the other one is when pausing and then resuming it.
My issue is the scan IDs that start from zero everytime I close and then open the ZAP app even while opening the last saved session

**Comment by thc202** [comment] 2023-02-24 15:44
What you are asking is part of that issue, if we persist the state of the scans their IDs (and the sequence) will be preserved between runs.

**Comment by kingthorin** [comment] 2023-02-24 15:44
Why is it relevant what the scan ID is?

**Closed** 2023-03-08 13:43 UTC
