### ISSUE TITLE
Search Feature for Scripts

### ISSUE THREAD

**Issue by lpinilla** [zaproxy/zaproxy#6402] opened 2021-01-15 18:08 UTC
**Is your feature request related to a problem? Please describe.**
On the scripting tab, I know the name of the script I want but I don't know where it is.

**Describe the solution you'd like**
A search bar could filter all scripts by name.

**Describe alternatives you've considered**
Filter view by category instead of tree view, so if I want al HUD scripts, I could select from a drop down menu "HUD" an only see scripts for that.

**Would you like to help implementing this feature?**
Yes I would like

**Comment by kingthorin** [comment] 2021-01-15 18:21
Could probably use this functionality: https://github.com/zaproxy/zaproxy/pull/4141 which can currently be seen used in the options panel, active scan policy dialog, etc.

The code for the scripts addon can be found here: https://github.com/zaproxy/zap-extensions/tree/master/addOns/scripts

**Comment by thc202** [comment] 2021-01-15 18:28
Seems to be a duplicate of #5737.

**Comment by lpinilla** [comment] 2021-01-15 18:30
yes it is, sorry I didn't find it before posting the issue

**Closed** 2021-01-15 18:32 UTC
Labels: Component-Scripts, add-on, enhancement

**Comment by thc202** [comment] 2021-01-15 18:40
No worries, can you comment in other issue so that it can be assigned to you?
